### ISSUE TITLE
Could we auto resize when container size changes instead of every X seconds?

### ISSUE THREAD

**Issue by aml2610** [visjs/vis-network#1011]
Hi, thanks again for this awesome library!

I'm trying to set up auto-resize for the following use case:
- on my screen, I am displaying a vis graph and also some other UI elements which can be shown or not, conditionally
- I want the graph to always resize itself whenever one of the other UI elements appears on/disappears from the page; I want it to resize so as to fit the remaining space fully (by remaining space I mean the space not taken up by the other UI elements)

I looked through the code and it seems to resize itself every 1 second (correct me if I am wrong), but (at least for my use case) it seems like a more robust approach would be to listen for when the container is resized and only then trigger a resize.
The advantage here is we don't have to wait the <= 1 second before the resize happens.

I have not tried to re-write the code to work like this, at this point it is just an idea. I was wondering if anyone has any thoughts on such a feature (resize when container is resized instead of every X seconds)?

I could help with the implementation if we find it's a useful feature.

Best
Andrei

**Comment by Thomaash** [comment]
Hi @aml2610,

this is purely about compatibility. If it works in all browsers from [this live list](https://browserl.ist/?q=%3E+0.1%25+and+not+dead), then we can do it. Otherwise the answer is not yet.

**Comment by aml2610** [comment]
Hi @Thomaash 

With a polyfill like [this one](https://github.com/que-etc/resize-observer-polyfill) I think we can achieve that, thoughts?
Is there an automatic way to test on all browsers?
