### ISSUE TITLE
Is it possible to change the zoom speed on mouse scrolling / trackpad scrolling?

### ISSUE THREAD

**Issue by willfinnigan** [visjs/vis-network#1018]
Hi,

Great project.  Apologies if this is covered somewhere in the documentation, but I've been through it a few times I can't find anything.

I recently upgraded from v4.something to the lastest version on unpkg, and it seems the zoom speed of networks is quite a bit faster.

Is there anyway I can control how quickly scrolling with the mouse wheel or trackpad zooms a network in or out?  I'd like to make it a bit slower as it seems quite jumpy now.

For reference, heres an example of how I'm using visjs.  [https://retrobiocat.com/network_explorer/ab97a1a1-abbd-4c14-b248-68a2308cf7b1/](https://retrobiocat.com/network_explorer/ab97a1a1-abbd-4c14-b248-68a2308cf7b1/)

**Comment by Thomaash** [comment]
Hi @willfinnigan,

you can change `options.interaction.zoomSpeed`, it's just a number (1 is the default).

**Comment by Thomaash** [comment]
It should appear in the docs soon.

**Comment by willfinnigan** [comment]
Great, thank you!
