### ISSUE TITLE
Needs demystifying for the `node.x` and `node.y` attributes

### ISSUE THREAD

**Issue by laike9m** [visjs/vis-network#1027]
First, thanks for making this lib, I just became a contributor 😀

To the real issue, I find the `node.x` and `node.y` attributes really confusing.

![image](https://user-images.githubusercontent.com/2592205/92361930-0a84ce80-f0a4-11ea-88fe-7138a0819b66.png)

It seems to suggest that **the attributes work with the hierarchical layout**, but I tried all config combinations, none worked. 

See https://jsfiddle.net/laike9m/dg8Lzt7c/339/

In the above snippet, I set `node.x` and `node.y` to be `50`, with `fixed` equal to `true`:

```javascript
var nodes = new vis.DataSet([
  {
    title: "Aaaa",
    id: "id1",
    label: "1",
    level: 1,
    x: 50,
    y: 50,
    fixed: true
  },
  {
    id: "id2",
    label: "2",
    level: 2,
    x: 50,
    y: 50,
    fixed: true
  },
  {
    id: "id3",
    label: "3",
    level: 3,
    x: 50,
    y: 50,
    fixed: true
  }
]);
```

And this is the rendered graph. Apprantely the position settings didn't take effect.

![image](https://user-images.githubusercontent.com/2592205/92362273-9dbe0400-f0a4-11ea-8c7b-77c3ff8334a1.png)

So it could be I misinterpret the doc, or I used it in the wrong way. Either way, some explanation could be helpful.

**Comment by laike9m** [comment]
Again, this is me trying to tackle the issue in https://stackoverflow.com/q/63314093/2142577 without adding hidden edges.

**Comment by Thomaash** [comment]
Hierarchies (sets of nodes interconnected via edges, each node in your example is a standalone hierarchy) are placed side by side regardless of the coordinates of the nodes as there can be many conflicting coordinates violating hierarchical layout. Why do you turn hierarchical layout on anyway?

**Comment by Thomaash** [comment]
I get the feeling that your trying to combine hierarchical (blue on SO) and nonhierarchical (red on SO) layouts at the same time. This is currently not implemented, see #203.

**Comment by laike9m** [comment]
Let me explain my real use case, hopefully it could explain why I need it.

So I'm currently working on a tool to visualize code execution:
https://twitter.com/PyCyberbrain/status/1302827633613238273

As you can see in the above video, in the trace graph (right side), I have some nodes to show line number (8, 9, 10 in this case). These lineno nodes, along with other nodes representing code execution, are placed in a hierarchical graph, with each node's level representing its lineno. This ensures that code execution happened at line `N` is placed on the same height with the line number node.

Now, to align lineno nodes vertically, I added some hidden edges between the nodes, like you suggested in the SO question. I want to see if I can achieve the same result without hidden edges, and I also want to move these nodes to the left a little bit by manually setting `x`.

> Hierarchies (sets of nodes interconnected via edges, each node in your example is a standalone hierarchy) are placed side by side regardless of the coordinates of the nodes as there can be many conflicting coordinates violating hierarchical layout. Why do you turn hierarchical layout on anyway?

To be honest I don't fully get it. Do you mean that neither setting `x` nor `y` will take effect in hierarchical layout? My interpretation of the documentation is that, if I use `UD`/`DU`, I can control `x`; if I use `LR`/`RL`, I can control `y`.

**Comment by Thomaash** [comment]
I don't know where you got this interpretation as the direction docs say nothing even remotely similar.

Hierarchical layout sets x and y, custom coordinates could easily violate the layout and therefore can't be safely honored. If you just want to space the hierarchies (lineno vs code) a bit more, you can use `treeSpacing` to do that.

**Comment by laike9m** [comment]
Ok, it's good to know that I misunderstood the doc. But this paragraph is really confusing

> When using the hierarchical layout, either the x or y position is set by the layout engine depending on the type of view. The other value remains untouched.

Especically it says "The other value remains untouched", which gives readers the impression that hierarchical layout will keep the specified `x` or `y` untouched. Perhaps this part needs to be revised a little bit?

**Comment by Thomaash** [comment]
Thanks for pointing this out, the paragraph wasn't so much confusion as it simply wasn't true.

**Comment by laike9m** [comment]
Thanks for the fix
