### ISSUE TITLE
Documentation, broken link 

### ISSUE THREAD

**Issue by ashwinkumar6** [visjs/vis-network#103]
The following hyperlink (present under network-> edges ->  smooth -> smooth.type)
throws a 404 page not found Error
https://visjs.org/examples/network/edgeStyles/smooth.html

**Comment by Thomaash** [comment]
Where exactly did this link come from? Clicking through the page I got this instead: https://visjs.github.io/vis-network/examples/network/edgeStyles/smooth.html .

**Comment by Thomaash** [comment]
Oh, it came from the docs. That's indeed broken.

**Comment by Thomaash** [comment]
Broken link is on https://visjs.github.io/vis-network/docs/network/edges.html .

PS: @ashwinkumar6 next time post a link to the page with the broken link please. A list of steps to click through can be easily misunderstood.
