### ISSUE TITLE
title field is not displayed with version 8.3.2

### ISSUE THREAD

**Issue by smoretti** [visjs/vis-network#1039]
Hi

the title field is not displayed with version 8.3.2. It was displayed with version 8.2.0 before.

Here is the code I use.
Did something change with version 8.3.2?

`<script>
var nodes = new vis.DataSet([{id: 'MNXM6571', label:'MNXM6571', title: 'deprecated' },
{id: 'MNXM739268', label:'MNXM739268', title: 'Inulin', font: {color: '#C74F00' }},
{id: 'MNXM739269', label:'MNXM739269', title: 'this entry', font: {color: '#008570' }}]);
var edges = new vis.DataSet([{ from: 'MNXM6571', to: 'MNXM739268', color: 'gray', arrows: { to: { enabled: true, type: 'triangle' }}},
{ from: 'MNXM6571', to: 'MNXM739269', color: 'gray', arrows: { to: { enabled: true, type: 'triangle' }}}]);
var container = document.getElementById('depr_net');
  var data = {
    nodes: nodes,
    edges: edges
  };
  var options = {
    nodes: {
        font: '13px Arial #202020',
        shape: 'box',
        color: {
            border: 'white',
            background: 'white'
        }
    },
    interaction: { hover: true, zoomView: false },
    layout: { randomSeed: 'Mickey' }
};
var network = new vis.Network( container, data, options );
network.on( 'click', function (params) {
    if( params.nodes[0] ){
        window.location.href = params.nodes[0];
    }
});
</script>`

**Comment by MacroChip** [comment]
I'm seeing this as well. In previous versions, there were a number of style tags put in the head. One of those tags was
```html
<style type="text/css">div.vis-tooltip{position:absolute;visibility:hidden;padding:5px;white-space:nowrap;font-family:verdana;font-size:14px;color:#000;background-color:#f5f4ed;-moz-border-radius:3px;-webkit-border-radius:3px;border-radius:3px;border:1px solid #808074;box-shadow:3px 3px 10px rgba(0,0,0,.2);pointer-events:none;z-index:5}</style>
```

Feel free to add that style to your head in the meantime.

**Comment by smoretti** [comment]
Thanks, I will look at that.
But strange the behavior of title display changed between releases 8.2 and 8.3

**Comment by Thomaash** [comment]
Hi @smoretti and @MacroChip,

could you provide some more info about this (browser, OS, platform, imports…)? Because the tooltips are there, see [MWE](https://jsfiddle.net/dnep7zv2/).

Thanks.

**Comment by MacroChip** [comment]
We must have gotten our js from a different folder in unpkg. See https://jsfiddle.net/vgthfux8/. What is the dist folder for in unpkg? There are differences between `dist` and `standalone`.

**Comment by Thomaash** [comment]
https://jsfiddle.net/vgthfux8/ fails with `ReferenceError: vis is not defined`.

Dist is the legacy format that came from the botched split this library underwent between versions 4 and 5. Standalone, peer and esnext are from an attempt at solving the issues of dist (they work but are confusing, see the examples for more details on how to use them). Dist doesn't contain CSS, standalone does, which is most likely what makes the titles (and some other stuff too) disappear in your case.

**Comment by MacroChip** [comment]
I guess I didn't save the jsfiddle but I was using the `dist` version so that was the issue for me. Thanks.

**Comment by smoretti** [comment]
So the issue is on my side or in version 8.3.2?
I did not get it
