### ISSUE TITLE
edges middle hover event

### ISSUE THREAD

**Issue by zy960814** [visjs/vis-network#1044]
option：{
    edges: {
           arrows:{
                middle:{
                 chosen：{}，
                 hover：{}，
                }
           }
     },
}
I want get edges middle hover，not edges hover 。

**Comment by Thomaash** [comment]
Hi @zy960814,

I'm not sure what exactly you mean. Could you elaborate on this a bit more?

Thanks.

**Comment by zy960814** [comment]
I want to get the hover event for the center arrow。But I didn't see it on the document

**Comment by Thomaash** [comment]
Hi @zy960814,

this isn't currently possible. You can supply a PR though and thank you very much if you do.
