### ISSUE TITLE
Feature-Request: support image padding for the image shape

### ISSUE THREAD

**Issue by r3code** [visjs/vis-network#105]
I'd like to add a feature to set a padding around the image located inside the image shape. It would help to show the shape color for any images as for now to achieve this you need to use PNG with transparent borders inside the image to mimic such behavior.
I have already some code and example [here in my fork](https://github.com/r3code/vis-network/commit/ccedba321b72bc0885875ba0e0d9337c54a95c56).

It allows to set the individual image padding at Node level:
`imagePadding: { left: 2, top: 10, right: 8, bottom: 20},`
or
`imagePadding: 10`
It also takes care of `useImageSize`, if `useImageSize = true` then the resulting shape size calculated as image dimensions + image padding. Else image dimensions reduced by image padding to save the shape dimensions set by `size` at network or node level options.

![vis-network_imagePadding](https://user-images.githubusercontent.com/1355056/64082141-422f9c80-cd13-11e9-8048-087e4e5f9b7b.png)

**Comment by Thomaash** [comment]
Hi @r3code,

I don't have anything against such feature. Your repo however doesn't seem to contain the source code, only the example and the distribution bundle. After you commit the source files feel free to open a PR where we can discuss it in greater detail including the implementation.

Thanks.

**Comment by r3code** [comment]
@Thomaash I just tried at dist yesterday ) Today I'll put in modules

**Comment by r3code** [comment]
Feature added by PR  https://github.com/visjs/vis-network/issues/106 at https://github.com/visjs/vis-network/commit/7e4aff667119eb538e88809fac8afcce58014803
