### ISSUE TITLE
Flexible spacing between levels in hierarchica layout

### ISSUE THREAD

**Issue by laike9m** [visjs/vis-network#1064]
For context, the use case was described [here](https://github.com/visjs/vis-network/issues/1027#issuecomment-688501428).

What I find annoying is that, when the lineno has a large range, and nodes are relatively sparse, the fixed distance between levels would make the graph unnecessarily tail...

![image](https://user-images.githubusercontent.com/2592205/93979234-ed056500-fd31-11ea-8f3c-f8dd31f5fc97.png)

I'm wondering, can we add an option to enable flexible spacing between levels? So that there's a minimal space between two adjacent levels that **have nodes**, while the layout system can decide the actual space, presumably minimizing space.

**Comment by Thomaash** [comment]
Hi @laike9m,

two issues. One is that I don't think what you have there is a formal hierarchy, in other words you may be misusing hierarchical layout and trying to force it to do something it wasn't designed to do. The other one is that you force the rendering of a tonne of empty levels and then complain that it renders a tonne of empty levels. Just number the levels 1, 2, 3… and your problem will disappear or if you do have formal hierarchy (the only thing hierarchical layout is supposed to handle), just omit the levels, they'll be inferred from the structure.

**Comment by laike9m** [comment]
Re-numbering the level is something I planned to do. There's some hidden complexity as the numbers of level could change as user interacts with the graph, but that' doable for sure.

I'm not sure if there's a better choice than hierarchical layout. For my use case I need to put nodes that have the same lineno on the same height, so hierarchical layout + level seems to be the only choice? I could be wrong.

**Comment by laike9m** [comment]
kindly ping..😢

**Comment by laike9m** [comment]
Remapped lineno to level and now looks fine. Closing this issue.

![image](https://user-images.githubusercontent.com/2592205/94380750-bb065100-00eb-11eb-9bbb-a06f592d625d.png)
