### ISSUE TITLE
How to force a network to stop moving after some times

### ISSUE THREAD

**Issue by smoretti** [visjs/vis-network#1079]
Hi

For most networks the physics works and they stabilize (stop moving) quickly.
Nevertheless some networks never stop moving.
E.g. https://www.metanetx.org/chem_info/MNXM729615

How to force a network to stop moving?

I use vis-network version 8.2.1

**Comment by Thomaash** [comment]
Hi @smoretti

Unfortunately the physics sometimes gets stuck in chaotic movement and never stops. You can interrupt it with `network.stopSimulation()`, which technically speaking would be exactly the answer you asked for, however it will most likely restart chaotic movement as soon as you do anything with the network, which is unlikely to be what you want.

If you don't need physics enabled, you can disable it and use `network.stabilize(number)` where `number` is the number of iterations it will do and then it will stop regardless of the state of the network.

If you want to keep physics enabled, you can try playing with Force Atlas 2, it is less likely to end up moving forever than the default Barnes Hut in my experience.

**Comment by smoretti** [comment]
I tried the **forceAtlas2Based** solver but for me on large networks the colors I put on nodes, as well as the text, disappear. The network stops moving very quickly.

So I tried with _network.stabilize(10)_ and/or _physics: { stabilization: { iterations: 10 } }_ with the **barnesHut** solver but the network does not stop moving.

**Comment by Thomaash** [comment]
Hi @smoretti,

I suggested to disable physics (`physics: { enabled: false }`) and run `network.stabilize(10)` manually as a possible solution, running with the physics enabled has little chance of stopping the movement.

Regarding the colors and text disappearing, could you open a new issue for this, elaborate a bit more and provide an MWE (edit [JSFiddle](https://visjs.github.io/vis-network/examples/static/jsfiddle.6aafb848b7cdab2c7e29eccacaac025b14415c67094508dc8ee5f21b2da07e84.html) or so), please?

Thanks.

**Comment by smoretti** [comment]
Thanks it works with `physics: { enabled: false }`

I have opened another issue for the colors and text disappearing #1111
