### ISSUE TITLE
'opencollective' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tillias** [visjs/vis-network#1083]
When running **npm install vis-network**:

> \> vis-network@8.3.2 postinstall .......\node_modules\vis-network
> \>opencollective postinstall || exit 0

'opencollective' is not recognized as an internal or external command,
operable program or batch file.

Win10 64bit

**Comment by Thomaash** [comment]
Hi @tillias,

this is just supposed to ask for donations, you can safely ignore it.
