### ISSUE TITLE
UUID Error

### ISSUE THREAD

**Issue by becerriljc** [visjs/vis-network#1090]
Hi everyone!

I'm working with Angular 10.1.4, I installed:

"@egjs/hammerjs": "^2.0.17",
"keycharm": "^0.3.1",
"uuid": "^8.3.1",
"vis-data": "^7.0.0",
"vis-network": "^8.3.2",
"vis-util": "^4.3.4"

and have this error:

**Unknown error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /home/ubuntu/Documents/angularProjects/visNetwork/node_modules/uuid/package.json**

Thanks for you great job!!

**Comment by Thomaash** [comment]
Hi @becerriljc,

I searched through the code and we don't import `./v4` from `uuid` anywhere. Could you provide an MWE, please?

Thanks.

**Comment by becerriljc** [comment]
Thanks @Thomaash, sure:

Im using:

Angular 10.1.4
Nodejs 12.18.4

First installed dependency:

![2020-10-07_10-15](https://user-images.githubusercontent.com/24251698/95351705-2340f980-0887-11eb-9018-1d0529f5141b.png)

Installed requires dependencies:
![2020-10-07_10-16](https://user-images.githubusercontent.com/24251698/95351832-39e75080-0887-11eb-94ba-7024519b126a.png)

Installed dependencies requires by vis-data
![2020-10-07_10-17](https://user-images.githubusercontent.com/24251698/95352006-64d1a480-0887-11eb-917b-8018f118a40c.png)

And run project:

![2020-10-07_10-18](https://user-images.githubusercontent.com/24251698/95352042-70bd6680-0887-11eb-9a24-b43fb14803d7.png)

Thanks so mucho for u help!

**Comment by Thomaash** [comment]
MWE is something I can run (ideally on JSFiddle, StackBlitz etc.), not a bunch of screenshots showing what you provided the last time anyway. I need to know what `npm run start` does among other things.

**Comment by becerriljc** [comment]
Im sorry, i dont know -whats happend? but i can't reproduce error on stackblitz, reinstall all my package and works fine! 

My apologies, thanks!
