### ISSUE TITLE
[Discussion] Types across vis-network and Visjs

### ISSUE THREAD

**Issue by tiberiushunter** [visjs/vis-network#1093]
Hi,

I'm looking at helping out by adding more types to vis-network (and vis in general) but looking at DefinitelyTyped it's not been updated since May 2019, before vis was deprecated in favour of the community edition vis-network and others. I've also seen the minimal fork for vis-types which looks like is just used to pull any relating commits in from DT.

There's also the ./types in this repo which seems to have newer definitions so my question is where the best place is to submit newer types, (also happy to lend a hand with more migration to TS in general). I don't know if we want the @types/vis to stay at v4.21 as it's deprecated and then a new package (e.g. @types/visjs) for all the new definitions between then and v8.3.2/latest

I had [started a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48620) on DT but I've now since closed that for now while I try to gain some guidance.

Let me know your thoughts,

**Comment by Thomaash** [comment]
Hi @tiberiushunter,

if you could help with this, it would be great. We experimented a bit with the types and in the end decided to just manage them inside each repository, so the ideal place to open PRs is here.
