### ISSUE TITLE
focus outline-style: none; is not working

### ISSUE THREAD

**Issue by tillias** [visjs/vis-network#1101]
Hello folks,

I can't get rid of nasty focus border for canvas. I have tried literally every post I could find on stackoverflow, something like this:

```
.no-focusborder:focus {
  outline-style: none;
  box-shadow: none;
  border-color: transparent;
}

<div class="no-focusborder" id="visNetwork" #visNetwork></div>
```

But there is still border visible.

Please advise

**Comment by Thomaash** [comment]
Hi @tillias,

this is off topic (general CSS/accessibility stuff that has nothing to do with Vis Network specifically). See http://www.outlinenone.com/ for more details.
