### ISSUE TITLE
clickToUse working incorrect.

### ISSUE THREAD

**Issue by tillias** [visjs/vis-network#1102]
Hello folks,

I have investigated https://github.com/visjs/vis-network/issues/1101 a little bit more and it seems root-cause is clickToUse.

![clickToUse-false](https://user-images.githubusercontent.com/753889/95782443-33663800-0cd0-11eb-9b9f-d4a6370ea133.gif)
![clickToUse-true](https://user-images.githubusercontent.com/753889/95782447-33fece80-0cd0-11eb-8750-f087a8dd2642.gif)

For me it is bug, cause if clickToUse -> false, then no border or highlight should be visible.

**Comment by Thomaash** [comment]
Hi @tillias,

the border is a standard accessibility feature that tells the user what is focused at the moment. It has nothing to do with click to use (click to use doesn't affect focusing at all, it just ignores input sent into unfocused canvas, similarly as unfocused windows in most operating systems do) or even this library (place a focusable canvas into the page and you'll see that it does the same). This is not a bug, this is how the web is supposed to work (you can override it, though).

MWE:
```html
<!DOCTYPE html>
<html>
  <body>
    <canvas tabindex="0"/>
  </body>
</html>
```

**Comment by tillias** [comment]
Hi @Thomaash, thanks -> that was exactly what I was looking for. In my use-case it was read-only modal and it was not supposed you could click somewhere except close modal button.
