### ISSUE TITLE
Is there no way to give an initial scale value to the Network?

### ISSUE THREAD

**Issue by baptisteArnaud** [visjs/vis-network#1114]
I read the entire documentation and couldn't find a way to properly fit the graph to the container size:

<img style="width: 300px" src="https://user-images.githubusercontent.com/16015833/96235518-30eb3300-0f9b-11eb-8e35-4b1a6c4e31b8.png"/>

I'd like the network to fit the container. Here it seems too far away and I have to zoom in.

The `fit()` method makes it back to this initial scale.

Is there any way to initially scale up the graph a bit?

**Comment by Thomaash** [comment]
Hi @baptisteArnaud,

fit indeed zooms out but doesn't zoom in beyond 1:1. Implementing this should be rather simple, though. Simply adding `zoomIn` parameter (it already takes an object) to fit and not capping the zoom at 1:1 if it's true should do the trick.

**Comment by baptisteArnaud** [comment]
Thank you for your answer @Thomaash !

I can't seem to find this `zoomIn` parameter in the doc. Where is it? 😅
