### ISSUE TITLE
network.fit() does not work with scale > 1?

### ISSUE THREAD

**Issue by pettno** [visjs/vis-network#1157]
The doc states that network.fit() works for scale from 0 to 1, but that's not what I would expect. I failed to make a simple solution for autofit on load (and resize) for all my networks. Trying to set maxZoomLevel like this did not help:
`network.fit({maxZoomLevel: 1000.0});`

[This issue](https://github.com/almende/vis/issues/1908) seems to refer to the same functionality without an easy solution. I managed making [something like this](https://stackoverflow.com/a/37915105), but it feels like this should be much simpler.

I'm using vis-network 8.3.2 and Chrome 85.0.4183.102.

**Comment by Thomaash** [comment]
Hi @pettno,

fit's max zoom level option was implemented in 8.5.0, this functionality is not and is never going to be available in older versions.
