### ISSUE TITLE
Remove Shapes4FREE icons

### ISSUE THREAD

**Issue by ajorg-aws** [visjs/vis-network#116]
The documentation uses [external link icons](https://github.com/visjs/vis-network/tree/master/docs/img/external-link-icons) from [Shapes4FREE](http://www.shapes4free.com). The [Shapes4FREE License](http://www.shapes4free.com/license/) is not an open source license (does not allow redistribution). There are comparable icons available from open source icon libraries. For example, [Feather](https://feathericons.com) has a nice external link icon and an MIT License. Font Awesome also has some external link icons and a CC-BY-4.0 license for those, and there are likely other open source projects with similar icons. Alternatively, Unicode has the ↪ character, which is often used to denote external links, though it's not as familiar.

Would you consider replacing the Shapes4FREE icons with open source icons?

**Comment by mojoaxel** [comment]
@ajorg-aws Thanks!
We should replace these icons!

**Comment by r3code** [comment]
Related #31

**Comment by r3code** [comment]
We can use instead of https://github.com/visjs/vis-network/blob/master/docs/img/external-link-icons/external-link-icon.png a "shortcut" icon from https://iconsvg.xyz/

**Comment by r3code** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" width="5" height="5" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="3" stroke-linecap="square" stroke-linejoin="arcs"><g fill="none" fill-rule="evenodd"><path d="M18 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8c0-1.1.9-2 2-2h5M15 3h6v6M10 14L20.2 3.8"/></g></svg>`

![img](https://user-images.githubusercontent.com/1355056/64377302-cdba6d80-d032-11e9-9111-12a0bf678613.png)

**Comment by r3code** [comment]
@mojoaxel maybe we just remove them? I didn't find any reference in vis-network files.

**Comment by r3code** [comment]
> @r3code do you plan to open PRs?

You propose me to delete them by myself for all the projects you have listed?

**Comment by Thomaash** [comment]
If you want to you can. My motivation for opening these additional issues and not doing it myself was that this is a straightforward thing for first time contributors who don't have deep insight into the project but still want to contribute. You know something easy that anybody can do and then maybe work their way up to more complex contributions.
