### ISSUE TITLE
Disable scroll wheel/touchpad zoom

### ISSUE THREAD

**Issue by btantlinger** [visjs/vis-network#1172]
I find many users have a hard time with the default zooming on mouse wheel or touch pad scroll. 

For example, It blocks them from scrolling up and down the page, captures their mouse events, and zooms the network when that is not what they intended to do.  In addition, for many visualizations zooming is not needed.  However, there does not seem to be a way to disable this behavior other than overriding network.body.eventListeners.onMouseWheel

**Comment by Thomaash** [comment]
RTFM (read the fine manual): specifically `zoomView` on https://visjs.github.io/vis-network/docs/network/interaction.html or `clickToUse` on https://visjs.github.io/vis-network/docs/network/#options.

PS: Feel free to reopen if I missed something.

**Comment by btantlinger** [comment]
Doh, sorry about that. I don't know how I missed that option!

Thanks
