### ISSUE TITLE
Chromium no longer compatible

### ISSUE THREAD

**Issue by DRJP** [visjs/vis-network#1175]
Hi

New linux versions of the Chromium browser can no longer, & by design, access files in the /tmp directory. It is considered a new security feature.
https://askubuntu.com/questions/1184357/why-cant-chromium-suddenly-access-any-partition-except-for-home

This appears to render some of the visNetwork functionality incompatible with the latest versions of Chromium
ropensci/drake#1345 

Cheers
David

**Comment by Thomaash** [comment]
Hi @DRJP,

I skimmed through the linked pages but I don't see any way how this would relate to Vis Network, it would happen to anything loaded from /tmp. As far as I understand it, Ubuntu switched Chromium from native package to Snap and Snap blocks access to a bunch of directories. Anyway, it doesn't seem like there would be anything in Chromium (I can load files from /tmp just fine in Chromium on Arch) itself or in Vis Network (we are not in control of where people load our library from) that would cause or even could affect this in any way. Keep in mind that Vis Network runs 100% in the web browser, it doesn't even know the host computer has /tmp directory.

PS: Feel free to reopen if there is something I missed or misunderstood. It's quite likely as my knowledge of Ubuntu/Snap/etc. is very limited.
