### ISSUE TITLE
Edge arrow improperly aligned when smooth type is cubicBezier

### ISSUE THREAD

**Issue by ashwinkumar6** [visjs/vis-network#118]
**Steps To Reproduce**
*`edge smooth` type is set to `cubicBezier` 
```
smooth: {
  enabled: true,
  type: 'cubicBezier'
}
```
* enable `arrow` on `middle` of the edge
```
arrows: {
  middle: {
    enabled: true,
  }
},
```
**Expected Behaviour**
Arrow should be placed at the centre of the edge

**Actual Behaviour**
Arrow is placed either above or below the edge

**Basic Information**
browser: Chromium (74.0)
OS: Linux (Ubuntu 16.04)

**Code Example**
[fiddle example](http://jsfiddle.net/ashwinkumar6/q34gkx62/19/)

**Screenshots**
![arrow_alignment](https://user-images.githubusercontent.com/22762119/64371703-e29cfe00-d03e-11e9-98fc-8d069151307a.png)

**Comment by Thomaash** [comment]
It seems to align correctly only when the bezier curve is straight (horizontal and vertical lines) but otherwise it doesn't even align with a straight line: http://jsfiddle.net/thomaash/1ecmw3ra/

**Comment by Thomaash** [comment]
Okay, so the example you provided uses ancient version of vis, not even vis-network.

**Comment by Thomaash** [comment]
With current vis-network it aligns perfectly with a straight line: http://jsfiddle.net/thomaash/1ecmw3ra/5/.

Still an issue though as it doesn't align with the curve that is being rendered.
