### ISSUE TITLE
shape procedure?

### ISSUE THREAD

**Issue by gamadoleo** [visjs/vis-network#1183]
hello i would like to know how to use a form of procedure type, is it possible to create natively used "custom"? attached the photo of the shape
![Screenshot_2](https://user-images.githubusercontent.com/23720707/99386801-cbe46f00-28b1-11eb-95b1-157aca86a8dd.png)

**Comment by Thomaash** [comment]
You can create any type you need. Read the fine manual: specifically `ctxRenderer` on https://visjs.github.io/vis-network/docs/network/nodes.html.

PS: I'm not 100% sure I understand your question properly, feel free to reopen if I didn't.
