### ISSUE TITLE
Unable to pass custom component for Nodes

### ISSUE THREAD

**Issue by onlyreddy** [visjs/vis-network#1194]
Hi,

I'm trying to use visjs with react and found that it's very useful. I tried to pass custom component for each individual nodes but when I checked in visjs docs found that it's not supported for custom components.

Is there any way to achive this?

**Comment by Thomaash** [comment]
Hi @onlyreddy,

you can't pass components as nodes because the graph is rendered on a canvas, it's not HTML. You can however have any shape you want using the custom shape and ctxRenderer function.

**Comment by NickvanDyke** [comment]
Sorry to necro, but in case any future travelers need this functionality (as I did), I made a library for it! https://github.com/NickvanDyke/visjs-html-nodes
