### ISSUE TITLE
Is there a way to set the node label position in the center of the node?

### ISSUE THREAD

**Issue by Instinct408** [visjs/vis-network#1215]
The node label position defaults underneath the node. However, I would like to set it in the center. I can't find this option anywhere.

Edges have this option in font.align. However nodes.font.align just aligns the text which seems inconsistent.

**Comment by Instinct408** [comment]
I found the solution. Change the shape from 'dot' to 'circle'

**Comment by AlexInJar** [comment]
Is it possible to do it for 'dot' node though? I would like to resize the node but also place the label at the center.

**Comment by magsarjav** [comment]
When changing shape type from 'dot' to 'circle', the size of nodes are neglected and they are auto controlled by label texts, which is strange. Is there any other way to do it?
