### ISSUE TITLE
Network - EdgeEdge/EditWithoutDrag return complex objects

### ISSUE THREAD

**Issue by FizzBuzz791** [visjs/vis-network#122]
The `edgeData` that is passed to the `EditEdge`/`EditWithoutDrag` function is a complex object, rather than a standalone edge (perhaps there's a reason for this, documentation is lacking...) and the callback then fails with "Cannot read property 'connected' of undefined" at e.value (vis-network.esm.min.js:13426).

I suspect this has to do with the fact that `edgeData.from` is an object (the "from" edge object) rather than an ID. The same applies to `edgeData.to`. If I do `edgeData.from = edgeData.from.id` before the callback then the callback succeeds and the network graph is updated correctly.

Happy to do a recreation if you really need it, but I think this explains the problem pretty clearly.

**Comment by Thomaash** [comment]
This is definitely a bug not an undocumented feature. We're leaking internal objects from the library which is something that shouldn't happen. Also the variable names in the code suggest it should be the id only.
