### ISSUE TITLE
Edges is not redrawn when physics is disabled

### ISSUE THREAD

**Issue by CoderAllan** [visjs/vis-network#1228]
When I disable physics in the options for a network and drag the nodes in my network to a new position the edges seem to persist some of their properties from before I dragged them. Instead of the edges being redrawn to the shortest path between the nodes the edges get bent into long arcs.

This animation illustrates the issue:
![Not optimal edge behavior](https://raw.githubusercontent.com/CoderAllan/tmpImages/main/PhysicsDisabled.gif)

I have tryed to add a call to redraw() on the dragEnd event, but it did not have any effect. I have also tryed to enable physics only during dragging, but that is not good because it will cause all the other nodes to be moved also during the dragging.

It would be great if there was an option where the edges could be specified as straight lines and not arcs. Is there a way to get the edges to be straight lines? Or is there a way to get the edges redrawn without enabling the physics?

This is the code I used:
```javascript
 var options = {
    physics: {
      enabled: false
    }
  };
  var container = document.getElementById('network');
  var network = new vis.Network(container, data, options);
  network.on('dragEnd', (params) => {
    console.log('dragEnd', params);
    network.redraw(); 
  });
```

**Comment by Thomaash** [comment]
Hi @CoderAllan,

as the gif you provided proves, edges are being redrawn just fine.

If you don't want your edges to have a curve to them (which has to be updated by physics, and therefore doesn't make much of a sense without it), simply disable it:
```typescript
const options = {
  "edges": {
    "smooth": false // Make edges straight lines.
  }
}
```

**Comment by CoderAllan** [comment]
Brilliant, it works just like I wanted it to.
I wonder how I missed that in the docs...
