### ISSUE TITLE
Add 'files' to package.json to reduce the install size

### ISSUE THREAD

**Issue by rdrgn** [visjs/vis-network#123]
I found that installed `vis-network` contains a lot of files needed only during development.
Why not add `files` to package.json?

```
{
  "name": "vis-network",
  ...
  "files": [
    "dist",
    "LICENSE-APACHE-2.0",
    "LICENSE-MIT",
  ],
  ...
}
```

cf. https://docs.npmjs.com/files/package.json#files

**Comment by Thomaash** [comment]
We can't do this because the building process is broken (see #85). We need the source files to build vis-charts where all the packages can properly work together.
