### ISSUE TITLE
Constantly moving nodes

### ISSUE THREAD

**Issue by cburghardt** [visjs/vis-network#126]
I have just added a network map to the z-wave implementation of iobroker using vis.
Now 2 users have reported that their network map is constantly moving. Issue is here including screen caps:
https://github.com/ioBroker/ioBroker.zwave/issues/76

Does anybody have a point how that can be resolved? Disable physics?
On another note, is there a chance to optimize the map when the nodes have a lot of connections between them which is typical for z-wave?

**Comment by Thomaash** [comment]
Hi @cburghardt,

could you try if it still happens with Vis Network 5.4.1? Also an MWE would really help to speed everything up.

Thanks.

**Comment by Thomaash** [comment]
Regarding performance straight edges are much faster than the default smooth ones (you can see the difference on https://visjs.github.io/vis-network/examples/network/other/performance.html if you add a lot of nodes). Also you can remove edges altogether when moving which improves performance a lot usually without much of an impact on usability.

**Comment by Thomaash** [comment]
Disabling physics (if you don't need physics, it will also greatly improve performance) will likely solve this however I don't really know what's going on without an MWE.

**Comment by cburghardt** [comment]
Unfortunately that network is generated dynamically so I even can't reproduce it. But I will give it a shot with disabled physics.
What kind of change of 5.4.1 would help?

**Comment by Thomaash** [comment]
Since I have no idea what is wrong, who knows what change could help.

**Comment by cburghardt** [comment]
Fixed by disabling physics
