### ISSUE TITLE
how to draw arrows

### ISSUE THREAD

**Issue by foxFallingSkies** [visjs/vis-network#1278]
i just want to use canvas to draw arrows...but i can not find the api。。。so..how to do this..

**Comment by stuchl4n3k** [comment]
Hi @foxFallingSkies, check out the [docs regarding edges](https://visjs.github.io/vis-network/docs/network/edges.html), namely the `arrows` property.

**Comment by foxFallingSkies** [comment]
> Hi @foxFallingSkies, check out the [docs regarding edges](https://visjs.github.io/vis-network/docs/network/edges.html), namely the `arrows` property.

thank you...
i know why i can not draw arrows
just because i install all vis...
when i just install vis-network,i can draw
