### ISSUE TITLE
Migrate DefinitelyTyped typings for TypeScript support

### ISSUE THREAD

**Issue by jamesorlakin** [visjs/vis-network#13]
There was a type declaration file on DefinitelyTyped for vis to allow TypeScript developers to enable static analysis and autocomplete in VS Code. Would this project be interested in migrating it over for vis-network?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vis/index.d.ts

I would happily give it a go but the file was never that accurate and I'm not that concrete on vis' inner workings.

**Comment by gflarity** [comment]
@jamesorlakin I'll definitely use it and I'm more than willing to fix and issues I run into it. Might as well go for it?

**Comment by gflarity** [comment]
There's also a tsconfig.json in this project, but no .ts files... so maybe there's something in works?

**Comment by mojoaxel** [comment]
> There's also a tsconfig.json in this project, but no .ts files... so maybe there's something in works?

Thanks to @Thomaash the whole visjs family is moving into the typescript direction :tada: 
The vis-network repository already has one test file written in TS and I'm sure @Thomaash is planning to move a lot in this direction in the future.

Before we change the whole codebase to typescript We really should try to adopt as many existing pull-requests from [almende/vis](https://github.com/almende/vis/pulls) and [visjs-community/visjs-network](https://github.com/visjs-community/visjs-network/pulls?q=is%3Apr+is%3Aclosed) as possible!

**Comment by Thomaash** [comment]
There are actually 2 tests in TypeScript (that's why the tsconfig.json exists). I wan't to rewrite it into TypeScript (DataSet and DataView already are) but I also want to be sure to not break anything (or break as few things as possible). However there are very few tests to help me with this, so my plan right now is to increase the test coverage first.

I originally started with visjs-network (it seemed more active to me) but that didn't go that well. It just lies on my HDD and it's probably not worth publishing. I just jumped into it, made some big breaking changes and then realized they're not only incompatible but also nonsensical (quite a lot of wasted effort). I don't want to do this mistake again.

**Comment by mojoaxel** [comment]
>  I don't want to do this mistake again.

:+1: We all lern all the time! I would recommending starting small and than moving more and more to TS. As I understand it JS is compatible with TS so the first step could be to rename the first file to `.ts` and start adding type information!?

At some point https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vis could become obsolete.

**Comment by glennverschooren** [comment]
Hi, 

Is it possible to use the `vis-network` module inside a typescript project today?
If not what do you prefer?:

- use the old 'vis' library with the '@types/vis' types?
- use the new one and type it with any?

`
import * as VisNetwork from 'vis-network';

// Typescript does not recognize the `Network` function
const network = new VisNetwork.Network(container, data, options)

`

**Comment by HWouters** [comment]
@glennverschooren this was possible with 5.0.0,  but seems to be broken with 5.1.1

**Comment by mojoaxel** [comment]
> @glennverschooren this was possible with 5.0.0, but seems to be broken with 5.1.0

@glennverschooren That is sad to hear! Can you please create a bug report, with a view more details. Thx!

**Comment by mojoaxel** [comment]
> Is it possible to use the vis-network module inside a typescript project today?

@Thomaash Can you please have a look and answer this questions. Thx!

**Comment by Thomaash** [comment]
This is planned in 4 stages:
- [x] Add root TypeScript files (export types that don't exists).
- [ ] Add types from DefinitelyTyped.
- [ ] Add dummy types (export any to silence TS) where we don't have them.
- [ ] Rewrite into TS (there is a PR for Gephi parser already).

We should maybe release 5.1.1 completely without types because what is there is unusable :shit:.

**Comment by mojoaxel** [comment]
> Add types from DefinitelyTyped.

Just for Info: We have our own fork of our "DefinitelyTyped": [vis-types](https://github.com/visjs/vis-types).

**Comment by mojoaxel** [comment]
> We should maybe release 5.1.1 completely without types because what is there is unusable hankey.

Well than lets release a 5.1.2 fast!!

**Comment by ydg2018** [comment]
(not sure if i should create a new issue or ask in here as it's indirectly the same subject)
Is vis-network 5.1.0 not working in typescript projects?
I tried installing vis-network but it didn't recognize the Network, Edge Data or Node objects from the old vis library. 
Also tried to use `import * as VisNetwork from 'vis-network'; ` but that still only recognized the DataSet object.

I was looking at the vis-network/dist folder and noticed index.d.ts was pointing at some other directories like the network directory which does not exist in the dist folder.

So for now keep using the old vis library which is marked as EOL or am i doing something wrong with the new library?

**Comment by Thomaash** [comment]
@ydg2018 I'm going to look into this today and either make it work or release type free 5.1.1. The types are indeed broken. 5.0 doesn't have types at all so you can pin this version in your project.

**Comment by ydg2018** [comment]
@Thomaash thanks for the quick reply, i'll have a look at 5.0

**Comment by ydg2018** [comment]
I noticed the 5.1.1 has been merged, i just have 1 question.
When i define a DataSet<Edge> it keeps using the DataSet class from the vis-data library but that is a different class than the 1 defined in vis-network. 
I can change 
`import { Network, DataSet, Node, Data, Edge } from 'vis-network';`
to
`import { Network, DataSet, Node, Data, Edge } from 'vis-network/dist/types/vis-types';`
but that feels a bit hacky and not sure if that is a good practice to do.

So am I just importing the wrong way or is there still a small bug in the 5.1.1 release?

**Comment by Thomaash** [comment]
I think I forgot to update the DataSet in vis-types. I'll look into it when
I get home. Await 5.1.2.

**Comment by Thomaash** [comment]
Update for those who are interested: await 5.2.1, 5.2.0 doesn't solve this issue. We have to set vis-types repo up and publish it first.

**Comment by ydg2018** [comment]
> I think I forgot to update the DataSet in vis-types. I'll look into it when I get home. Await 5.1.2.
> […](#)

I've finally updated my typescript which gave me the possibility to update to 5.2.4 (without getting the weird errors in util.d.ts), but i still have the problem of the DataSet that is being used when importing as below:
`import { DataSet } from 'vis-network';`

With the above import it will use the DataSet version from vis-data and not the one that exists in vis-network. Which gives errors as the Data object expects the DataSet version from vis-network.

So how can i force it to use the DataSet version from vis-network?
