### ISSUE TITLE
Adding many nodes and edges takes forever

### ISSUE THREAD

**Issue by UnicornDeluxe** [visjs/vis-network#131]
Hey,
vis-network does an awesome job displaying networks. Even with a large number of nodes/edges (>500) everything simply works. 
HOWEVER, if one tries to add such a large number of nodes later on, by calling the _add_ function on the corresponding _DataSet_ object it simply won't do.
Check out this fiddle to see what i mean: http://jsfiddle.net/qhxj7n9w/
Adding 50 nodes & edges to an existing network does work, however adding 500 will not.
However, having 500 nodes & edges at the beginning is no problem.
Would be nice if adding nodes & edges could be more efficient.

**Comment by Thomaash** [comment]
Your MWE adds node with duplicate ids. That's why it doesn't add anything.

**Comment by Thomaash** [comment]
Also why are you adding them one by one? Just pass the array to add them in bulk, that's way faster.

**Comment by Thomaash** [comment]
See http://jsfiddle.net/thomaash/hjz8x72m/. It's very slow but it works.

**Comment by Thomaash** [comment]
Much faster: http://jsfiddle.net/thomaash/hjz8x72m/2/.

**Comment by UnicornDeluxe** [comment]
> Your MWE adds node with duplicate ids. That's why it doesn't add anything.

Yes I just noticed, updated it.
> Also why are you adding them one by one? Just pass the array to add them in bulk, that's way faster.

Am I stupid, or was that just not described anywhere?

Thanks :D

**Comment by Thomaash** [comment]
The first DataSet example starts with:
```javascript
// create a DataSet
var options = {};
var data = new vis.DataSet(options);

// add items
// note that the data items can contain different properties and data formats
data.add([
  {id: 1, text: 'item 1', date: new Date(2013, 6, 20), group: 1, first: true},
  {id: 2, text: 'item 2', date: '2013-06-23', group: 2},
  {id: 3, text: 'item 3', date: '2013-06-25', group: 2},
  {id: 4, text: 'item 4'}
]);
```

So there's no problem in the docs.
