### ISSUE TITLE
Nodes overlap

### ISSUE THREAD

**Issue by cburghardt** [visjs/vis-network#133]
I am trying to find a way to ensure that the nodes of my heavily connected z-wave network overview don't overlap and it is therefore easier to read.
I create the network like this:
```
        var options = {
            edges: {
                arrows: {
                    to: {
                        enabled: true,
                        scaleFactor: 0.5
                    }
                }
            },
            physics: { 
                enabled: false
            }
        };
        var network = new vis.Network(container, data, options);  
        network.stabilize(100);
```
container is sized to 100% width and height.
I have attached an example data structure.
[data.json.zip](https://github.com/visjs/vis-network/files/3631260/data.json.zip)

Any ideas?

**Comment by Thomaash** [comment]
Hi @cburghardt,

have you tried playing with gravitationalConstant, springLength and other physics options? You can experiment on https://visjs.github.io/vis-network/examples/network/physics/physicsConfiguration.html.

**Comment by Thomaash** [comment]
You can use `network.stabilize()` to run physics just once.

**Comment by cburghardt** [comment]
So I would add the physics options to the configuration, keep "enabled" as false and then run the stabilize()?

**Comment by Thomaash** [comment]
Exactly.

**Comment by Thomaash** [comment]
Since communication ceased I assume there's no issue anymore. Feel free to reopen this if that's not the case.
