### ISSUE TITLE
Type Script error creating networks

### ISSUE THREAD

**Issue by lmcadory** [visjs/vis-network#134]
Creating edges is throwing a typescript error.

If I have something like this:
``` javascript
let edgesArray = [
 { from: 1, to: 3 },
 { from: 1, to: 2 },
 { from: 2, to: 4 },
 { from: 3, to: 5 },
 ]
```

Then do: 
```javascript
let data = {
  nodes: new vis.DataSet(nodesArray),
  edges: new vis.DataSet(edgesArray)
}
```

I get the following error:
```
No overload matches this call.
  Overload 1 of 2, '(options?: DataSetInitialOptions<"id">): DataSet<Partial<Record<"id", string | number>>, "id">', gave the following error.
    Type '{ from: number; to: number; } []' has no properties in common with type 'DataSetInitialOptions<"id">'.
  Overload 2 of 2, '(data: Partial<Record<"id", string | number>>[], options?: DataSetInitialOptions<"id">): DataSet<Partial<Record<"id", string | number>>, "id">', gave the following error.
    Argument of type '{ from: number; to: number; } []' is not assignable to parameter of type 
```

The only way I seem to get around this is if I create my edge array using a loop. 
If I repurpose your exampleUtil.js getScaleFreeNetwork function and change the return statement to use vis.DataSet(arrays) everything works fine. 

I've also created a StackOverflow question for this error but it hasn't picked up traction
https://stackoverflow.com/questions/58015656/problem-setting-edges-in-vis-network-with-typescript

Is this a bug with the types or am I just doing something wrong? I'm going against the examples and I'm using vis-network version 5.2.4

**Comment by Thomaash** [comment]
There's no issue with Vis Network or Vis Data Set. I'll answer this on StackOverflow.
