### ISSUE TITLE
Node.title types doesn't match the documentation

### ISSUE THREAD

**Issue by Nexucis** [visjs/vis-network#1343]
Hello,

In the [documentation](https://visjs.github.io/vis-network/docs/network/nodes.html#), it says the field `title` supports `String` or `Element`, but then in types, it says it only supports `String`:

https://github.com/visjs/vis-network/blob/db6562ed03d48c94cbb9441e5ded1d991073af91/types/network/Network.d.ts#L966

Is it the doc that is not up to date ? Or Is there an issue in the types ?

In case it's indeed not possible to inject HTML element in the title, do you have something to replace it ?

**Comment by th3cr0w** [comment]
I guess this is your answer: https://github.com/visjs/vis-network/commit/57c0047ffa8a33ba9820faf00b8218d9b543944e

**Comment by Nexucis** [comment]
ok that means the docs is ok but the typescript Type is wrong then.
Thanks for the input @th3cr0w :).
