### ISSUE TITLE
Network stops loading if I move away from the page

### ISSUE THREAD

**Issue by aditya-manit** [visjs/vis-network#1351]
I have created a network but it would only load and stabilize only if I stay on the page, if lets say its 50% stabilized and I switch my tab it would kind of get paused there and will only stabilize when I will return to the page.

I want it to be loading even when I switch to some other tab. How to do that?

**Comment by Thomaash** [comment]
Hi @aditya-manit,

web browsers significantly throttle web pages in the background (for general performance, better battery life and so on) as people usually don't want background pages to do anything. There is nothing that a web page can do about that, well apart from hacks like playing audio to keep the tab alive but Vis Network is not gonna do anything like that for rather obvious reasons.
