### ISSUE TITLE
Is there a way to prevent border to appear when highlighted?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [visjs/vis-network#137]
Each example shows square with a border. While you can disable border in CSS 

![image](https://user-images.githubusercontent.com/15063294/65378233-ede65f80-dcb5-11e9-9531-c6390b378eb2.png)

```html
  <style type="text/css">
    #mynetwork {
      width: 600px;
      height: 400px;
      /*border: 1px solid lightgray;*/
    }
  </style>
```

It still shows up when you start interacting with a diagram. Is there a way to disable it completely? Sorry for noob question.

**Comment by Thomaash** [comment]
This is an accessibility feature of web browsers. AFAIK you can't disable it. The only way I know of is to add negative margin to the canvas so that the border is outside of the window or hidden bellow nearby opaque elements.

**Comment by mojoaxel** [comment]
This should work:
```css
#mynetwork:focus {
  outline: none;
}
```

**Comment by Thomaash** [comment]
It doesn't.

**Comment by mojoaxel** [comment]
This works:
```css
.vis-network:focus {
    outline: none;
}
```

**Comment by Thomaash** [comment]
> This works:
> 
> ```css
> .vis-network:focus {
>     outline: none;
> }
> ```

This indeed does work: https://jsfiddle.net/thomaash/Lkjshge7/.

**Comment by PrzemyslawKlys** [comment]
Thank you, guys! Appreciate the effort!
