### ISSUE TITLE
Title not rendering <pre>-tag correctly

### ISSUE THREAD

**Issue by ljacobsson** [visjs/vis-network#1376]
I maintain [cfn-diagram](https://github.com/mhlabs/cfn-diagram) which uses vis-network to render a diagram visualisation of an [AWS CloudFormation](https://aws.amazon.com/cloudformation/) template.

When hovering the icons I want to render the YAML or JSON of the template fragment as a tmultiline title formatted with the correct linebreaks and intendation. I've wrapped it in <pre>...</pre> to achieve this, but at some point lately it's stopped working. See [this issue](https://github.com/mhlabs/cfn-diagram/issues/30)

I pull in https://visjs.github.io/vis-network/standalone/umd/vis-network.min.js into a static html file, so I'm not sure what version caused this.

Can you please advise me how to make this work?

**Comment by Thomaash** [comment]
Hi @ljacobsson,

this is by design, it has been removed due to covert XSS issues (hence the major version change). If you want to pass custom elements, you have to pass, well, custom elements:
```javascript
// Just a simple wrapper to make the transition easier.
function preTitle(text) {
  const container = document.createElement("pre");
  container.innerText = text; // You may also use innerHTML if your source is trusted.
  return container;
}

// Create nodes as usual.
const nodes = new vis.DataSet([
  { id: 1, label: "Node 1", title: preTitle("test\n    test\n\n\ntest") },
  { id: 2, label: "Node 2", title: preTitle("test\n    test\n\n\ntest") },
  { id: 3, label: "Node 3", title: preTitle("test\n    test\n\n\ntest") },
  { id: 4, label: "Node 4", title: preTitle("test\n    test\n\n\ntest") },
  { id: 5, label: "Node 5", title: preTitle("test\n    test\n\n\ntest") },
]);
```
