### ISSUE TITLE
How to expand/collapse nodes with mouse click

### ISSUE THREAD

**Issue by kelumKP** [visjs/vis-network#14]
Like D3 Js is there any option available to Expand/Collapse Nodes?

**Comment by mojoaxel** [comment]
Maybe Clustering is what you are looking for?
- https://visjs.github.io/vis-network/examples/network/other/clusteringByZoom.html
- https://visjs.github.io/vis-network/docs/network/#methodClustering

**Comment by mojoaxel** [comment]
_By the way: This is not a support forum! We don't want to answer user-questions here. We are currently working on a documentation to make it more clear where this kind of questions could be better answered. For now please use [stackoverflow and the "vis.js" tag](https://stackoverflow.com/search?q=vis.js)_
