### ISSUE TITLE
Clearing labels and titles for edges

### ISSUE THREAD

**Issue by jan-johansson-mr** [visjs/vis-network#1450]
Hello @Thomaash,

I had an [issue](https://github.com/visjs/vis-network/issues/739) last year about clearing label and titles, with edges in vis-network graph. It was added to `DataSet` the possibility to delete properties via `updateOnly` operation, given the symbol `DELETE`. This works great, the property gets removed and all is well. However, it does not clear out the label, or the title in vis-network, they still remain and are displayed. I pointed to the [code section](https://github.com/visjs/vis-network/blob/379c43139e95ef3d67b9480c7fc25cd4664fe344/lib/network/modules/components/Edge.js#L205) where the magic happens. When after clearing (deleting) e.g. the label property, the said code does nothing with the label in the graph (since the label is now undefined) so it remains visible.

Experimenting with the code, and modify it with the following:

    // Only copy label if it's a legal value.
    if (isValidLabel(newOptions.label)) {
      parentOptions.label = newOptions.label;
    } else if (!isValidLabel(parentOptions.label)) {
      parentOptions.label = undefined;
    } else if (newOptions.label === undefined) {
      parentOptions.label = undefined;
    }

Do the magic. The label is cleared out. However now two clustering tests are failing:

 - 1 ) properly opens 1-level clusters
 - 2 ) properly opens clustered clusters

As the tests are relying on the text in the label for the test outcome, and the label is now undefined with the code above. It seems that the code is assuming that an undefined value for the property means no change. And that's okay, however, how are we to propagate that a label was cleared to the network when the label was deleted with `updateOnly` and symbol `DELETE` with `DataSet`, so that the label can be cleared with the network too?

Thanks

**Comment by mgkr** [comment]
I've been trying to figure out how to use the `DELETE` symbol with no luck.
Could you give a minimal jsfiddle (or similar) example.

Is this only possible in a node environment or similar?
Looks as if one needs to `import` the symbol - which isn't really doable in inline script on a html page (unless I'm wrong)

**Comment by mgkr** [comment]
@jan-johansson-mr 
As to your problem - I can now say that it seems to be a general problem (not just related to your labels).
My specific use-case is that I hide and then unhide a specific edge - and then later I want to hide/unhide all edges (via network options).
But that specific edge is now "stuck" on being shown - as in the network the "hidden" property has not been deleted.

So for now it seems the DELETE functionality is somewhat broken.
It correctly removes a property from the dataset object - but it remains in the network object.

The failure mode seems to be that subscribers to the "update" event (`this._trigger("update", .......)`) themself to not check `oldData` for the presence of the DELETE symbol.

And this then causes all sorts of side effects....

**Comment by jan-johansson-mr** [comment]
@mgkr 

Hi there, I agree with you, there is more to this than *just* the label. The solution with `DELETE` symbol solves one issue, namely removing a property from `DataSet`, but it does not solve the issue with removing it from the network. Thus, as stated in the issue, the `label` stay put in the network. Maybe there will be some resolution in the future.

Thank you for looking into this, it's very much appreciated!

**Comment by J0n4t4n** [comment]
Just stumbled upon the same problem, when I try to delete the label of an edge, it doesn't actually remove the text.
