### ISSUE TITLE
Use vis.js with map

### ISSUE THREAD

**Issue by albeliakov** [visjs/vis-network#1455]
I want to be able to draw a network on a map. Like here http://geojson.io/

Is it possible to do this with vis.js?

**Comment by mgkr** [comment]
Please make sure to **read the following list** before creating a new issue:

* **This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports** and feature requests! In case you face yourself with a usage question, then post your question e.g. on [stackoverflow](https://stackoverflow.com/questions/tagged/vis.js) tagged with "vis.js".

**Comment by mojoaxel** [comment]
@albeliakov Everything is possible, but I don't think vis-network is a good fit here!
