### ISSUE TITLE
React Bug: "Uncaught TypeError: Cannot read property 'solve' of undefined at t.value (vis-network.min.js:33)"

### ISSUE THREAD

**Issue by murilobellatini** [visjs/vis-network#1480]
I'm trying to use `vis.js` to render a Network Visualization using React.

However,  after installing all necessary packages the following errors are raised on the console

[Console Errors](https://i.stack.imgur.com/IF4YG.png)

My implementation goes as follows (based on this tutorial: https://www.jamestharpe.com/react-visjs/)

https://github.com/murilobellatini/try-vis-network

Can you guys help me get this code working?

Thanks!

**Comment by san4ezgig** [comment]
You can provide an empty object as third param in new Network()
