### ISSUE TITLE
Big nodes overlap

### ISSUE THREAD

**Issue by sharpaper** [visjs/vis-network#149]
vis-network, version from `/dist` in this repository, Firefox last version.

    network = new vis.Network(container, data, options);
    var options = {
        nodes: {
            size: 64
        }
    }

My graph has a lot of nodes that are **not** linked one another. When I set the size of a node too large (eg. size: 64), the nodes are not well distanced. Instead they are drawn one on top of the other.

**Comment by Thomaash** [comment]
Have you tried messing with spring length?

```javascript
const options = {
  nodes: {
    size: 64
  },
  physics: {
    barnesHut: {
      // Increased from default 95. You may need to increase this further.
      springLength: 300
    }
  }
};
const network = new vis.Network(container, data, options);
```

**Comment by sharpaper** [comment]
Thanks for the quick reply.
If anything, this is even worse. Setting this option (from 1 to 100000), nodes are even more clustered together, one over the other.
I don't know if this is of any help, but my graph has 100s of lone nodes (not linked to anything) of type `shape: "circularImage"`.

**Comment by sharpaper** [comment]
An image.

![nodes](https://user-images.githubusercontent.com/32109035/66032397-9d68d080-e505-11e9-885c-61ef6f966d84.png)

**Comment by Thomaash** [comment]
Spring length affects edges between nodes :smile:. You want to play with:
- `barnesHut.gravitationalConstant` default is -2000, the lower this is the more spaced out they'll be,
- `barnesHut.centralGravity` default is 0.3, the higher this is the more will they cluster around the center,
- `barnesHut.avoidOverlap` default is 0, higher values make node size matter (max is 1).

**Comment by sharpaper** [comment]
OK! This seems to work, although I have another problem with a node that when it's disturbed it never stops, it just keeps on going forever out of the screen.

Are all these options documented somewhere?

**Comment by Thomaash** [comment]
Sure it's all documented, everything is on https://visjs.github.io/vis-network/docs/network/physics.html. Try increasing central gravity to prevent nodes from flying of the screen.

**Comment by sharpaper** [comment]
Thank you.

**Comment by Thomaash** [comment]
You're welcome.
