### ISSUE TITLE
"text" nodes computation heavy

### ISSUE THREAD

**Issue by sharpaper** [visjs/vis-network#150]
Is there a particular reason why nodes of type "text" seem to hung up the browser significantly more than any other type? With 100s of text nodes, my PC is struggling to render the graph, much more than any other type such as "dot" or "circularImage".

**Comment by Thomaash** [comment]
Hi @sharpaper,

rendering text (convert vector font into raster image, do it many times for several letters that may form ligatures with their neighbors, affect each other's spacing etc.) is much more demanding than rendering raster image (just decompress and use) or a dot (very basic geometry). In other words text will always be slower. However this doesn't necessarily mean it couldn't be faster. If you provide an MWE showing what exactly is happening I'll have a deeper look into it.

**Comment by sharpaper** [comment]
I'm not doing anything fancy really, I'm only drawing a graph with a couple hundreds nodes and only a few edges (a couple 10s at most). All nodes are text nodes with a label, and all edges have a label too. All labels are between 10-40 characters long. The initial rendering is actually OK, the noticeable slow down happens when dragging the nodes around. It stutters and it looks like it's struggling to keep up with the mouse cursor. This does not happen with other node types. For my particular use case I can switch to "dot".
