### ISSUE TITLE
Fontawesome Icons inside the label?

### ISSUE THREAD

**Issue by nassif7** [visjs/vis-network#1510]
is there a way to render a Fontawesome Icon inside the node label? 

I have been trying t change the node style and shape when selected, but it seems the only way is to highlight the node. 
in case i want to show an icon inside the label it doesn't seem to be rendered

**Comment by mojoaxel** [comment]
Here are some examples:
https://visjs.github.io/vis-network/examples/network/nodeStyles/icons.html
