### ISSUE TITLE
e2e testing with protractor

### ISSUE THREAD

**Issue by Imkeshav** [visjs/vis-network#1523]
Hi team,
I am using vis-network library in one of my angular project. 

I need to write e2e testcases for testing the node selection, double click, right click, node properties, etc.

As I have only one element 'canvas' which deal with everything,
How can I write automated testcases for these function in protractor.

or, should I use any other tool to test it.

**Comment by mojoaxel** [comment]
You could try using something that compares screenshots. Have a look here:
https://github.com/mojoaxel/awesome-regression-testing

**Comment by JoyChopra1298** [comment]
How does comparing screenshot help in selecting and clicking on a particular node of the graph. Can you provide some example?
