### ISSUE TITLE
different edge & node types

### ISSUE THREAD

**Issue by gadepallivs** [visjs/vis-network#153]
In context of biological pathway representation we use different edge types & Node types ( reference image attached). This is from Ingenuity Pathway Analysis, some of these are already in vis-network library. However, certain features are missing eg. both bar and arrow, or color filled arrow or blank arrow. I hope these enhancements are generally applied for various graphs. However, I understand all feature requests may not be applicable to all users. In this scenario, is there any example tutorial on how I can write JS snippets that add these new functionality to my networks instead of implementing as part of the complete package ? 

<img width="531" alt="IPA_annalysis" src="https://user-images.githubusercontent.com/13947738/66313887-1a6ac000-e8e1-11e9-98b1-5952586cba06.png">

**Comment by Thomaash** [comment]
Hi @gadepallivs,

arrows are hardcoded at the moment. You can use the rendering events to render them yourself but that wouldn't be easy. However I do like the idea of having a way to supply custom arrow rendering functions. I'll look into this today (hopefully).

**Comment by Thomaash** [comment]
Is it still Monday? Am I not too late? I'm sure it's still Monday :smile:. Anyway as I said I looked into it and I'm no longer so fond of the idea of custom rendering functions for arrows. The code is not robust enough to support this. I ran into some unexpected and difficult to debug issues playing with it and I maintain this library. It would be quite tricky to use. However I implemented image arrow heads. So you can simply supply an SVG (PNG, JPG or whatever) image and it will be rendered for you. See #157 and http://jsfiddle.net/thomaash/67xaky4s/. It works pretty much the same way as image nodes and I think it will solve your issue. Correct me if I'm wrong.

**Comment by gadepallivs** [comment]
That works. But, it kind of makes your network look not so pleasant when you have too many of these :) . Thank you for alternative .

**Comment by Thomaash** [comment]
Why not so pleasant? How would rendering functions be more pleasant?

**Comment by gadepallivs** [comment]
Its great and quick alternative. That is't an issue at all. I was saying, I need to find good images, as for the example fiddle you had black background for arrows...that don't blend with the overall network. It isn't any problem. Solves my need. Just to make sure, you mentioned "image arrow heads", but I can create other connections from the example image I shared  ( IPA edges Types) or (IPA node Types) and render them wherever I would need them right ?

**Comment by Thomaash** [comment]
You can use any image as a node, with #157 you can also use any image as an arrow head and you can also have solid or dashed edges with a thickness and color of your choice. Therefore you can have all of them.

PS: Regarding the colors I made it just for demonstration, the image doesn't have to be black, it can have any color you need.

**Comment by mojoaxel** [comment]
@Thomaash Nice work mit #157 !

I remember creating a bunch of new arrow-heads back in the days. While the new image head might solve this issue I'm not sure if it is the best solution because of performance issues. Maybe we should also add some custom heads like I did in https://github.com/almende/vis/pull/2066 ?

**Comment by Thomaash** [comment]
I didn't really think about performance. We can add more arrow heads that's no big deal. Although if we want to allow people to add their own we should rework the way this works as it's pretty confusing right now (good design for reducing duplicity but it can easily break with improper use).
