### ISSUE TITLE
Set length of edges between 2 nodes when physics is off

### ISSUE THREAD

**Issue by PrzemyslawKlys** [visjs/vis-network#154]
I know I can set the length of edge when physics is on. Is there a way to do it when physics is off? It doesn't seem to do anything when I played with it (like the option is just not there).

**Comment by Thomaash** [comment]
You can use `network.stabilize()` to fire physics once without enabling it.
Other than that you‘d have to position the nodes manually.

**Comment by PrzemyslawKlys** [comment]
Thank you

**Comment by Thomaash** [comment]
You‘re welcome.
