### ISSUE TITLE
Node getting fixed when shift clicking & moving (Possible Bug?)

### ISSUE THREAD

**Issue by JonasGruenwald** [visjs/vis-network#1540]
I've noticed that when holding shift while clicking and dragging a node to move it, after the node has been moved it will become fixed (network data will reflect that x and y are fixed for the node).

I can reproduce this on [the basic example](https://visjs.github.io/vis-network/examples/network/basicUsage.html) on Firefox and Chrome on Mac OSX.

I can't find any documentation on this in the docs, is this a feature? And if yes, how can I turn it off?

**Comment by Syrusel** [comment]
I'm also facing this same issue.
