### ISSUE TITLE
After dragging a non-selected node you can no longer drag the selected node

### ISSUE THREAD

**Issue by tkolanko** [visjs/vis-network#1596]
This issue is reproducible on the basic usage example https://visjs.github.io/vis-network/examples/network/basicUsage.html

Steps:

1. Click on `Node 1` to select it
2. Drag `Node 2` 
3. Try to drag `Node 1`.
    - The entire canvas starts to pan

I tried to work around this by hooking into the `dragStart` and `dragEnd` events to see if I could programatically unselect/resleect the originally selected node, however, in both events `Node 2` is passed as the selected node even though `Node 1` has the selected node styling

**Comment by nickchomey** [comment]
Im also seeing this.
