### ISSUE TITLE
onContext returns different pointer position than click

### ISSUE THREAD

**Issue by UnicornDeluxe** [visjs/vis-network#162]
Hey,
this issue has already been opened on the old _almende-vis_ repository.
As described by @HaoyuanY in the mentioned [issue](https://github.com/almende/vis/issues/3254) it seems like the `oncontext` and the `click` events do not yield the same coordinates, which results in e.g. the list of nodes beeing empty even if one clicked right on a node.
Another strange behaviour I noticed, which can also be experience in the linked [jsfiddle ](https://jsfiddle.net/yuehaoyuan/p7e5qaob/)from Haoyuan, is that the `oncontext` event _does_ yield the correct coordinates if the node has been selected before. (click on it once)
I'm not quite sure if this relates somehow to #155 .

**Comment by rg2609** [comment]
I saw your issue in jsfiddle and I think it's working fine https://jsfiddle.net/yuehaoyuan/p7e5qaob/

**Comment by Thomaash** [comment]
The coordinates seem the same to me (in both the ancient JSFiddle and with up to date package).

The nodes are the selected nodes, not clicked. Since oncontext doesn't change the selection the event just contains whatever selection was there. It's documented in the docs.

**Comment by UnicornDeluxe** [comment]
Thank you very much @Thomaash for the quick answer. Apparently I missed this point in the documentation. Is there a possibility to get the (right-)clicked node even if it was not selected before?

**Comment by Thomaash** [comment]
It's in the docs: 

> You can use the method getNodeAt to select the node if you want.

**Comment by UnicornDeluxe** [comment]
Thank you for the answer, I definitely should look more into the docs.
So is it considered to be a feature to have the `oncontext` only apply on selected nodes, and not on the one clicked? Or are their plans to "fix" it?

**Comment by Thomaash** [comment]
We can't “fix” this. We'd have to “fix!: BREAKING CHANGE“ this. Many projects likely depend on the documented and long existing behavior. I'm against changing this behavior as achieving what you want is really easy even without any changes. It's not worth the the hassle and confusion for all the other people.

**Comment by UnicornDeluxe** [comment]
Makes sense, I agree!
