### ISSUE TITLE
Fontawesome 5 icon not getting render on network

### ISSUE THREAD

**Issue by rg2609** [visjs/vis-network#163]
I am using the network of Vis.js, previously for icon fontawesome 4.x was working fine, but after updating the fontawesome version to 5.x it's giving a problem.
I changed the icon code too, but still is not rendering the icon properly, I used the` icon: {face: "Font Awesome 5 Free", code: "\ufbb", color: "#6cf7a2", size: 30}` code for fontawesome and the output is following:
![image](https://user-images.githubusercontent.com/20682661/66828790-8ac3b200-ef6f-11e9-8be6-4900b301d505.png)

**Comment by Thomaash** [comment]
Hi @rg2609,

are you using the latest vis-network package and have you checked the Font Awesome 5 example on https://visjs.github.io/vis-network/examples/network/nodeStyles/icons.html?

**Comment by rg2609** [comment]
Hi @Thomaash ,
I am using thins [https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.css](https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.css ) and [https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.js](https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.js)

**Comment by Thomaash** [comment]
In other words you're not using the code from this repo, you're using https://github.com/almende/vis.

**Comment by rg2609** [comment]
Now I changed the link to [https://unpkg.com/vis-network@6.1.1/dist/vis-network.min.js](https://unpkg.com/vis-network@6.1.1/dist/vis-network.min.js) and 
[https://unpkg.com/vis-network@6.1.1/dist/vis-network.min.css](https://unpkg.com/vis-network@6.1.1/dist/vis-network.min.css), but still, the output is the same no icon render

**Comment by Thomaash** [comment]
Did you read the docs? Namely the part about FA5 and forcing bold font face?

**Comment by rg2609** [comment]
[https://visjs.github.io/vis-network/docs/network/index.html](https://visjs.github.io/vis-network/docs/network/index.html) then this one is old right

**Comment by Thomaash** [comment]
Seems up to date to me:
![Screenshot from 2019-10-15 14-46-49](https://user-images.githubusercontent.com/12966757/66832775-df106700-ef5a-11e9-885d-4b3620687a90.png)

**Comment by rg2609** [comment]
ya i saw this and updated too added weight:"bold" `icon:{face: "Font Awesome 5 Free", code: "", color: "#6cf7a2", weight: "bold", …}` , but sill, the output is same
![image](https://user-images.githubusercontent.com/20682661/66833552-a633ba80-ef79-11e9-81d5-21755d0a9b25.png)

**Comment by Thomaash** [comment]
Can you provide an MWE so that I could investigate this please?

**Comment by rg2609** [comment]
Here is MWE:
`[{"id":4353,"label":"a1-Display","font":{"face":"calibri"},"shape":"icon","icon":{"face":"Font Awesome 5 Free","code":"\ufbb","color":"#6cf7a2""weight":"bold","size":30}},{"id":4371,"label":"a2-Display","font":{"face":"calibri"},"shape":"icon","icon":{"face":"Font Awesome 5 Free","code":"","color":"#6cf7a2","weight":"bold","size":30}},{"id":4612,"label":"Dispay A3","font":{"face":"calibri"},"shape":"icon","icon":{"face":"Font Awesome 5 Free","code":"","color":"#6cf7a2","weight":"bold","size":30}}]`

**Comment by Thomaash** [comment]
This is not an MWE. This is just some JSON mess.

**Comment by rg2609** [comment]
```
// create an array with nodes
var nodes = new vis.DataSet([
      {
          "id":1,
          "label":"a1-Display",
      },
      {
          "id":2,
          "label":"a2-Display",
     },
     {
         "id":3,
         "label":"Dispay A3"
    }
]);

// create an array with edges
var edges = new vis.DataSet([]);

// create a network
var container = document.getElementById("mynetwork");
var data = {
  nodes: nodes,
  edges: edges
};
var options = {
  edges:{
                arrows: {
                  to: {enabled: true, scaleFactor:0.5, type:'arrow'},
                },
                arrowStrikethrough: false,
                color: '#848484',
                font: {
                    size: 8,
                    align: 'bottom'
                },
                width: .5,
                smooth: false,
            },
            interaction:{
                dragNodes:true
            },
            nodes: {
                physics:true,
                font: {
                  size: 10
                },
                shape:"icon",
                icon:{face:"Font Awesome 5 Free",code:"\\ufbb",color:"#6cf7a2",weight:"bold",size:30}
            },
            physics: {
                barnesHut: {
                    avoidOverlap: 0.01
                },
                maxVelocity: 500,
                minVelocity: 0.29,
                timestep: 0.1,
                stabilization: {
                    iterations: 300
                }
            },
            interaction: {
                hover:true,
                tooltipDelay: 200
            },
            layout: {
                improvedLayout:false
            }
};
var network = new vis.Network(container, data, options);

```

**Comment by Thomaash** [comment]
```javascript
face: "'Font Awesome 5 Free'", // Notice the quotes, they're if the name contains spaces.
code: "\uf2bb", // Notice the single back slash, \u**** is a Unicode escape, \\ is literal backslash.
```

**Comment by rg2609** [comment]
Thank @Thomaash, 
It's working I missed that` face: "'Font Awesome 5 Free'",`. working [jsfiddle](http://jsfiddle.net/pL27auv0/2/)

**Comment by Thomaash** [comment]
You're welcome.
