### ISSUE TITLE
TypeScript: declarations for keycharm

### ISSUE THREAD

**Issue by MrManny** [visjs/vis-network#164]
Greetings,

I have been using vis.js through the vis package in a Vue web application which uses TypeScript exclusively. As that package was EOL, I finally got around to migrate to vis-network 6.1.1.

The transition itself was painless and easy except for one tiny little detail. During the build process, TypeScript complained about this:

```
ERROR in C:/path-to-my-project/node_modules/vis-network/dist/types/index.d.ts
22:27 Could not find a declaration file for module 'keycharm'. 'C:/path-to-my-project/node_modules/keycharm/keycharm.js' implicitly has an 'any' type.
  Try `npm install @types/keycharm` if it exists or add a new declaration (.d.ts) file containing `declare module 'keycharm';`
    20 | import * as Hammer from './module/hammer';
    21 | export { Hammer };
  > 22 | import * as keycharm from 'keycharm';
       |                           ^
    23 | export { keycharm };
    24 | //# sourceMappingURL=index.d.ts.map
```

For reference, here is my tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "resolveJsonModule": true,
    "types": [
      "webpack-env",
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

The DefinitelyTyped repository does not appear to contain @types/keycharm, but I could work around the issue by adding `"skipLibCheck": true` to my tsconfig.json. As such, this is not a critical issue for me. However, I can also be somewhat pedantic and would appreciate a solution to this minor issue. I can also try to take it up with the [package owner](https://github.com/AlexDM0/keycharm) if you'd prefer that.

**Comment by Thomaash** [comment]
Keycharm doesn't have type definitions. You can make this error go away by simply adding `declare module "keycharm";` to your type definitions.

It would indeed be better to solve this either in DefinitelyTyped or the Keycharm library itself.

**Comment by mojoaxel** [comment]
We should keep this here open until https://github.com/AlexDM0/keycharm/issues/6 is resolved!

**Comment by xrn** [comment]
https://github.com/AlexDM0/keycharm/issues/6 is solved - @mojoaxel issue can be solved?
