### ISSUE TITLE
Hierarchical layout to respect node size

### ISSUE THREAD

**Issue by flaushi** [visjs/vis-network#168]
I am working with a hierarchical layout.
My nodes carry labels of  varying length.
AFAIK, the standard physics solver `hierarchicalRepulsion` computes a repulsion only based on the node centre. It does not take the node size (with label) into account.

Would it be possible to implement such a solver? 

![Bildschirmfoto 2019-10-20 um 13 37 42](https://user-images.githubusercontent.com/15819451/67158986-47868c00-f33f-11e9-8c4a-eb7bba1b7f12.png)

For hierachical layouts, it should be even be possible to position all nodes **without physics simulation**: All one needs is a margin between neighboring nodes (i use `direction: "UD",				sortMethod: "directed"`).

![image](https://user-images.githubusercontent.com/15819451/67159034-ae0baa00-f33f-11e9-9d98-cf67cc8ddbae.png)

**Comment by Thomaash** [comment]
Hi @flaushi,

I implemented overlap avoiding for hierarchical layout (#171). Could you check if it works as you expect? It has the same avoidOverlap option as Barnes Hut and you can use https://thomaash.github.io/cdn/vis-network.090dcc5097b4a8f89678183d5680f6b9.js in JSFiddle or wherever you prefer.

**Comment by flaushi** [comment]
Hey @Thomaash , that looks great! Is there a way for me to include this via npm? I am using webpack, and including "custom" libs always is a pain for me...

**Comment by Thomaash** [comment]
There's no way to include this by npm (unless you want to pack it and ship or publish yourself) but it's not a big change. I already asked @mojoaxel for review and if no issues arise from the review it could be released soon.
