### ISSUE TITLE
When network is in addEdgeMode, dragView doesn't work

### ISSUE THREAD

**Issue by stevenlafl** [visjs/vis-network#174]
For my use case, I just wanted to use Network to create edges between nodes at the moment. I'll be controlling the viewport, so I don't need users to be able to drag the viewport.
```
interaction: {
          dragView: false,
}
```
does not result in the desired behavior when in addEdgeMode. This contradicts https://visjs.github.io/vis-network/docs/network/interaction.html

Linux, Chrome

**Comment by Thomaash** [comment]
Hi @stevenlafl,

could you provide an MWE, please? Because if I put `dragNodes: false` into https://visjs.github.io/vis-network/examples/network/other/manipulation.html it works as expected.

**Comment by Thomaash** [comment]
What comes to my mind is that the nodes can't be dragged but their positions are not fixed. That is if you have enabled physics the new edge will move the nodes it's connected to. To prevent this you have to use `nodes.fixed: true` or `physics: false`. This however doesn't contradict the docs so it's probably not your problem.

**Comment by stevenlafl** [comment]
It's dragView: false, sorry. Just edited, here is the MWE https://jsbin.com/bitacuvowo

**Comment by Thomaash** [comment]
That's indeed a bug. I can confirm that.

**Comment by Thomaash** [comment]
Could you try if https://thomaash.github.io/cdn/vis-network.5f753610cc88ac3ff0052747e9863e7f.js works properly in your project?

Thanks.

**Comment by stevenlafl** [comment]
It does indeed. Thank you!

**Comment by Thomaash** [comment]
I'm glad to hear that. You're welcome.

**Comment by jkumar88** [comment]
I have same issue
