### ISSUE TITLE
Setting cluster fixed option doesn't do anything in hierarchical layout

### ISSUE THREAD

**Issue by Tyler-Maclachlan** [visjs/vis-network#179]
I'm using the hierarchical layout, and on node dragStart I update the node fixed property to 

```
fixed: {
  x: false,
  y: false
}
```

While this works for non-clustered nodes it doesn't seem to work for clusters.

Here is a [codepen](https://codepen.io/tyler-maclachlan/pen/gOOWPMe?editors=0010) example

**Comment by Thomaash** [comment]
Hi @Tyler-Maclachlan,

I'm not exactly sure what you're trying to achieve. Could you provide more info, please?

**Comment by Tyler-Maclachlan** [comment]
Just to give you some more context, we're using the hierarchical layout for positioning because it is the most visually aesthetic option in our use case; however, we would like to allow for moving nodes around on both axes.We managed to make it work by unsetting `fixed` on dragStart which works for nodes but not for clustered nodes. Clustered nodes seem to ignore fixed: {x: false, y: false}. Does that make sense?

Enabling and Disabling the hierarchical layout has the issue I posted earlier #178

**Comment by Thomaash** [comment]
Yeah, I understand what you're doing. The problem is that hierarchical layout is not supposed to be used in this way.

**Comment by ChickenSaysBak** [comment]
Experiencing the exact same issue. I want the hierarchical layout on initialization, but after that, I want the nodes where they can be freely positioned by the user (I have physics off).

I've achieved this with the same approach of disabling `fixed` on `dragStart` but this doesn't work on clustered nodes.
