### ISSUE TITLE
Create docs for Korean

### ISSUE THREAD

**Issue by GuengdongKim** [visjs/vis-network#180]
We are Korean university students who are conducting education and research on networks and open source.

We've been looking for an open source drawing a network, and your vis.js is the most interesting of them all.

That's why I **want to create Korean docs** that Koreans can access more easily.
Is it okay if we make Korean docs and contribute to you?

Thank you.

**Comment by Thomaash** [comment]
Hi @GuengdongKim,

that would be awesome, thank you very much. We don't have anything in place for multilingual docs though. I'm open to suggestions how to handle this but if you're in only to translate and don't mind editing HTML simply copy `docs` to `docs-kr`, rewrite the files and open a new PR.

**Comment by mojoaxel** [comment]
@GuengdongKim I also want to encourage you to contribute! This is awesome! 

The only problem is that this project is actively maintained and also the documentation changes in time. So we would need future help from one of you guys to not only translate the docs but also maintain the translation it in the future. If you cannot provide this it maybe would be better to fork the project, do the translation there and we could link to it from within out docs!?

**Comment by GuengdongKim** [comment]
**To @mojoaxel .** 
Thanks you to accept our proposal about translating and contributing to your open source software. Through our team discussion, we decided to making a **new docs-kr ourselves** and continuously updating it.  Sooner or later, our docs-kr  will be uploaded our project repository. And we will **pull request** our uploading docs-kr file to your visjs/vis-network profile. After pull requests, give a advice on our docs-kr. 
Thanks you to  considering our suggestion and reading a comment.
