### ISSUE TITLE
None of the examples work on 6.2.0?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [visjs/vis-network#183]
All examples are basically empty now in Chromium Edge / IE. 

https://visjs.github.io/vis-network/examples/

![image](https://user-images.githubusercontent.com/15063294/67639026-4a5b2100-f8eb-11e9-9309-0288cf373729.png)

Only legacy version works.

**Comment by Thomaash** [comment]
Hi @PrzemyslawKlys,

I'm just working on this.

**Comment by PrzemyslawKlys** [comment]
Ah, ok. This new version should work on IE right? Because I can't get it to work. 

I've changed link to new UMD:

https://jsfiddle.net/t7sbg0pn/1/

```
        <link type="text/css" rel="stylesheet" href="https://unpkg.com/vis-network@latest/dist/vis-network.min.css" /><!-- CSS VIS Network Dynamic, browser based visualization libraries END -->
        <!-- JS VIS Network Dynamic, browser based visualization libraries START -->
        <script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script><!-- JS VIS Network Dynamic, browser based visualization libraries END -->
```

**Comment by Thomaash** [comment]
It seems the dependencies got messed up (probably when I was merging upstream/master into the PR branch) so they don't have polyfills included and therefore work only in the most modern environment (not yet 100% sure that's the whole problem).

**Comment by PrzemyslawKlys** [comment]
This still isn't fixed in 6.3.0, and IE doesn't work still. Is this still work in progress?

**Comment by PrzemyslawKlys** [comment]
Examples still not working:
- https://visjs.github.io/vis-network/examples/network/data/dotLanguage/dotPlayground.html - pressing Draw doesn't do anything
- https://visjs.github.io/vis-network/examples/network/data/dotLanguage/dotEdgeStyles.html - nothing has shown

Now that I checked, most still don't work (if not all). Miniatures do work thou...

**Comment by PrzemyslawKlys** [comment]
Does this solve issue with IE not working as well or different thing?

**Comment by Thomaash** [comment]
No IE is still not working. However there is an error coming from Vis Data now. It seems like it's not properly polyfilled. I'll probably have to migrate it to core js 3 as well.

**Comment by PrzemyslawKlys** [comment]
thanks ;)

**Comment by Thomaash** [comment]
The problem is actually not present in standalone build. It's only peer build that suffers from this issue (the problem is in Vis Data package not in Vis Network). The standalone build seems to work just fine.

**Comment by PrzemyslawKlys** [comment]
The version I use doesn't seem to work

[Example-Basic.zip](https://github.com/visjs/vis-network/files/3790169/Example-Basic.zip)

1. Unpack
2. Open this up in IE as file (not via webserver)

In chrome it looks like this:
![image](https://user-images.githubusercontent.com/15063294/67879497-6229e380-fb3d-11e9-9a09-f2dc67b38212.png)

In IE it gives empty space. I'm using single:         `<script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>`
