### ISSUE TITLE
Newest release breaks functionality with accessing data on edges.

### ISSUE THREAD

**Issue by PCJPablo** [visjs/vis-network#189]
Previously was accessing the vis.DataSet object like so `edges._data[id]` but it appears the the _data object has been changed from a normal key value pair object to a Map but the entries are not accessible by the id anymore or even the index of the entery.

**Comment by Thomaash** [comment]
Hi @PCJPablo,

the underscore at the start of the property name says: `WARNING: THIS IS NOT PART OF THE API. THIS MAY CHANGE AT ANY TIME. DON'T TOUCH THIS!!!!`. We indeed switched to map.

If you have some use case that can't be implemented with the public API feel free to open an issue on https://github.com/visjs/vis-data/issues/new, provide an example (preferably an MWE on JSFiddle) and I'll see what can be done about it.
