### ISSUE TITLE
Why scrollbar not working if network is too large ?

### ISSUE THREAD

**Issue by Tripathi-Alok** [visjs/vis-network#1979]
I am using visjs network to plot large networks, so if the network is large then the labels are not visible because the network is being rendered in small space. How can we apply scrollbar on the network ?

**Comment by mojoaxel** [comment]
@Tripathi-Alok You could make the canvas that renders the network bigger and put it into a container with `overflow: both`.
The canvas element itself does not support scroll-bars.
