### ISSUE TITLE
postinstall script

### ISSUE THREAD

**Issue by mgobishop** [visjs/vis-network#2]
When I npm install vis-timeline I get the following error:

npm ERR! Failed at the vis-data@6.1.0 postinstall script

Any help or advice appreciated :-)

**Comment by mojoaxel** [comment]
@mgobishop Thanks for opening this issue. We are happy that it could be resolved! Working on these issues takes a lot of time. Please consider [supporting](https://opencollective.com/visjs/contribute) further maintenance and development!
