### ISSUE TITLE
Self reference circle position option 

### ISSUE THREAD

**Issue by piratuks** [visjs/vis-network#200]
I would like to request features / properties related to the selfReference. Property to say that selfReference edge is at the top / bottom / right / left (meaning the edge circle position is centered based on node according to provided position). 

I am attaching images to represent my requested option:

So the following image is something i would expect from requested options. You can see that  self ref is at the center on top.

![Capture](https://user-images.githubusercontent.com/8760197/68011028-dde77580-fc8e-11e9-93dd-6973b4655261.PNG)

**Comment by Thomaash** [comment]
Hi @piratuks,

I think many people would appreciate these features but the problem is that those are three independent features that should be tracked and implemented separately. Could you split this into three issues, please?

Thanks.

**Comment by piratuks** [comment]
@Thomaash yea sure. I have forked and implemented these thing as quick work around for myself. The code is not the best and etc but feel free to check if needed...
