### ISSUE TITLE
Half circle of self reference option

### ISSUE THREAD

**Issue by piratuks** [visjs/vis-network#201]
I would like to request features / properties related to the selfReference. Property to say that selfReference edge should be half circle. I have network where i am representing some nodes as tables and i have other nodes as attributes of the table (meaning these are placed inside that table node). So in this case i have table node with transparent background. Now if such table has self reference half of the edge is fine because it is above node and other half is visible under the node which is a bit annoying.

I am attaching images to represent my requested option:

So the following image is something i would expect from requested options. You can see that the table is transparent because other edge is visible, however self ref is just a half of it.

![Capture](https://user-images.githubusercontent.com/8760197/68024179-02a11480-fcb2-11e9-9f24-7e0c30a70bbd.PNG)

**Comment by Thomaash** [comment]
Implemented with #368.
