### ISSUE TITLE
[BUG] Hierarchical layout bug with vis-network v9.1.7

### ISSUE THREAD

**Issue by ksrrock** [visjs/vis-network#2023]
I am using vis-network v9.1.7.
This is the options that I am using.
```
const options = {
    interaction: {
      zoomView: true,
      dragView: true,
    },
    layout: {
      improvedLayout: true,
      hierarchical: {
        enabled: true,
        levelSeparation: 200,
        nodeSpacing: 300,
        treeSpacing: 300,
        blockShifting: true,
        edgeMinimization: true,
        parentCentralization: true,
        direction: 'UD', // UD, DU, LR, RL
        sortMethod: 'hubsize', // hubsize, directed
        shakeTowards: 'leaves', // roots, leaves
      },
    },
  };
```

**When i change direction from UD to LR , the graph breaks with error :**
`Error in /turbo_modules/vis-network@9.1.7/peer/umd/vis-network.min.js (33:306522)
t is not a function`

The same can be reproduced with the following online editor:
https://stackblitz.com/edit/react-wp8ct3?file=package.json,src%2FGraph.js

Any idea when will this bug be resolved?
Thanks

**Comment by Thomaash** [comment]
Hi, thanks for reporting it. I think that this should be fixed by #2024. Feel free to reopen if I'm wrong.
