### ISSUE TITLE
Import data from DOT language

### ISSUE THREAD

**Issue by vklepper** [visjs/vis-network#214]
Hi, 

I found an error in the documentation : The function `convertDOTNetwork()` doesn't exist anymore. I found the function `parseDOTNetwork()` and guess it was the the correct way to import data from DOT string. 

Thanks you for the library, very usefull !

Valentin

**Comment by Thomaash** [comment]
This export never actually existed. It used to be a part of the network monster object (`vis.network.convertDOTNetwork`, very treeshaking unfriendly). Thanks for pointing this out.
