### ISSUE TITLE
navigationButtons not displayed

### ISSUE THREAD

**Issue by Tazeg** [visjs/vis-network#217]
Navigation buttons disappeared between releases 6.0.0 and latest. Here is how to reproduce : 

Create a package.json with **6.0.0** release : 

```json
{
  "name": "testvis",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "vis-network": "^6.0.0"
  }
}
```
type : `yarn install`

create this `index.html` file and open it in the browser : 

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Test</title>
    <link rel="stylesheet" type="text/css" href="node_modules/vis-network/dist/vis-network.min.css">
</head>
<body onload="draw();">

<div id="mynetwork"></div>

<script type="text/javascript">

var nodes = null;
var edges = null;
var network = null;

function destroy() {
    if (network !== null) {
    network.destroy();
    network = null;
    }
}

function draw() {
    destroy();

    // create an array with nodes
    var nodes = [
    {id: 1, label: 'Node 1'},
    {id: 2, label: 'Node 2'},
    {id: 3, label: 'Node 3'},
    {id: 4, label: 'Node 4'},
    {id: 5, label: 'Node 5'}
    ];

    // create an array with edges
    var edges = new vis.DataSet([
    {from: 1, to: 3},
    {from: 1, to: 2},
    {from: 2, to: 4},
    {from: 2, to: 5}
    ]);

    // create a network
    var container = document.getElementById('mynetwork');
    var data = {
    nodes: nodes,
    edges: edges
    };
    var options = {
    interaction: {
        navigationButtons: true,
        keyboard: true
    }
    };
    network = new vis.Network(container, data, options);
}
</script>

<script type="application/javascript" src="node_modules/vis-network/dist/vis-network.min.js"></script>

</body>
</html>
```
The navigation buttons are displayed.

Update to the latest release : 

```bash
yarn add vis-network@latest
```
(latest is: 6.3.1)

Refresh page in the browser : navigation buttons have gone.

**Comment by Thomaash** [comment]
Hi @Tazeg,

the default/dist build is deprecated now. Can't you switch to the standalone build instead?

The problem is that the CSS is supposed to have the images inlined which works in peer and standalone builds. However nobody has configured this for the legacy build.

PS: `node_modules/vis-network/standalone/umd/vis-network.min.js` and you no longer need the CSS nor the images, just this single file.

**Comment by Tazeg** [comment]
Thanks for your quick answer.

I use `vis-network` in Electron app. So as you said, it works fine with the following line and without including any CSS : 

```
const vis = require('../../node_modules/vis-network/standalone/umd/vis-network.min')
```
But it is not supposed to be the right way. I should require like this : 

```
const vis = require('vis-network')
```

**Comment by Thomaash** [comment]
Try
```javascript
const vis = require("vis-network/standalone/umd/vis-network");
```
or if you bundle and want tree shaking
```javascript
import vis from "vis-network/standalone/esm/vis-network";
```
or if you really want to use the legacy build (please don't, we'll remove it eventually anyway) you can wait for #219 which will fix the issue.

**Comment by Tazeg** [comment]
If I understand, legacy is deprecated code ? if yes i don't need it. I want to use the latest and futur releases. 
I'm sorry but what are umd, esm and three shaking ?
Should i always use `const vis = require("vis-network/standalone/umd/vis-network");` for latest and futur releases ?

**Comment by Thomaash** [comment]
The legacy bundle contains up to date code. It's just bundled in fundamentally flawed way. The recommended way of importing Vis Network is either https://visjs.github.io/vis-network/examples/network/basic_usage/standalone.html or https://visjs.github.io/vis-network/examples/network/basic_usage/peer.html.

UMD combines several legacy module systems in single file. These can be simply required in node or loaded by script tag in browsers. ESM is the modern standard compliant module system that can be imported in modern module script tags (not so well supported yet though it can be used already if you don't care about older browsers) or used in conjunction with Rollup, Webpack and other bundlers. With bundlers you gain the advantage of tree shaking which throws away unused code. This doesn't work so well yet but we're working on this. For example if you never import the Gephi parser in your code it can be tree shaken that is not included in the bundle saving you precious kB and loading/parsing time.
