### ISSUE TITLE
[TypeScript] Type of "node.font.vadjust" is string but should be number?

### ISSUE THREAD

**Issue by aml2610** [visjs/vis-network#227]
Hi guys!
First of all, thank you for supporting this awesome library!

I am using `"vis-network": "^5.2.3"` and testing on the latest Chrome, latest macOS, but for this one I think versions are a bit irrelevant. I can see the same code on the `master` branch.

You can pass a font-related option to a node called `vadjust`. In the type declaration from https://github.com/visjs/vis-network/blob/master/types/network/Network.d.ts line 987, `vadjust` is declared as a string but looking at the usages of `vadjust` (e.g https://github.com/visjs/vis-network/blob/master/lib/network/modules/NodesHandler.js line 58) I can see it is actually a number.
I can confirm that when passed as a string, the option is not applied to the node. When passed as a number, it does work, but the interface `FontOptions` cannot be used because of incompatibility of string and number.

If you can confirm this issue, I am happy to contribute with a fix!
What do you think?

Best
Andrei

**Comment by Thomaash** [comment]
Hi @aml2610,

`vadjust` is definitely supposed to be a number (it's actually converted to Number internally and a number is used if it's not specified). Even the docs get it confused as there is string as data type but number as default value.

If you could provide a fix that would be great. Thank you.
