### ISSUE TITLE
Hierarchical layout creates massive gaps when there are nodes in clusters

### ISSUE THREAD

**Issue by Tyler-Maclachlan** [visjs/vis-network#264]
Hi guys,

So I have a graph of around ~930 nodes

916 of those nodes are connected to one node and therefore are clustered into that node.

The problem is the layout still creates space for them and thus creates large gaps where those nodes would be if they weren't clustered.

This creates a scenario where I have a node that is clustered and I have to scroll down forever to find the 13 nodes that aren't clustered because there is still space given for the 916 nodes that are in the cluster.

Is there any way for the layout to not give space for the nodes in the cluster or for the layout to order the nodes that aren't in the cluster above the nodes that are in the cluster?

I am clustering all the nodes before I enable the hierarchical layout and all the nodes have predefined levels.

My layout config:
`hierarchical: {
    enabled: false,
    direction: 'RL',
    sortMethod: 'directed',
    nodeSpacing: 200,
    treeSpacing: 200,
    levelSeparation: 250
}`

The layout `enabled` gets changed after clustering is done.

![large_network_gap](https://user-images.githubusercontent.com/32850000/69528974-fd18b080-0f77-11ea-964a-3c4f8918ad87.png)

Attached screen shot of what I mean, the nodes at the top are where the cluster is and alll the way at the bottom is a lonely node that is on the same level as the nodes in the cluster but gets pushed way down because there is space allocated for the nodes that are in the cluster.

**Comment by Thomaash** [comment]
Hi @Tyler-Maclachlan,

you said you have predefined levels. Then this is the correct behavior. The library is not supposed to question your levels. It gives you full manual control (the code that assigns levels doesn't run at all in this case).

Is there any particular reason why you want to have predefined levels?

**Comment by Tyler-Maclachlan** [comment]
Hi @Thomaash,

This gap scenario happens even if the levels are not predefined. We use predefined levels because we calculate the level differently than what the `directed` and `hubsize` options do.

The problem is not with the levels, it's that the layout engine gives positions to all the nodes in the cluster and then can't use those positions for the nodes outside the cluster which makes the graph spread out very far when you have a lot of nodes on the same level, even if not all the nodes on that level are visible.

**Comment by Triet** [comment]
Not sure if this is related but there has been an issue where hierarchical layout "exploded" causing the massive gap. This was seen in earlier versions and should have been fixed. I used the earlier version and saw the same thing on large graphs.

https://github.com/almende/vis/issues/3357#issuecomment-322148978

**Comment by Tyler-Maclachlan** [comment]
Hi @Thomaash 

Is there a way to set the initial positions of the nodes for the hierarchical layout without it using only those positions and not calculating new ones based on those positions.

Currently if I set a default position for the nodes in the hierarchical layout it uses only those positions and does not try to lay them out?
