### ISSUE TITLE
Example refers to libraries which are missing on unpkg.com

### ISSUE THREAD

**Issue by earcanal** [visjs/vis-network#278]
When I tried to run the [Browser UMD example](https://visjs.github.io/vis-network/examples/network/basic_usage/peer.html) I got the following errors

```
Cannot find "/peer/umd/vis-util.min.js" in vis-util@2.0.1
Cannot find "/peer/umd/vis-data.min.js" in vis-data@6.2.4
```

which seem to relate to these lines:

https://github.com/visjs/vis-network/blob/647fb57b6ea1c7cc35d5b8d4d720621d54afc209/examples/network/basic_usage/peer.html#L100-L101

**Comment by Thomaash** [comment]
Thanks for pointing this out.
