### ISSUE TITLE
How to space between  nodes without using hierarchical ?

### ISSUE THREAD

**Issue by asmakhalfallah2018** [visjs/vis-network#290]
Hello , i have a large graph , so when i set the option hierarchical in options layout my graph becomes not visible enough , that's why i decided to not use hierarchical and let it like normal . I want just to put some space between nodes . Is there any way to set nodes space without getting through hierarchical property ?  
Here is my options :

                `         var options = {
                         width:  '100%',
                          height: '100%',
                         layout: {
                           randomSeed:1,
                        
                          },
                    edges: {
                        arrows: {
                            to: {
                                enabled: true
                            }
                        },
                        smooth: {
                            enabled: false,
                            type: 'continuous'
                        }
                    },
                  
                    physics: {
                        enabled:false ,
                    },
                  
                };`

**Comment by Thomaash** [comment]
Hi @asmakhalfallah2018,

you can fire physics manually to place the nodes by calling `network.stabilize()`. This way you can take advantage of all the things physics can do without enabling it:
```javascript
const options = {
  edges: {
    length: 400 // Longer edges between nodes.
  },
  physics: {
    // Even though it's disabled the options still apply to network.stabilize().
    enabled: false,
    solver: "repulsion",
    repulsion: {
      nodeDistance: 400 // Put more distance between the nodes.
    }
  }
};

// Create the network.
const network = new vis.Network(container, data, options);

// Run physics once to space out the nodes.
network.stabilize();
```

**Comment by asmakhalfallah2018** [comment]
thanks @Thomaash  . It works

**Comment by kyleyost** [comment]
this doesnt work
