### ISSUE TITLE
How hub is built  when clustering ?

### ISSUE THREAD

**Issue by asmakhalfallah2018** [visjs/vis-network#299]
Hello , i am using clustering with vis-network and i find it really matching with what i was searching . My question is about clustering by hub size : how do we specify the hub size ? i use it like mentionned :   

           `function clusterByHubsize() {
                        network.setData(data);
                     var clusterOptionsByData = {
                         processProperties: function (clusterOptions, childNodes) {
                             clusterOptions.label = "[" + childNodes.length + "]";
                             return clusterOptions;
                         },
                         clusterNodeProperties: { borderWidth: 3, shape: "box", font: { size: 30 } }
                     };
                     network.clusterByHubsize(undefined, clusterOptionsByData);
                   }`

So how could we say if it's a hub or not ?

**Comment by Thomaash** [comment]
Hi @asmakhalfallah2018,

I'm not exactly sure what your asking. If you want to cluster hubs of given size simply replace the `undefined` in `network.clusterByHubsize(undefined, clusterOptionsByData)` by a number but that's already described in the docs: https://visjs.github.io/vis-network/docs/network/#methodClustering.

**Comment by asmakhalfallah2018** [comment]
sorry @Thomaash  yup this is what i am asking . I didn't see it . Thnx alot man !
