### ISSUE TITLE
How to enhance visibilty of  large graph  Vis.js ?

### ISSUE THREAD

**Issue by asmakhalfallah2018** [visjs/vis-network#302]
i am using vis.js to draw my graphs . For small graphs i put a layout with a direction and it's working fine . But for large graphs i am obliged to not use layout and here is the result . So how can i avoid overlapping nodes and edges ? i used this code in physics and it's not working :

      ` var options = {
        interaction: { hover: true },
        layout: {    improvedLayout:false  },

        edges: {
            arrows: {
                to: {
                    enabled: true ,
                    type: 'dynamic'

                }
            },
          
        },
      
        physics: {
            enabled: false,
            solver: "repulsion",
            repulsion: {
                nodeDistance: 400 // Put more distance between the nodes.
              }`

![image](https://user-images.githubusercontent.com/30045602/70636676-3e76b480-1c36-11ea-8308-b9c66d030c4e.png)

**Comment by Thomaash** [comment]
Hi @asmakhalfallah2018,

sadly you just have to play with the options to find something that will work for you.

You can try forceAtlas2Based. I had some quite good result with this one in the past although it needed some tweaking to get it just right.

Untested guess:
```json
{
  "solver": "forceAtlas2Based",
  "forceAtlast2Based": {
    "gravitationalConstant": -200,
    "springLength": 400,
    "springConstant": 0.36,
    "avoidOverlap": 1
  }
}
```

PS: It's really difficult to just look at a screenshot and give advice without being able to test if it actually works.

**Comment by asmakhalfallah2018** [comment]
> Hi @asmakhalfallah2018,
> 
> sadly you just have to play with the options to find something that will work for you.
> 
> You can try forceAtlas2Based. I had some quite good result with this one in the past although it needed some tweaking to get it just right.
> 
> Untested guess:
> 
> ```json
> {
>   "solver": "forceAtlas2Based",
>   "forceAtlast2Based": {
>     "gravitationalConstant": -200,
>     "springLength": 400,
>     "springConstant": 0.36,
>     "avoidOverlap": 1
>   }
> }
> ```
> 
> PS: It's really difficult to just look at a screenshot and give advice without being able to test if it actually works.

Thnxx @Thomaash  . No problem since we can drag nodes it's not a big problem for us

**Comment by asmakhalfallah2018** [comment]
Thnxx @Thomaash . No problem since we can drag nodes it's not a big problem for us
