### ISSUE TITLE
In react componentDidMount, enabling manipulation has no effect.

### ISSUE THREAD

**Issue by greenking19** [visjs/vis-network#304]
As shown in the code, manipulation is turned on but I don't see operation options in the canvas

![code](https://user-images.githubusercontent.com/43332372/70784591-abb85000-1dc4-11ea-91ae-d9686b5d24dd.png)
![effectMap](https://user-images.githubusercontent.com/43332372/70784593-ac50e680-1dc4-11ea-9cb5-da37f9a5b93e.png)
![officialWebsiteExample](https://user-images.githubusercontent.com/43332372/70784595-ac50e680-1dc4-11ea-8f8a-88ef3021a363.png)

**Comment by greenking19** [comment]
No edit button。 Why is this？

**Comment by Thomaash** [comment]
Hi @greenking19,

how are you importing it? Do you use something like:
```html
<script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
```

**Comment by greenking19** [comment]
> 嗨@ greenking19，
> 
> 您如何导入？您是否使用类似：
> 
> ```
> < 脚本 类型 = “ text / javascript ”  src = “ https://unpkg.com/vis-network/standalone/umd/vis-network.min.js ” > </ 脚本 >
> ```
No, I installed vis-network with npm, imported vis-network in the jsx file and then used it. Similar to the following code
-----------code-----------
import vis from 'vis-network'
...
var network = new vis.Network(container, data, options);
-----------end------------

**Comment by greenking19** [comment]
Thank you for your reply!  @Thomaash 
I don't know if it's a React problem or the framework problem I'm using. Have developers encountered similar problems?

**Comment by Thomaash** [comment]
Try importing it like:
```javascript
import * as vis from "vis-network/standalone";
```

If that doesn't help the other thing that comes to my mind is whether React is reactive. I've never used React but with Vue, which is reactive, there were some problems in the past. The problem was that Vue was observing DataSets and they failed to work properly. It didn't make sense to observe them anyway so the solution was to simply prevent Vue from observing them. Maybe something similar could be happening with React.

**Comment by greenking19** [comment]
Great! @Thomaash 
It can be used after being introduced in this way.
React is also reactive, and the problem has been solved.
--------- code ----------
import * as vis from "vis-network / standalone";
--------- end ------------
thank you for your help!。

**Comment by greenking19** [comment]
I have a doubt, is it possible to get an instance of node based on the id of the node and modify it? Is there such an interface?
I didn't find it when I looked at the documentation. It seems that only the click event gets the id, but no instance is available.

**Comment by greenking19** [comment]
I have a doubt, is it possible to get an instance of node based on the id of the node and modify it? Is there such an interface?
I didn't find it when I looked at the documentation. It seems that only the click event gets the id, but no instance is available.
Similar to：
-------code--------
let network = new vis.Network(container, data, options)
network.getNodeId(id).label = 'test change'
-------end----------

**Comment by Thomaash** [comment]
This is off topic but you want something like:
```javascript
const data = { nodes: new vis.DataSet(), edges: new vis.DataSet() };
new vis.Network(container, data, options);

data.nodes.updateOnly({ id: nodeId, label: "test change" }); // Only the label will be changed, other properties will stay as before.
```

More info on https://visjs.github.io/vis-data/data/dataset.html.
