### ISSUE TITLE
Edge de-select event report to many de-selected edges at specific case...

### ISSUE THREAD

**Issue by jan-johansson-mr** [visjs/vis-network#315]
Hi,

Thanks for a fantastic work with Vis. I've started to integrate it to my Blazor solution, and so far it's really good stuff.

There is one corner case I've noticed with Vis, and that is the reporting on de-selected edges. Mostly it runs as espected, but there is one case that gives the issue.

If you create a hierarchy with Vis, e.g a simple one with five nodes and four edges, where one node has more than one edge. In my case the middle node has three edges (root and two children nodes).

If I select the middle node, then I get good reporting of one node and three edges selected. If I select any edge not already selected, then I get the good report of three de-selected edges and one new selected edge. But if I select one of the edges already selected (by the middle node selection), then I get a report of three edges de-selected but not the selected edge as selected.

This means that my solution now thinks that no edge is selected, but Vis is displaying the clicked edge as selected.

Another issue is with update and delete operations. The same, if I select the middle node, the node and the three edges are selected (this is fine). If I delete the node, then the node and edges are deleted (this is fine too), but there is no report of the edges (or the node) being de-selected. Since the edges and the node are now gone, it would be logical if the same items also were reported as de-selected. This is a minor issue, since I do get report of the items being removed (so I can de-select them myself accordingly).

The select issue (above) is somewhat worse, since it derails my solution (not synchronized) with Vis depending on how I select the edges in the graph (selecting nodes however works fine with edges and nodes reported correctly reported).

Thanks

**Comment by Thomaash** [comment]
Hi @jan-johansson-mr,

these are two problems, could you split it into two issues, please?

Anyway regarding the first one I can't reproduce it. Could you provide an MWE, please? Because when I fiddled with it real quick it all seemed fine. It is not actually supposed to trigger select event because the edge was never deselected in the first place though it should not say that all were deselected.

Deleting indeed doesn't trigger deselection events. I can confirm that and I think it should trigger them.

**Comment by jan-johansson-mr** [comment]
Hi,

I've looked into the issue some more, with the following observation. You're right that the selection is correctly reported, but in somewhat unexpected way. Here's why...

When hooking up to the event `deselectEdge` we get the deselected edges. However, the event has a duality nature, because it also reports on newly selected edges (e.g. [deselectEdge](https://visjs.github.io/vis-network/docs/network/#Events) with the prevoius selected edges in the `previousSelection` and the newly selected edges in the `edges` array).

The `deselectEdge` event is only fired if some edge is selected prior to the event. Otherwise no report is given. To have that report we need to hook the `selectEdge` event.

When it get's wierd is how these events flow with the selection of edges in the graph. A `selectEdge` is almost always in pair with `deselectEdge`, except in two cases.

The first is when there is no edge selected, then we only get `selectEdge`. But the second case is as described above (e.g. select the middle node - three edges fires up as selected, then select one edge of these three edges and now we get the `deselectEdge` as expected, but no `selectEdge`).

The takeaway is that it is possible to compute the deselected edges in the `deselectEdge` event, by subtracting the newly selected edges from the previous selected edges given in the `previousSelection`.

Doing that fixes the issue firstly reported.

I did a repo, to observe the flow of events in the graph. If you want I can upload it to my github place for you to check it out.

Thanks for a quick reply!

**Comment by Thomaash** [comment]
I'm not 100 % sure about what your doing but did you try the `select` event? It seems to me that it would fit your needs better since it fires on any change to the selection. This way you could sync app and Vis selections with just this one listener.

The deselect events quite oddly report new state and previous state but this is how it is and how it has always been. Changing it would break countless projects that depend on this behavior.

**Comment by jan-johansson-mr** [comment]
It'll work good hooking on the `select` event instead, since it'll simply report exactly what is selected throughout (I just tested it). It'll also simplify all :-)
