### ISSUE TITLE
Popup Context menu on right click of the node or edge

### ISSUE THREAD

**Issue by abhinpai** [visjs/vis-network#336]
Thank you team for an amazing lib.

I have one feature that is been proposed for my project requirement. That is popping a Custom context menu on right click of the node or edges. 

Is this feature is already available or if it is new implementation then how can i contribute for this. what is the plan ?

**Comment by Thomaash** [comment]
Hi @abhinpai,

key question: How would this work on touchscreen?

**Comment by abhinpai** [comment]
Honestly, i haven't thought about it. But yes i can think of long press on the node to popup the custom context menu and where as in the laptop or the desktop the the same can be achieve with the help of right click on node. What is your opinion on it ?

**Comment by Thomaash** [comment]
Yeah, that sounds reasonable.

**Comment by abhinpai** [comment]
@Thomaash i have implemented these feature in my react (Typescript) application and AntDesign Lib, there are some glitches in it. In this i have introduced few features like, On right click to show context menu on edge and the node. And Bulk selection on drag, but the the UI hangs for a sec. Can you just find what am doing wrong ?

I know this is not the right forum to discuss on this but the thread is already on this topic so thought of asking here 

[https://github.com/abhinpai/react-vis-graph](url)

**Comment by Thomaash** [comment]
Sorry, I can't help you with that. I have never used React so I have no idea.

**Comment by abhinpai** [comment]
@Thomaash  No problem 😄
