### ISSUE TITLE
Scale issue

### ISSUE THREAD

**Issue by piratuks** [visjs/vis-network#340]
I have spotted something interesting. I have empty network (no nodes and no edges). My options has physics : {enabled : false}. Now this for some reason under fit() method for variables this.canvas.frame.canvas.clientWidth and this.canvas.frame.canvas.clientHeight returns 0 which ends up with 0/0 and so scale becomes Nan which invokes error. I am not sure why height and width are returned as 0 because i have actually set height and width to specific numbers. This only happens under vis_network = new vis.Network(container, data, options); So i am forced to use work around which is this: i set physics : { enabled: true} and after network is created then i toggle it off.

**Comment by Thomaash** [comment]
Hi @piratuks,

I can't reproduce it. Could you provide an MWE, please?

**Comment by piratuks** [comment]
@Thomaash So i tracked a bit the issue. My configuration is as follows:
1. Using angularjs
2. Using semantic ui.

Now i attached html which represents the issue.
So for this particular case the issue is that semantic-ui has tabs. Initially first tab is active and second is inactive which means it has display:none. So because of that i think placeholder for vis has no heigh / width.

Obviously i could do check in my project for tab activation and only then initiate network.
[interactionEvents.txt](https://github.com/visjs/vis-network/files/4044632/interactionEvents.txt)

**Comment by Thomaash** [comment]
Your MWE tries to load some `semantic/*` files I don't have and then crashes with:
```
TypeError: $(...).tab is not a function
```

I found a bug that caused the scale to be requested to be NaN but this was never set. The fit simply ended with an error and everything else worked correctly afterwards. Also setting physics to true didn't affect this at all not mentioning to function as a workaround.

There's likely something else in your setup causing these issues. An actually working (that's what the W stands for by the way) MWE would help a lot.

**Comment by piratuks** [comment]
@Thomaash sorry my bad forget to include semantic. The following should indicate what i was talking about.
[example.zip](https://github.com/visjs/vis-network/files/4045534/example.zip)

**Comment by Thomaash** [comment]
I found another problem regarding values like infinity and NaN being propagated through the state rendering the network unusable. #345 together with #344 fixes your MWE.

PS: In the MWE the height of the containing element is zero. Even if everything works correctly it will fill zero height container meaning it will have zero height. But if the container is stretched everything works with the forementioned fixes.

**Comment by piratuks** [comment]
@Thomaash thanks.
