### ISSUE TITLE
About border dashes

### ISSUE THREAD

**Issue by jan-johansson-mr** [visjs/vis-network#346]
Hi there,

I'm experiencing an issue with dashed borders in vis. When I update a node in a graph, to put a border color (e.g. red) and to emphesize in case of user having problem with colors with also setting the border to dashed pattern. Then the node border turns red, which is expected, but all nodes in the graph gets dashed borders and this is not expected.

If I create the graph from scratch with the same node data (only the said node with dashed border), then all nodes get the correct border line, and only the given node gets red and dashed border, and this is fine.

Both nodes and edges are collected in the Vis.DataSet, so the update of nodes is via the DataSet,
e.g.
```
var nodes = new vis.DataSet([
  {id: 1, label: 'Node 1'},
  {id: 2, label: 'Node 2'},
  {id: 3, label: 'Node 3'},
  {id: 4, label: 'Node 4'},
  {id: 5, label: 'Node 5'}
]);
// create an array with edges
var edges = new vis.DataSet([
  {from: 1, to: 3},
  {from: 1, to: 2},
  {from: 2, to: 4},
  {from: 2, to: 5},
  {from: 3, to: 3}
]);
// create a network
var container = document.getElementById('mynetwork');
var data = {
  nodes: nodes,
  edges: edges
};
var options = {};
var network = new vis.Network(container, data, options);
```
And then updating one of the nodes in the `nodes` collection.

I have no idea of why this is happening...

Here is the link to the description of the options for the [nodes](https://visjs.github.io/vis-network/docs/network/nodes.html).

Thanks

**Comment by Thomaash** [comment]
Hi @jan-johansson-mr,

I can't replicate this. It seems to work correctly. Could you provide an MWE, please?

PS: <https://jsfiddle.net/thomaash/ugnrq4b5/>.

**Comment by jan-johansson-mr** [comment]
I'll look into it a bit later, thanks!

Den lör 11 jan. 2020 12:22Tomáš Vyčítal <notifications@github.com> skrev:
