### ISSUE TITLE
why this  cannot support a small data like even 60 nodes and 500 edges

### ISSUE THREAD

**Issue by loveJasmine** [visjs/vis-network#370]

**Comment by Thomaash** [comment]
Hi @loveJasmine,

there are a few reasons why you may run into performance issues but 60 nodes and 500 edges should run a an old cell phone. If you provide an MWE I'll have a look at it.

PS: The title made way more sense with the "shit" included.

**Comment by loveJasmine** [comment]
var nodes = new vis.DataSet([{'group': 'OG', 'id': 1, 'label': '太平洋电子刘翔团队'}, {'group': 'TT', 'id': 2, 'label': '硬科技'}, {'group': 'OG', 'id': 3, 'label': '清溢光电'}, {'group': 'PO', 'id': 4, 'label': '浙江大学学士'}, {'group': 'PO', 'id': 5, 'label': '中科院硕士'}, {'group': 'TT', 'id': 6, 'label': '实业工作经验'}, {'group': 'TT', 'id': 7, 'label': '证券研究经验'}, {'group': 'AC', 'id': 8, 'label': '任职于'}, {'group': 'OG', 'id': 9, 'label': '联发科'}, {'group': 'OG', 'id': 10, 'label': '第一创业证券'}, {'group': 'OG', 'id': 11, 'label': '国信证券'}, {'group': 'AC', 'id': 12, 'label': '参与过'}, {'group': 'TM', 'id': 13, 'label': '北斗卫星'}, {'group': 'TT', 'id': 14, 'label': '规划与设计'}, {'group': 'TM', 'id': 15, 'label': '数字电视主芯片'}, {'group': 'TM', 'id': 16, 'label': '手机基带芯片'}, {'group': 'AC', 'id': 17, 'label': '研发'}, {'group': 'TT', 'id': 18, 'label': '主持设计'}, {'group': 'TM', 'id': 19, 'label': 'DisplayPort芯片'}, {'group': 'TT', 'id': 20, 'label': '年出货量'}, {'group': 'AC', 'id': 21, 'label': '位居'}, {'group': 'OG', 'id': 22, 'label': '龙头'}, {'group': 'BR', 'id': 23, 'label': '新财富第3名'}, {'group': 'BR', 'id': 24, 'label': '新财富第5名'}, {'group': 'PO', 'id': 25, 'label': '太平洋证券研究院副院长'}, {'group': 'AC', 'id': 26, 'label': '兼'}, {'group': 'PO', 'id': 27, 'label': '电子行业首席分析师'}, {'group': 'AC', 'id': 28, 'label': '曾就职于'}, {'group': 'OG', 'id': 29, 'label': '长江证券'}, {'group': 'AC', 'id': 30, 'label': '加入'}, {'group': 'OG', 'id': 31, 'label': '太平洋证券电子团队'}]);
            
              // create an array with edges
              var edges = new vis.DataSet([{'from': 1, 'label': '1', 'to': 1}, {'from': 1, 'label': '1', 'to': 2}, {'from': 1, 'label': '1', 'to': 3}, {'from': 2, 'label': '1', 'to': 2}, {'from': 2, 'label': '1', 'to': 3}, {'from': 3, 'label': '1', 'to': 3}, {'from': 4, 'label': '1', 'to': 4}, {'from': 4, 'label': '1', 'to': 5}, {'from': 4, 'label': '1', 'to': 6}, {'from': 4, 'label': '1', 'to': 7}, {'from': 5, 'label': '1', 'to': 5}, {'from': 5, 'label': '1', 'to': 6}, {'from': 5, 'label': '1', 'to': 7}, {'from': 6, 'label': '1', 'to': 6}, {'from': 6, 'label': '1', 'to': 7}, {'from': 7, 'label': '1', 'to': 7}, {'from': 8, 'label': '1', 'to': 8}, {'from': 8, 'label': '1', 'to': 9}, {'from': 8, 'label': '1', 'to': 10}, {'from': 8, 'label': '1', 'to': 11}, {'from': 8, 'label': '1', 'to': 12}, {'from': 8, 'label': '1', 'to': 13}, {'from': 8, 'label': '1', 'to': 14}, {'from': 8, 'label': '1', 'to': 15}, {'from': 8, 'label': '1', 'to': 16}, {'from': 8, 'label': '1', 'to': 17}, {'from': 8, 'label': '1', 'to': 18}, {'from': 8, 'label': '1', 'to': 19}, {'from': 8, 'label': '1', 'to': 20}, {'from': 8, 'label': '1', 'to': 21}, {'from': 8, 'label': '1', 'to': 22}, {'from': 8, 'label': '1', 'to': 23}, {'from': 8, 'label': '1', 'to': 24}, {'from': 9, 'label': '1', 'to': 9}, {'from': 9, 'label': '1', 'to': 10}, {'from': 9, 'label': '1', 'to': 11}, {'from': 9, 'label': '1', 'to': 12}, {'from': 9, 'label': '1', 'to': 13}, {'from': 9, 'label': '1', 'to': 14}, {'from': 9, 'label': '1', 'to': 15}, {'from': 9, 'label': '1', 'to': 16}, {'from': 9, 'label': '1', 'to': 17}, {'from': 9, 'label': '1', 'to': 18}, {'from': 9, 'label': '1', 'to': 19}, {'from': 9, 'label': '1', 'to': 20}, {'from': 9, 'label': '1', 'to': 21}, {'from': 9, 'label': '1', 'to': 22}, {'from': 9, 'label': '1', 'to': 23}, {'from': 9, 'label': '1', 'to': 24}, {'from': 10, 'label': '1', 'to': 10}, {'from': 10, 'label': '1', 'to': 11}, {'from': 10, 'label': '1', 'to': 12}, {'from': 10, 'label': '1', 'to': 13}, {'from': 10, 'label': '1', 'to': 14}, {'from': 10, 'label': '1', 'to': 15}, {'from': 10, 'label': '1', 'to': 16}, {'from': 10, 'label': '1', 'to': 17}, {'from': 10, 'label': '1', 'to': 18}, {'from': 10, 'label': '1', 'to': 19}, {'from': 10, 'label': '1', 'to': 20}, {'from': 10, 'label': '1', 'to': 21}, {'from': 10, 'label': '1', 'to': 22}, {'from': 10, 'label': '1', 'to': 23}, {'from': 10, 'label': '1', 'to': 24}, {'from': 11, 'label': '1', 'to': 11}, {'from': 11, 'label': '1', 'to': 12}, {'from': 11, 'label': '1', 'to': 13}, {'from': 11, 'label': '1', 'to': 14}, {'from': 11, 'label': '1', 'to': 15}, {'from': 11, 'label': '1', 'to': 16}, {'from': 11, 'label': '1', 'to': 17}, {'from': 11, 'label': '1', 'to': 18}, {'from': 11, 'label': '1', 'to': 19}, {'from': 11, 'label': '1', 'to': 20}, {'from': 11, 'label': '1', 'to': 21}, {'from': 11, 'label': '1', 'to': 22}, {'from': 11, 'label': '1', 'to': 23}, {'from': 11, 'label': '1', 'to': 24}, {'from': 12, 'label': '1', 'to': 12}, {'from': 12, 'label': '1', 'to': 13}, {'from': 12, 'label': '1', 'to': 14}, {'from': 12, 'label': '1', 'to': 15}, {'from': 12, 'label': '1', 'to': 16}, {'from': 12, 'label': '1', 'to': 17}, {'from': 12, 'label': '1', 'to': 18}, {'from': 12, 'label': '1', 'to': 19}, {'from': 12, 'label': '1', 'to': 20}, {'from': 12, 'label': '1', 'to': 21}, {'from': 12, 'label': '1', 'to': 22}, {'from': 12, 'label': '1', 'to': 23}, {'from': 12, 'label': '1', 'to': 24}, {'from': 13, 'label': '1', 'to': 13}, {'from': 13, 'label': '1', 'to': 14}, {'from': 13, 'label': '1', 'to': 15}, {'from': 13, 'label': '1', 'to': 16}, {'from': 13, 'label': '1', 'to': 17}, {'from': 13, 'label': '1', 'to': 18}, {'from': 13, 'label': '1', 'to': 19}, {'from': 13, 'label': '1', 'to': 20}, {'from': 13, 'label': '1', 'to': 21}, {'from': 13, 'label': '1', 'to': 22}, {'from': 13, 'label': '1', 'to': 23}, {'from': 13, 'label': '1', 'to': 24}, {'from': 14, 'label': '1', 'to': 14}, {'from': 14, 'label': '1', 'to': 15}, {'from': 14, 'label': '1', 'to': 16}, {'from': 14, 'label': '1', 'to': 17}, {'from': 14, 'label': '1', 'to': 18}, {'from': 14, 'label': '1', 'to': 19}, {'from': 14, 'label': '1', 'to': 20}, {'from': 14, 'label': '1', 'to': 21}, {'from': 14, 'label': '1', 'to': 22}, {'from': 14, 'label': '1', 'to': 23}, {'from': 14, 'label': '1', 'to': 24}, {'from': 15, 'label': '1', 'to': 15}, {'from': 15, 'label': '1', 'to': 16}, {'from': 15, 'label': '1', 'to': 17}, {'from': 15, 'label': '1', 'to': 18}, {'from': 15, 'label': '1', 'to': 19}, {'from': 15, 'label': '1', 'to': 20}, {'from': 15, 'label': '1', 'to': 21}, {'from': 15, 'label': '1', 'to': 22}, {'from': 15, 'label': '1', 'to': 23}, {'from': 15, 'label': '1', 'to': 24}, {'from': 16, 'label': '1', 'to': 16}, {'from': 16, 'label': '1', 'to': 17}, {'from': 16, 'label': '1', 'to': 18}, {'from': 16, 'label': '1', 'to': 19}, {'from': 16, 'label': '1', 'to': 20}, {'from': 16, 'label': '1', 'to': 21}, {'from': 16, 'label': '1', 'to': 22}, {'from': 16, 'label': '1', 'to': 23}, {'from': 16, 'label': '1', 'to': 24}, {'from': 17, 'label': '1', 'to': 17}, {'from': 17, 'label': '1', 'to': 18}, {'from': 17, 'label': '1', 'to': 19}, {'from': 17, 'label': '1', 'to': 20}, {'from': 17, 'label': '1', 'to': 21}, {'from': 17, 'label': '1', 'to': 22}, {'from': 17, 'label': '1', 'to': 23}, {'from': 17, 'label': '1', 'to': 24}, {'from': 18, 'label': '1', 'to': 18}, {'from': 18, 'label': '1', 'to': 19}, {'from': 18, 'label': '1', 'to': 20}, {'from': 18, 'label': '1', 'to': 21}, {'from': 18, 'label': '1', 'to': 22}, {'from': 18, 'label': '1', 'to': 23}, {'from': 18, 'label': '1', 'to': 24}, {'from': 19, 'label': '1', 'to': 19}, {'from': 19, 'label': '1', 'to': 20}, {'from': 19, 'label': '1', 'to': 21}, {'from': 19, 'label': '1', 'to': 22}, {'from': 19, 'label': '1', 'to': 23}, {'from': 19, 'label': '1', 'to': 24}, {'from': 20, 'label': '1', 'to': 20}, {'from': 20, 'label': '1', 'to': 21}, {'from': 20, 'label': '1', 'to': 22}, {'from': 20, 'label': '1', 'to': 23}, {'from': 20, 'label': '1', 'to': 24}, {'from': 21, 'label': '1', 'to': 21}, {'from': 21, 'label': '1', 'to': 22}, {'from': 21, 'label': '1', 'to': 23}, {'from': 21, 'label': '1', 'to': 24}, {'from': 22, 'label': '1', 'to': 22}, {'from': 22, 'label': '1', 'to': 23}, {'from': 22, 'label': '1', 'to': 24}, {'from': 23, 'label': '1', 'to': 23}, {'from': 23, 'label': '1', 'to': 24}, {'from': 24, 'label': '1', 'to': 24}, {'from': 25, 'label': '1', 'to': 25}, {'from': 25, 'label': '1', 'to': 26}, {'from': 25, 'label': '1', 'to': 27}, {'from': 26, 'label': '1', 'to': 26}, {'from': 26, 'label': '1', 'to': 27}, {'from': 27, 'label': '1', 'to': 27}, {'from': 28, 'label': '1', 'to': 28}, {'from': 28, 'label': '1', 'to': 29}, {'from': 28, 'label': '1', 'to': 30}, {'from': 28, 'label': '1', 'to': 31}, {'from': 29, 'label': '1', 'to': 29}, {'from': 29, 'label': '1', 'to': 30}, {'from': 29, 'label': '1', 'to': 31}, {'from': 30, 'label': '1', 'to': 30}, {'from': 30, 'label': '1', 'to': 31}, {'from': 31, 'label': '1', 'to': 31}]);

**Comment by Thomaash** [comment]
Hi @loveJasmine,

the Forced Altlas 2 based solver often works better when the default Barnes Hut fails:
```javascript
var options = {
  physics: {
    solver: 'forceAtlas2Based'
  }
};
```

MWE: https://jsfiddle.net/thomaash/etpgysjo/

**Comment by loveJasmine** [comment]
it does better， but it cannot support more 10k nodes。
thanks

**Comment by Thomaash** [comment]
Yeah, 10k+ is a lot. This library would need a lot of work in order to work well with that. You also seem to have heavily interconnected graphs which doesn't work that well on it's own and just makes all the issues worse.
