### ISSUE TITLE
Overlay Menu Option on Node Possible?

### ISSUE THREAD

**Issue by dbourdeveloper** [visjs/vis-network#382]
Hello, I was wondering if its possible to get a Neo4J browser like effect using vis.js. Something like the image where you click a node and it opens up a menu overlay. Would this be feasible without modifying the source code? 
<img width="164" alt="Screen Shot 2020-01-24 at 6 04 03 PM" src="https://user-images.githubusercontent.com/10367546/73114934-1edcd800-3ed4-11ea-9fc8-affd116a5957.png">

**Comment by dbourdeveloper** [comment]
Might have found a solution.

**Comment by Jothinayagan** [comment]
I'm looking for the same solution. Can you just drop the solution here, that could help me?

**Comment by CarryM** [comment]
> Might have found a solution.

can you tell me the solution?
