### ISSUE TITLE
Edge label positioning 

### ISSUE THREAD

**Issue by tiagombsilva** [visjs/vis-network#390]
Hello,

If it is possible, i think this issue will help many people that uses vis, before this new community there was a issue created here (https://github.com/almende/vis/issues/2104) that wanted to add some new features to labels in edges and it would be nice if we can add here!

![imagem](https://user-images.githubusercontent.com/51969868/73209718-5d72cc80-4138-11ea-8761-aa872107c4cd.png)

Like this image demostrates.
Iam sorry for sounding a bit too vague, it's my first contributing :D

**Comment by Thomaash** [comment]
Hi @tiagombsilva,

this has already been mentioned in #129 so let's move over there.
