### ISSUE TITLE
render behind node

### ISSUE THREAD

**Issue by piratuks** [visjs/vis-network#397]
I found issue when i added to my project. Only for specific case -> shape must be box or text and heightConstraint between 175 - 431. Then the angleFrom and To are calculated wrongly.

Have i missed something @Thomaash ?

        var nodes = new vis.DataSet([
            {
                id: 2,
                label:
                    [
                        "An edge connected to the same node on both end renders a circle.",
                        "Both from and to arrows point to the same node.",
                        "The radius of the edge can be adjusted using selfReference.size.",
                        "The edge can be positioned using selfReference.angle.",
                        "The part of the edge behind the node can be hidden using selfReference.renderBehindTheNode."].join("\n"),
                 heightConstraint: { minimum: 400 },
                x: 100,
                y: 0,
                shape: "box",
                color: {
                    background: "transparent"
                }
            }, 
        ]);

        // create an array with edges
        var edges = new vis.DataSet([
            { from: 1, to: 1, label: "Moonage Daydream" },
            {
                from: 2, to: 2, label: "Testing", arrows: 'to, middle, from',
                selfReference: {
                    size: 30,
                    angle: Math.PI / 2,
                    renderBehindTheNode: false
                }
            },

        ]);
    
        // create a network
        var container = document.getElementById("mynetwork");
        var data = {
            nodes: nodes,
            edges: edges
        };
        var options = {};
        var network = new vis.Network(container, data, options);

**Comment by Thomaash** [comment]
Yeah. In `EdgeBase.getArrowData` they are both searching for an intersection through the whole circle just in opposite directions. I guess that with some configurations, like the one you just found, they'll both find the same intersection instead of both.

In case you want to fix it I suggest to try searching through different half of the circle for each arrow. Though I'm not sure if such solution would be bullet proof.
