### ISSUE TITLE
hierarchical directed layout: wrongly directed arrows

### ISSUE THREAD

**Issue by UnicornDeluxe** [visjs/vis-network#4]
_The fiddle below is using vis.js as vis-network seems to be not yet available on cdnjs, however this is not working on the current vis-network version either._

As you can see on [this jsfiddle](http://jsfiddle.net/Ln4t9mjr/) not strictly hierarchical networks do not very well with vis atm. It seems that the levels given to the diferent nodes by vis are not quite.. right.
The first network shows nodes without the level argument given, the second one below with level given. Without explicit level the result is just wrong: crossing edges and even wrong levels. (In up direction a child node should never be above its parent node ^^) 

The edge crossing seems to be [known](https://github.com/almende/vis/issues/3357) but it still would be nice if it gets fixed or at least if one could toggle if he want "optimazation but crossing" or "no crossing but no optimization" mentioned [here](https://github.com/almende/vis/issues/3357#issuecomment-322148978).
Concerning the wrong direction for some nodes I did not find any related issue.

Im not sure if it can help here, but it seems like for larger graphs without level given the order of edges does alter the resulting graph significantly. (I will update the issue with an example as soon as I got one or maybe better open another one, as it may be a totally different thing.) 

Without having looked into the code, I assume the graph engine isnt sorting the edges it is given properly in order to assign them their final level in the graph, thus nodes are placed on wrong levels resulting in wrongly directed arrows/edges.

**Comment by UnicornDeluxe** [comment]
[Here](http://jsfiddle.net/zjnktdvr/) is the above mentioned example where the order of the edges matters.
The top one of the 2 graphs has the edge array sorted differently each time one presses run which results in completly different trees each time.
It seems like this is due to the fact, that the way vis determines the max level of the tree is wrong.
The correct graph, the bot one, has 21 level. However vis comes up with a different number of levels each time going from 13 to 19.
There are basically two problems:
1. the order of the edges impacts the determination of the levels
2. the level determination is doing something wrong, which is why it never gets the correct number of levels.

Maybe [this publication about the Sugiyama-Algorithm](https://www.researchgate.net/profile/Nikola_Nikolov2/publication/303226437_Sugiyama_Algorithm/links/59354e6f45851553b6f39e2e/Sugiyama-Algorithm.pdf) can help solving the level determination problem.

**Comment by ohsorry** [comment]
Is there any progress on this issue? My application scenario also needs to manually set the level of the node to layout. It seems that I can't help much, I just finished reading the documentation.

**Comment by Thomaash** [comment]
Hi @UnicornDeluxe and @ohsorry,

I tried to fix the wrong layout part of this issue. It's really slow at the moment but seems to work correctly. Could you test it with your apps and give some feedback please? I'm not sure whether it's bullet proof.

- MWE 1: http://jsfiddle.net/m56qtkcu/
- MWE 2: http://jsfiddle.net/huwp23bz/
- URL for MWEs: https://raw.githack.com/Thomaash/vis-network/issues/4/dist/vis-network.js

**Comment by UnicornDeluxe** [comment]
Hi @Thomaash,

looks to me like there are no wrongly directed edges anymore, congrats!
And the randomness when altering the order of the edges is also gone.

The levels itself are a bit weird tho, I guess the problem is your determining the level based on the parent nodes, resulting in a lot of nodes beeing placed at level 0 which would fit better at for example level 6 (as their sole child is level 7).

I rendered the same graph in three different ways to make this a bit clearer: 

This one beeing without explicit level given to the nodes and without your fix. (although given in the right order):
![noLevelNoFix](https://user-images.githubusercontent.com/43786929/63149822-7dd52180-c005-11e9-816a-37feb5eb6816.png)
At level 10 to 9 one can see wrongly directed edges, which is due to the lack of 1 additional level in the graph. 

The next one is using your fix (without levels and with the same order of the nodes as the previous one ofc):
![fixedLevelling](https://user-images.githubusercontent.com/43786929/63150006-f0de9800-c005-11e9-8dba-824c96fe850f.png)
Here there are no wrongly directed arrows, however many nodes are placed at level 0 while they could be placed far below. Resulting in the graph beeing very broad.

The last one works with and without the use of your fix but requires the levels to be determined, leading to this:
![levelledNodes](https://user-images.githubusercontent.com/43786929/63150118-46b34000-c006-11e9-9bb7-b6d966f3af6c.png)
There are no wrongly directed edges either, however there are not more nodes than absolutly necessary on level 0 and so on. 

The way I avoid having nodes at level 0 that should not be there is by building the graph from the bottom to the top thus looking at they childs of the nodes instead of their parents. Which means in the worst case the number of levels in the graph is equal the number of nodes, thus I set the initial level of each node to the total amount of nodes. Then by using the edges I check for each node if their child node is on the same level as they are, if so the node level has to be reduced by one to get the node one level above its child. Repeat this for each node, number_of_nodes^2 times and you get the right levels. (As the lowest level may not be zero just substract it from all the other levels to get levels from 0 to x) 
The performance of this is horrible but I'm sure it can be improved a lot by some smart people out there.

I hope this helps make your fix even better.

Thanks for the work your putting into this, keep it up!

**Comment by Thomaash** [comment]
@UnicornDeluxe Okay, so I've improved the performance and incorporated your advice. Could you check it out once more whether everything is alright please?

URL for MWEs: https://raw.githack.com/Thomaash/vis-network/issues/4/dist/vis-network.js

**Comment by ohsorry** [comment]
@Thomaash 
No layout problems for me now! I used vis-network to visualize dynamic neural networks, everything works very well. 👍

**Comment by UnicornDeluxe** [comment]
Hi @Thomaash it seems like it's not working anymore; the graph looks like https://user-images.githubusercontent.com/43786929/63149822-7dd52180-c005-11e9-816a-37feb5eb6816.png again.

Can you please upload the vis-network.js from "https://github.com/visjs/vis-network/issues/4#issuecomment-521779374" separately again so I can check?

**Comment by Thomaash** [comment]
@UnicornDeluxe glad to read it works. The crossing edges are indeed not part of the PR, it's only about the messed up levels. Edge crossing is, at least in my opinion, an unrelated issue that should have it's own issue opened.

**Comment by UnicornDeluxe** [comment]
@Thomaash you are right, I will open another issue for the crossing edges.
What about the random layouting? A new issue aswell or as part of the crossing edges one?

**Comment by Thomaash** [comment]
I would say 2 independent issues.

**Comment by UnicornDeluxe** [comment]
Hi,
sad but this isnt fixed with https://raw.githack.com/Thomaash/vis-network/issues/4/dist/vis-network.js. Take a look at this http://jsfiddle.net/3zd5jtcf/ fiddle. The top graph is the current status, with wrongly directed edges. The bottom one is the correctly leveled one, with not wrongly directed edges.
I assume this is because when determining the level of each node as described in https://github.com/visjs/vis-network/issues/4#issuecomment-521917070 the number of iterations used is noth enough to fully determine the correct level.

**Comment by Thomaash** [comment]
Hi @UnicornDeluxe,

it is fixed. I just messed up updating dist (again :disappointed:) after merging upstream changes. It should be fine now.
