### ISSUE TITLE
groups properties override individual

### ISSUE THREAD

**Issue by piratuks** [visjs/vis-network#408]
Not sure if it is as suppose to be. However it is weird that if you have a group properties and you set a node to that group and put property to different value then it is being overridden with group properties. Node borderWidth is 5 in the following example, however i would expect 1. 

        var nodes = new vis.DataSet([
            {
                id: 1,
                label:
                    [
                        "I'm an alligator,",
                        "I'm a mama-papa coming for you.",
                        "I'm the space invader,",
                        "I'll be a rock 'n' rollin' bitch for you."
                    ].join("\n"),
                x: 0,
                y: 0,
                color: {
                    background: "transparent"
                },
                group: "test",
                borderWidth: 1
            }
        ]);

        // create a network
        var container = document.getElementById("mynetwork");
        var data = {
            nodes: nodes,
            edges: []
        };
        var options = {
            groups: {
                test: {
                    borderWidth: 5
                }
            }
        };
        var network = new vis.Network(container, data, options);

**Comment by Owlman145** [comment]
I also lost multiple hours because of this the other day. Definitively not intuitive.

**Comment by Akrog** [comment]
I've encountered the same issue with `image` and `shape` options when I was representing pods in k8s and I wanted to represent all the pods and use one image for them all except the pods running a particular container, which I wanted to have a different image while still belonging to the pod group.

Apparently this also [used to be the case with the `color` option](https://github.com/almende/vis/issues/3713).
