### ISSUE TITLE
Barneshut physics theta option is reported by the validator

### ISSUE THREAD

**Issue by Owlman145** [visjs/vis-network#415]
The Barneshut solver options throw an error when theta option is put there, even though it accepts it (though only on initialization, thetaInversed in nodesSolver doesn't get updated on change).

Theta is an important option for improving performance, especially since Barneshut algorithm tends to perform worse than a naive force simulation for small (few thousand nodes) with little difference to post stabilization result, as shown here: https://jheer.github.io/barnes-hut/.

In practice, for visualization purpose, values higher than 0.5 do cause visual jitter, so what I do is set theta high during hidden stabilization (1.2) and lower it back to 0.5 after. In the case of our network, this resulted in ~6 times lower stabilization times for networks with >1000 nodes, which is critical as our we don't want our users to be waiting forever to visualize their network. If I could set these with the options instead of forcefully changing thetaInversed in the nodesSolver, it would probably be better. An adaptive theta could perhaps be interesting to look at.

**Comment by Thomaash** [comment]
Hi @Owlman145,

I tried changing the theta. It thrown no errors and reacted just fine. Could you provide an MWE, please?

Thanks.

**Comment by Owlman145** [comment]
For testing this issue, I'm on latest commit of master branch.
Chrome: Version 79.0.3945.130 (Official Build) (64-bit)
Added the following below line 46 of examples/network/physics/physicsConfiguration.html:
`          barnesHut: {
            theta: 1
          },`
Causes the following error:

Validator.js:218 Unknown option detected: "theta" in 
options = {
  physics: {
    barnesHut: {
      theta
    }
  }
}
Perhaps it was misplaced? Matching option found at: 
options = {
  edges: {
    font
  }
}
Network.js:163 Errors have been found in the supplied options object.

**Comment by Owlman145** [comment]
I believe theta needs to be added here to prevent this: https://github.com/visjs/vis-network/blob/master/lib/network/options.js#L409
Should also be added to docs for clarity, to reduce issues like #248
Strangely, these are not missing in the compiled version found here: https://visjs.github.io/vis-network/standalone/umd/vis-network.js
