### ISSUE TITLE
Importing DataSet module in javascript in latest release

### ISSUE THREAD

**Issue by albertki** [visjs/vis-network#42]
I installed the latest (5.1.0)  vis-network using npm, and I am using it in a react project. When I was using v.4.20.1, in my visjs component, I would do the following:

```js
componentDidMount() { 
	this.mounted = true;

	var DataSet = require('../../node_modules/vis/lib/DataSet');
	var Network = require('../../node_modules/vis/lib/network/Network');
	nodesDataset = new DataSet(this.state.graph.nodes);		
	edgesDataset = new DataSet(this.state.graph.edges);

	var data = {
		nodes: nodesDataset,
		edges: edgesDataset
	};
	network = new Network(this.refs.network, data, options);
}
```

However, in the new repo, there doesn't seem to be a DataSet.js that I could import. Is there another way I could go about using the latest vis.js to create a network in my react project? (I am relatively new to javascript)

Thank you

**Comment by mojoaxel** [comment]
@albertki Try this:

```js
componentDidMount() { 
	this.mounted = true;

	var { DataSet, Network } = require('vis-network');
	nodesDataset = new DataSet(this.state.graph.nodes);		
	edgesDataset = new DataSet(this.state.graph.edges);

	var data = {
		nodes: nodesDataset,
		edges: edgesDataset
	};
	network = new Network(this.refs.network, data, options);
}
```

**Comment by albertki** [comment]
@mojoaxel That did it. Thank you very much!

**Comment by mojoaxel** [comment]
@albertki Thanks for opening this issue. We are happy that it could be resolved! Working on these issues takes a lot of time. Please consider [supporting](https://opencollective.com/visjs/contribute) further maintenance and development!
