### ISSUE TITLE
nodes.max('id') returns null if IDs are not numeric

### ISSUE THREAD

**Issue by fpierrat** [visjs/vis-network#457]
Hi,

I tried to use nodes.max() with no result. Whatever my efforts, it still only returned null.
I finally found out that max() works like a charm on numeric indexes (see attachment
[test-max.zip](https://github.com/visjs/vis-network/files/4231941/test-max.zip) ).

I think there must be something wrong: in the doc page https://visjs.github.io/vis-network/docs/network/nodes.html one can read:
- " id | String | undefined | The id of the node. The id is mandatory for nodes and  they have to be unique. This should obviously be set per node, not  globally."

But on the other hand, nodes are constructed with a vis.DataSet. The doc I could find about the max() function is https://visjs.github.io/vis-data/data/dataset.html#Methods:
- "max(field) | Object \| null | Find the item with maximum value of specified field. Returns null if no item is found."
Nothing here says that max() is supposed to work only on numeric fields.

Now, the max function seems to work properly on ID only if ID is numeric, contrary to what is awaited for the nodes dataset.

So the problematic is:
- should indexes really be strings? Then there must be a bug in the max() function.
- should indexes be numerics? Then the doc for vis-network should be amended. (note: many examples -if not all- found on github and in the doc itself use integer-IDs).
- are there known side-effects for ignoring vis-network doc and using numerics for IDs in vis-network?

Thanks in advance for your interest

**Comment by Thomaash** [comment]
Hi @fpierrat,

max finds the highest numeric value. It's not meant to be used on ids although you can do that. You may have something like price or length which would be a number and max would work.

There's no one right definition of max value for strings. Just google collation. For this reason it's not implemented.

Regarding numeric ids they're perfectly valid. You can use them. If the docs state something else somewhere (where?) it's an error in the docs.

If you want to use your own logic (like Intlr.Collator for strings) you can do:
```typescript
const isTheSecondArgumentMax = /* Your logic goes here. */;
const maxValue = dataSet
  .stream()
  .reduce<Item | null>((maxSoFar, item): Item | null => {
    if (maxSoFar == null) {
      return item;
    } else if (isTheSecondArgumentMax(maxSoFar, item)) {
      return item;
    } else {
      return maxSoFar;
    }
  }, null);
```

PS: Just a silly question but what's the point of getting the max id? I'm probably missing something but this seems utterly useless to me.

**Comment by fpierrat** [comment]
Thanks for this clear answer.
> Regarding numeric ids they're perfectly valid. You can use them. If the docs state something else somewhere (where?) it's an error in the docs.

See first doc URL in my initial message. ID is described as "string" there (citated here above).
Perfect for me if int allowed with no side effect.

> Just a silly question but what's the point of getting the max id? I'm probably missing something but this seems utterly useless to me.

Max('id')+1 is useful for me, in my specific context (PHP+DB related), when adding new nodes.
Thanks again.

**Comment by Thomaash** [comment]
I totally agree with the proposed changes. Would you be interested in contributing the changes?

**Comment by fpierrat** [comment]
Never used Github from "the other side of the Force" ;-)
What shall I do?

**Comment by Thomaash** [comment]
To put it simply:
1. Fork the repo (the button is at top right).
1. Clone the fork as with any other repo.
1. Create a new branch for your changes.
1. Make the changes.
1. Commit them.
1. Push the commits back into your fork.
1. Create a new pull request from your fork's Pull Requests page (you'll likely get a yellow box at the top that will automatically create a PR between your last pushed branch and our master, saving you a few clicks).
1. Set it to compare your branch against our master branch.
1. Create the pull request.

PS: At the moment the docs are just simple HTML files without any processing being done.

**Comment by fpierrat** [comment]
Done for node.html in vis-network 's doc (https://github.com/visjs/vis-network/pull/466).
I'll wait and see if I didn't miss something in this first pull request (2 words in a doc file, wahou ;-) ) before making another one for vis-dataset...

**Comment by fpierrat** [comment]
Done for vis-data/DataSet.max() too (https://github.com/visjs/vis-data/pull/129).
I'll close the issue if my perms allow it.  Stage clear ;-)
