### ISSUE TITLE
setOption edge color options not updating edge properties 

### ISSUE THREAD

**Issue by gase12** [visjs/vis-network#49]
hi.
dynamic option setting with setOptions() not working with edge colors (color.color, color.opacity etc)
though the network.edgesHandler.options gets updated.
network.setOptions({edges:{color:{opacity:0.0}}}).
on init all the parameters are ok afaik.
g

**Comment by Thomaash** [comment]
What exactly is wrong? Could you provide a MWE?
Because to me it seems to be working just fine: https://jsfiddle.net/2qzu916x/ .

**Comment by gase12** [comment]
sure. i might do something wrong but here it is:
https://jsfiddle.net/ts3jv4n8/16/

**Comment by Thomaash** [comment]
@gase12 The problem is, that you use the legacy Vis 4.15.0. With vis-network 5.1.1 everything works just fine: https://jsfiddle.net/pjf2L640/ .

**Comment by gase12** [comment]
omg. sorry.

**Comment by Thomaash** [comment]
No problem, everybody makes mistakes.

**Comment by mojoaxel** [comment]
@gase12 Thanks for opening this issue. We are happy that it could be resolved! Working on these issues takes a lot of time. Please consider [supporting](https://opencollective.com/visjs/contribute) further maintenance and development!
