### ISSUE TITLE
Is there a way to fallback to icon instead of brokenImage?

### ISSUE THREAD

**Issue by ydg2018** [visjs/vis-network#501]
In our project we use webfont icons for the nodes, but some nodes can also use custom images and with images some can have the problem of not loading. For this problem there is the field brokenImage, but in our case we don't have images but webfont icons we would like to show incase the custom image does not load.
So is there a way to fall back to the icon instead of the brokenImage?

i tried to set both image and icon, but this did not work (i guess this is because they use different node shapes).

**Comment by Thomaash** [comment]
Yeah, sadly the broken image is a feature of the image shape. There's no way to switch from one shape to another unless, of course, you want to do it manually.

**Comment by ydg2018** [comment]
Thanks for the reponse, thought that would be the case.
