### ISSUE TITLE
Bug in solver() in HierarchicalRepulsionSolver.js:70

### ISSUE THREAD

**Issue by ssadams11** [visjs/vis-network#555]
OSX 10.14.5
Latest visjs from https://unpkg.com/vis-network/standalone/umd/vis-network.min.js
(7.4.0, I believe)
Bug in solver() in HierarchicalRepulsionSolver.js:70
distance is defined as const but change is attempted in the code.
![image](https://user-images.githubusercontent.com/5204570/77084051-cb1ed480-69d4-11ea-82a1-4e349387d7de.png)

**Comment by Thomaash** [comment]
Hi @ssadams11,

would you have the time to fix this and provide a PR?

**Comment by alexbiohacker** [comment]
+1. Same bug.

I had some nodes in non hierarchical view with 'x' and 'y' set only for some nodes. In some sets of nodes, adding bold tag around node name ('<b>' . $node_label . '</b>') resolved the problem. But in many others did not.

If I would generate hierarchical view, it would always draw map correctly. So 'hierarchicalRepulsion' just breaks in non-hierarchical views.

**Comment by alexbiohacker** [comment]
I can confirm that '"vis": "^4.21.0",' did not have this problem.
