### ISSUE TITLE
Can not render in IE 11.

### ISSUE THREAD

**Issue by at-hoangnguyen2** [visjs/vis-network#57]
Hey,
I had an issue when using Visjs on IE 11. UI was not rendered and the error was shown in the picture below

![Capture1](https://user-images.githubusercontent.com/26244995/62682033-54a10980-b9e5-11e9-976c-c5fe842e3e1d.JPG)

Browser: IE 11.
Version: 11.615.17763.0

**Comment by mojoaxel** [comment]
dublicate of https://github.com/visjs/vis-util/issues/37

**Comment by at-hoangnguyen2** [comment]
@mojoaxel I am using Visjs-network version 5.2.0! Please check it again!

**Comment by mojoaxel** [comment]
@at-hoangnguyen2 I can confirm this issue. It must be fixed in `vis-util`. Please wait for the next release.

**Comment by mojoaxel** [comment]
We need vis-util > 1.1.4 to be released. Than greenkeeper will pick up the change and release a new - hopefully fixed - version of vis-network.

**Comment by Thomaash** [comment]
Hi @at-hoangnguyen2,

5.2.4 is released with a fix. Could you check whether it helps or not please? I don't have access to IE 11 at the moment.

Thanks.

**Comment by omniflash** [comment]
Using version 5.2.4 with IE11 (11.950.17134.0), none of the network examples work...exception logged in ie console:
SCRIPT5007: Object.getPrototypeOf: 'this' is not an Object 
vis-network.js (7074,9)

**Comment by Thomaash** [comment]
Hi @omniflash,

I don't have access to IE 11 so this is just a wild guess but could you try if this fiddle solves your issue: https://jsfiddle.net/thomaash/wzokfg04/ ?

**Comment by mojoaxel** [comment]
_(We should set up a browser stack account...)_

**Comment by Thomaash** [comment]
We should…

**Comment by mojoaxel** [comment]
@Thomaash We could use the vis-bot account for browserstack and share it. I'll take care of it..

**Comment by omniflash** [comment]
Hi @Thomaash! Sorry, I only could check it now...unfortunately its not working still, but now there is a different error:

SCRIPT438: Object doesn't support property or method 'isFinite'
vis-network.644b7d3a4855ea0563eb6c87e5124fe9.js (36427,13)

**Comment by Thomaash** [comment]
Yes! We're getting somewhere. Try this next: https://jsfiddle.net/thomaash/wzokfg04/7/ .

**Comment by omniflash** [comment]
Yesss! :)) Its displaying.

**Comment by Thomaash** [comment]
Okay, so we need core js 3 to properly polyfill IE11. I'll have to make some changes to the way bundling is done in the entire visjs family. That may take a while.

**Comment by omniflash** [comment]
I know its the worst question, but how much time you think? Asking bc its needed for a deadline project for me ;) And thank you in advance, very swift reaction :) Other option for me is to try the last version which is still working in IE11 and handles" controlNodeDragEnd" event.  Are you maybe aware of any version that may be good for me in the meanwhile?

**Comment by Thomaash** [comment]
I'm not sure how long but it is a big change I want to discuss with others (as it among other things affects all of our projects.) It could be a few days or even more.

I can publish a pre release outside of the normal versioning (to not affect other people with possible errors, overlooked breaking changes…) that you could pin in your package.json, would that be helpful?

**Comment by omniflash** [comment]
i will check and get back to you, but few days i think is not an issue ;) thank you very much!!

**Comment by omniflash** [comment]
Ok, so I just checked your commit and quickly changed it in the compiled js. The graph now is visible, still getting the same error in console when changing arrows or direction via buttons, but they seem to work fine nevertheless. The events tho doesnt seem to fire...
`		 	network.on("dragEnd", function (params) {
		 		var controlEdge = params.controlEdge;
		                alert(JSON.stringify(controlEdge,null,2));
             		        console.log('dragEnd Event:', params);
			    });
		    network.on("controlNodeDragEnd", function (params) {
		            	var controlEdge = params.controlEdge;
		                alert(JSON.stringify(controlEdge,null,2));
         		        console.log('controlNodeDragEnd Event:', params);
		    });
`
This doesnt do anything, when connecting edges, neither of the alerts are shown and nothing is logged.

**Comment by Thomaash** [comment]
What commit are you talking about? If you mean #85 that doesn't have the fix (https://github.com/visjs/vis-util/pull/55) for vis-util and therefore won't work. If you're talking about https://github.com/visjs/vis-util/pull/55 that uses core-js 2 and therefore won't work either. You need to have both at the same time, checking only one out is not enough.

If you just want the dist fixed for IE11 you can download it here: https://ulozto.net/file/Ks1Vf8hvqXC5/vis-network-ie11-dist-zip (md5sum: 9d34fe1b9a22943d7d245209135c7f81).

**Comment by omniflash** [comment]
Oh ok, gotcha. The one you uploaded works perfectly, thank you very much! I can use this until the next release, which contains these fixes. Hats down for the fast support!! :)

**Comment by evilmomo** [comment]
> 
> 
> What commit are you talking about? If you mean #85 that doesn't have the fix ([visjs/vis-util#55](https://github.com/visjs/vis-util/pull/55)) for vis-util and therefore won't work. If you're talking about [visjs/vis-util#55](https://github.com/visjs/vis-util/pull/55) that uses core-js 2 and therefore won't work either. You need to have both at the same time, checking only one out is not enough.
> 
> If you just want the dist fixed for IE11 you can download it here: https://ulozto.net/file/Ks1Vf8hvqXC5/vis-network-ie11-dist-zip (md5sum: 9d34fe1b9a22943d7d245209135c7f81).

Quick question... Will the dist fixed files help with the timeline not displaying in IE 11 as well?

**Comment by Thomaash** [comment]
No. The dist files contain only Network. However Util which is used in Timeline is already fixed and works in IE11 (the other issues were in Network codebase) so it should be enough to update Util to 1.1.7+ in Timeline and rebuild.

PS: This assumes that there are no issues in Timeline itself.

**Comment by rochappy** [comment]
> No. The dist files contain only Network. However Util which is used in Timeline is already fixed and works in IE11 (the other issues were in Network codebase) so it should be enough to update Util to 1.1.7+ in Timeline and rebuild.
> 
> PS: This assumes that there are no issues in Timeline itself.

Should vis-network package.json also update the version of vis-util?

**Comment by rochappy** [comment]
In addition, the example [https://visjs.github.io/vis-network/examples/network/basicUsage.html](https://visjs.github.io/vis-network/examples/network/basicUsage.html) ie 11 cannot be displayed.

**Comment by Thomaash** [comment]
Hi @rochappy,

does it work for you if you use https://github.com/Thomaash/vis-network/blob/peer-build/standalone/umd/vis-network.js instead of the version you're using now?

**Comment by rochappy** [comment]
Yesss! It is displayed, So for the time being, use this scheme instead? when is it merged into the master?

**Comment by rochappy** [comment]
> Hi @rochappy,
> 
> does it work for you if you use https://github.com/Thomaash/vis-network/blob/peer-build/standalone/umd/vis-network.js instead of the version you're using now?

Yesss! It is displayed, So for the time being, use this scheme instead? when is it merged into the master?

**Comment by Thomaash** [comment]
We have a mandatory review policy so it's up to when @mojoaxel will find the time to review it and if no problems arise from the review.

**Comment by rochappy** [comment]
> We have a mandatory review policy so it's up to when @mojoaxel will find the time to review it and if no problems arise from the review.

@Thomaash Thank you for your prompt reply and look forward to the team update.

**Comment by mojoaxel** [comment]
@mojoaxel plz review #85 !

**Comment by mojoaxel** [comment]
> @mojoaxel plz review #85 !

#85 is approved.
