### ISSUE TITLE
vis does not support IE, I'm using version 11

### ISSUE THREAD

**Issue by MarwaSh** [visjs/vis-network#571]
Please make sure to **read the following list** before creating a new issue:

* This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on [stackoverflow](https://stackoverflow.com/questions/tagged/vis.js) tagged with "vis.js".
* Have you already used the [github search](https://github.com/visjs/vis-network/issues), read the [documentation](http://visjs.org/) and looked at the [examples](https://visjs.github.io/vis-network/examples)?
* Make sure to use the [latest version of vis-network](https://unpkg.com/vis-network@latest/dist/) for bug reports.
* Make sure to mention which browser and OS you are using when creating a bug report.
* Please provide a minimal code example that demonstrates your issue. We recommend using [jsbin](https://jsbin.com) for that.
* Delete this list from the actual issue.

**Comment by Thomaash** [comment]
IE11 is supported and works.

If you have a problem, you have to say more than it does not work.
