### ISSUE TITLE
vis network doesn't work for me on IE

### ISSUE THREAD

**Issue by MarwaSh** [visjs/vis-network#573]
I'm using IE version 11 and whenever I try to run my code (using Vis library) that works on chrome fine,
I got this error at the console: 'SCRIPT5007: Unable to get property 'enumerable' of undefined or null reference'

**Comment by Thomaash** [comment]
Hi @MarwaSh,

you have to provide something more than just the error. Ideally an MWE on JSFiddle or somewhere.

**Comment by igorzlatkov** [comment]
Doesent work for me either. As an example, event the standard samples don't work in IE11. 
for me, they give errors: 
SCRIPT438: Object doesn't support property or method 'assign'
vis-network.js (7125,2)
SCRIPT445: Object doesn't support this action
standalone.html (178,7)

this is for basic usage sample
https://visjs.github.io/vis-network/examples/network/basic_usage/standalone.html

its the same for 
https://visjs.github.io/vis-network/examples/network/basic_usage/peer.html
