### ISSUE TITLE
How initiate network with DataSet ?

### ISSUE THREAD

**Issue by jmmccota** [visjs/vis-network#588]
I'm using react with vis-network, latest version.

    "react": "16.13.1",
    "react-dom": "16.13.1",

After lib update:

    "vis-data": "6.5.1",
    "vis-network": "7.4.2",
    "vis-util": "4.0.0"

I tried to maintain my original import

    import { Network, DataSet } from "vis-network";

Or update my import to
    
    import * as vis  from "vis-network";

But keeps with this error: `TypeError: vis_network__WEBPACK_IMPORTED_MODULE_1__.DataSet is not a constructor`

If I change my import to

    import { DataSet } from "vis-data";

Crashes `this.network = new Network(this.container, data, options);` saying Network wait Array or DataSet.

How can I fix this?

**Comment by segfault16** [comment]
@jmmccota Just resolved this. I think the peer example in vis-network is wrong.. Maybe someone can verify if DataSet needs to be included from vis-data peer.
In the meantime you can have a look at how I resolved it:
https://github.com/crubier/react-graph-vis/compare/master...segfault16:master#diff-1fdf421c05c1140f6d71444ea2b27638

**Comment by Thomaash** [comment]
`vis-network` bundles everything, many things multiple times. It throws these and other errors in many circumstances. Don't use it. It will be deprecated and removed eventually.

`vis-network/standalone` bundles everything (polyfills + Vis Data). If you use this you have to use the DataSet exported by this. The downside of this is that it works only on it's own, it will fail when used together with Vis Timeline etc.

`vis-network/peer` bundles polyfills only. You have to use DataSet from `vis-data/peer`. An advantage here is that it works together with Vis Timeline etc.

`vis-network/esnext` bundles nothing. You have to supply all dependencies yourself and use DataSet from `vis-data/esnext`. The advantage in this is that you can reuse polyfills and other dependencies from your app, reducing bundle size.

**Comment by segfault16** [comment]
@Thomaash Thanks for the clarification!
Just wondering though if this is in the documentation somewhere....

**Comment by Thomaash** [comment]
The second through fourth examples document this (https://visjs.github.io/vis-network/examples/) and if you click “Show the getting started!” (https://visjs.github.io/vis-network/docs/network/) you'll get a summary. The ESNext is undocumented at the moment though and I agree this could be improved a lot (current state is solely due to lack of time, as always help is needed and deeply appreciated).

**Comment by sandrooco** [comment]
Documentation seems to be wrong here: https://visjs.github.io/vis-network/examples/network/basic_usage/peer.html
This say that `DataSet` should be imported from `vis-data` although you say `vis-data/peer`, which also works for me.

In my opinion there should only be one way to import (parts of) libraries. Backwards compatibility will be given with the version you load from npm. Although I know that this would stop old projects from getting new features, which wouldn't be such a bad thing.

**Comment by Thomaash** [comment]
> Documentation seems to be wrong here: https://visjs.github.io/vis-network/examples/network/basic_usage/peer.html
> This say that `DataSet` should be imported from `vis-data` although you say `vis-data/peer`, which also works for me.
> 
> In my opinion there should only be one way to import (parts of) libraries. Backwards compatibility will be given with the version you load from npm. Although I know that this would stop old projects from getting new features, which wouldn't be such a bad thing.

Having only a single way to load stuff would be great. Except that there are different usecases and it's very difficult (probably even impossible) to satisfy all with a singe way of importing.

**Comment by jmmccota** [comment]
> 
> 
> Documentation seems to be wrong here: https://visjs.github.io/vis-network/examples/network/basic_usage/peer.html
> This say that `DataSet` should be imported from `vis-data` although you say `vis-data/peer`, which also works for me.
> 
> In my opinion there should only be one way to import (parts of) libraries. Backwards compatibility will be given with the version you load from npm. Although I know that this would stop old projects from getting new features, which wouldn't be such a bad thing.

For me only works calling `DataSet` from `vis-data/per`, thanks all. @Thomaash @sandrooco
