### ISSUE TITLE
icon.fonts - choose other icon libraries

### ISSUE THREAD

**Issue by wernerdaehn** [visjs/vis-network#59]
Would love to get a higher degree of freedom in the network.nodes.icon.face option.
To be more concrete, these icons as well.
https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons

Quite frankly I don't understand why you cannot set any value there and it gets added as the element's style={font-family: xxxx}.

Thanks in advance for considering.

**Comment by mojoaxel** [comment]
this is related to #31

**Comment by Thomaash** [comment]
Hi @wernerdaehn, could you provide an MWE please? Because this seems to work just fine to me: http://jsfiddle.net/wpcr1qfs/. Although you have to ensure that the icons are loaded before the initial rendering happens, otherwise they will appear only after zooming or similar actions.

**Comment by wernerdaehn** [comment]
Well, that would be even better if this is just a doc issue. From your code I don't understand where the "Material Design Icons" get loaded and defined. Can you do me a favor and modify your code so that on of the SAP-Icons is used? Just to proof the point.

**Comment by Thomaash** [comment]
I have no idea about SAP-Icons and I found no CDN link with the webfont, but simply load the CSS like this `<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.0.96/css/materialdesignicons.min.css">
`.

**Comment by wernerdaehn** [comment]
You are absolutely correct, this is a documentation-bug only. Yes you can specify any correctly defined font-family.
I use

    n.shape = 'icon';
    n.icon = {face: 'SAP-icons',
      code: '\uE0E5',
      size: 50,
      color: '#eeeeee'}

in a page where the font is defined already - within a OpenUI5 page the font is already defined, obviously - and it renders nicely.

**Comment by ben-gryps** [comment]
I would like to use mui icons [(Mui Icons Docs).](https://mui.com/material-ui/icons/)

Any ideas how to make it work? Thanks!
