### ISSUE TITLE
Init Load Zoom - Network.Js 5.2.1

### ISSUE THREAD

**Issue by grovolis** [visjs/vis-network#60]
Hi all,

Since the last update vis-network@5.2.1/dist/vis-network.min.js, the fit() method and subsequently the initial zoom during network init seems to be broken and focusing on random places within the network. 

Reverted back to the 5.2.0 and everything works fine, so it seems this has to do with the latest push.

Let me know if you need any additional information.

Thanks,
George

**Comment by mojoaxel** [comment]
I can confirm this:
https://visjs.github.io/vis-network/examples/network/layout/hierarchicalLayout.html
