### ISSUE TITLE
Network.getPositions() TS type/documentation does not align with actual implementation.

### ISSUE THREAD

**Issue by tzfx** [visjs/vis-network#634]
Hello there!

One of our projects was working on hooking into the afterDrawing event and drawing some more objects around a given node. In doing this, we were attempting to use Network.getPositions in the manner defined by the ts definitions/documentation:
```js
  /**
   * Returns the x y positions in canvas space of the nodes with the supplied nodeIds as an object.
   *
   * Alternative inputs are a String containing a nodeId or nothing.
   * When a String is supplied, the position of the node corresponding to the ID is returned.
   * When nothing is supplied, the positions of all nodes are returned.
   */
  getPositions(nodeIds?: IdType[]): { [nodeId: string]: Position };
  getPositions(nodeId: IdType): Position;
```

The method getPositions(nodeId): Position is not actually implemented as defined: https://github.com/visjs/vis-network/blob/93a79d73099a8f13088ea93c6ad0210616b1a177/lib/network/modules/NodesHandler.js#L403-L428

So, either the ts definition for that overload should be removed/first one modified to accept the string only and return keyed position, or the getPositions() method on line 417 should be altered to return the x/y position object directly, rather than the dataArray object.

Or a new method getPosition(nodeId: IdType): Position rather than the overload and split return type?

I'm happy to open a PR with whatever direction you guys want to go.

**Comment by Thomaash** [comment]
I'd personally go with:
```typescript
getPositions(nodeIds?: IdType | IdType[]): Record<string, Position>;
getPosition(nodeId: IdType): Position;
```

It wouldn't break anything and it would provide a convenient and intuitive way of getting the position of a single node.
