### ISSUE TITLE
Multiple self-connected edges overlap

### ISSUE THREAD

**Issue by rediet** [visjs/vis-network#643]
Hi Team

I'd like to have multiple self-connected edges like in the example below. The issue is that these edges have an exact visual overlap and its not possible to see the two edges separately.  The same does not happen when two edges from one node are connected to another node in the same way.
My suggestion would be to simply increase the radius of each duplicate by a little, perhaps by the height of the label.
```javascript
var nodes = new vis.DataSet([
  {id: 1, label: 'Node 1'},
]);

var edges = new vis.DataSet([
  {from: 1, to: 1, label: 'Edge 1 is here'},
  {from: 1, to: 1, label: 'Edge 2'},
]);
```
<img width="303" alt="edges" src="https://user-images.githubusercontent.com/1153119/79640847-386c8380-8194-11ea-8fec-ce4b22050602.png">

**Comment by Dignity1337** [comment]
There is actually an example that covers this:

https://codepen.io/pen/?&editable=true=https%3A%2F%2Fvisjs.github.io%2Fvis-network%2Fexamples%2Fstatic%2Fcodepen.e10d036f43df7649a3a496fd5aa88783772d98a411f5d03e0aa766fdc7db3697.html

This is one of the examples found on the vis.js website. As you can see you can set a selfReference object for each edge. Inside of this object you can define the size and also the angle in rad.

**Comment by rediet** [comment]
This is exactly what I was looking for. Thank you very much.
