### ISSUE TITLE
DataSet is not a constructor

### ISSUE THREAD

**Issue by Tyler-Maclachlan** [visjs/vis-network#646]
Hi I upgraded from `7.3.4` to `7.5.0` and now I get an error in the constructor:

`"TypeError: vis_network__WEBPACK_IMPORTED_MODULE_34__.DataSet is not a constructor"`

This is how I imported it in `7.3.4`

`import { Network, DataSet, Node, Edge } from 'vis-network';`

And now in `7.5.0`

This `import { Network, DataSet, Node, Edge } from 'vis-network';`

Gives me the DataSet is not a constructor error

And

`import { Network, Node, Edge } from 'vis-network';
import { DataSet } from 'vis-data';`

Gives me a `Expected DataSet or Array` error

**Comment by Tyler-Maclachlan** [comment]
@Thomaash can you help out with this. It doesn't work with `import { Network, DataSet, Nodes, Edges } from 'vis-network/standalone';` either.

It looks like all the releases use the same `entry-esnext.d.ts` file

**Comment by Thomaash** [comment]
This should be fixed since 7.6.1.

**Comment by Tyler-Maclachlan** [comment]
@Thomaash, This is the error I get on `7.6.1`

`./node_modules/vis-network/peer/umd/vis-network.min.js
Module not found: Error: Can't resolve 'vis-data/peer' in '/home/tylermaclachlan/Documents/active-mapper-dashboard/node_modules/vis-network/peer/umd'`

**Comment by Thomaash** [comment]
Just to explain this. The peer build doesn't contain Vis Data. That's the whole idea behind it. If you want to use the peer build you have to import from Vis Data (`import { DataSet } from "vis-data/peer";`).
