### ISSUE TITLE
Dragging layout in 'Add Edge Mode'

### ISSUE THREAD

**Issue by segfault16** [visjs/vis-network#655]
The layout jumps when dragging in add edge mode.
See https://visjs.github.io/vis-network/examples/network/version_migration/5.4.1_to_6.0.0/manipulationEditEdgeNoDrag.html

To reproduce:
- Click Edit
- Click Add edge
- Click and drag anywhere in the empty space of the network. The layout then jumps.

**Comment by DavidIreland1** [comment]
Duplicate of #603
