### ISSUE TITLE
Option to disable disable automatic resizing, zooming, scaling, repositioning. Position based on HTML element location.

### ISSUE THREAD

**Issue by stevenlafl** [visjs/vis-network#671]
I'd like to handle resizing and scaling myself. I want to overlay visjs onto HTML I defined myself.
For example: I want to design a page with blocks, other elements and then anchor nodes onto elements. 

For example: these boxes are set up exactly on the page where I want them. I want to draw a line between them with visjs. I want to use visjs for adding lines between blocks dynamically.

```
_______      ______
|     |      |    |
|    X|------|X   |
|_____|      |____|
```

When I resize the browser, it for example breaks into something more like this because of the scale.
```
_______      ______
| x---|-x    |    |
|     |      |    |
|_____|      |____|
```

If I can disable automatic resizing, zooming, scaling, repositioning, etc. and have it static based on the CANVAS itself, which is 100vw/100vh mapped directly to the positions of the elements on the page, this is ideal for me.

I understand this is not the general use-case for visjs, but this is the only module I have found that can ELEGANTLY perform this kind of excellent UI.

For reference, I attempting something like this in UE4: 
![image](https://user-images.githubusercontent.com/2539092/80402428-e4e0f080-888b-11ea-86b5-bb9b2f8c5c0f.png)

Except I need the elements to exist and stay where they are, with the connect points (nodes) staying anchored to them. I'll handle all the saving and other logic for edges server-side.

**Comment by stevenlafl** [comment]
https://github.com/sdrdis/jquery.flowchart I guess I'll live with this.

**Comment by Thomaash** [comment]
Hi @stevenlafl,

you can actually do that:
```json
{
  "autoResize": false,
  "interaction": {
    "dragNodes": false,
    "dragView": false,
    "keyboard": false,
    "zoomView": false
  },
  "physics": {
    "enabled": false,
    "stabilization": false
  }
}
```

It's of course up to you. If jQuery Flowchart fits your needs better, use that.
