### ISSUE TITLE
problems with vis.js builds on windows

### ISSUE THREAD

**Issue by luiseduardo123** [visjs/vis-network#699]
Hello, please I need your help, sorry for my inexperience and for my bad English hehehe, when I run the "npm run build" without making any changes, and I try to use the generated js, it gives me the following error:
basicUsage.html: 26 TypeError not captured: vis.DataSet is not a constructor

Can someone tell me why please. Thank you.
![image](https://user-images.githubusercontent.com/7430745/81587499-66ba3900-93b7-11ea-91ba-d450a650ff98.png)

**Comment by LeMoussel** [comment]
Any reason you don't use 'https://unpkg.com/vis-network/standalone/umd/vis-network.min.js" ? As the examples you can found in the examples directory of the project.

**Comment by luiseduardo123** [comment]
Thank you, i want do a change in the API, but i until was trying build but i have this problem 😭😭😭😭

**Comment by LeMoussel** [comment]
To help you further information is required.

- Source code of "basicUsage.html"
- "pepe" project tree 
....

**Comment by luiseduardo123** [comment]
https://drive.google.com/file/d/1Uc94uJ8oXRrc7C1aYdq_gHw78SmabEMp/view?usp=sharing
in this link is the code that I am using and the files generated when executing "npm run build", thank you very much for helping me.

**Comment by Thomaash** [comment]
Sadly the only “fix” at the moment is to build on Linux (that's where unpkg and npm stuff comes from) or Mac. I have no idea what's wrong and not enough time to work on it (I tried but failed and ran out of time and ideas). If you come up with anything though (a PR ideally, but anything can help) feel free to post it here and thanks if you do.

**Comment by luiseduardo123** [comment]
I have been trying out on Linux as you said and it works! The problem is just on Windows. I will look into why this is happening. If I get it I will share (post) it here. Thank you so much

**Comment by yotamberk** [comment]
@luiseduardo123 any insights? I'm having the same issue
