### ISSUE TITLE
Missing `addNode` and `addEdge` methods in public API

### ISSUE THREAD

**Issue by aryzing** [visjs/vis-network#700]
When wanting to add nodes or edges to the network, the only documented options I could find were to either 
1. Re-create the graph by passing in all existing data + the new node/edge with `setData({...})`, or
2. Use the GUI and click around to add nodes

How can I add a node or edge without recreating re-setting all the data or using the GUI?

Would it be possible to expose the GUI methods for adding nodes and edges through the global API?

**Comment by aryzing** [comment]
Was able to implement the desired functionality using the methods on the `DataSet` instances used to create the network graph. 

```ts
const nodesDataSet = new DataSet(nodes);
const edgesDataSet = new DataSet(edges);
const data = {
  nodes: nodesDataSet,
  edges: edgesDataSet,
};
const network = new Network(container, data, options);

// later in the app

nodesDataSet.add({id: 'test-id-123', label: 'Test'})
```

After calling the `add` method, the node appeared on the graph as expected. 

[Docs for DataSet](https://visjs.github.io/vis-data/data/dataset.html#Methods).

Will keep issue open b/c I still feel it's worth either exposing these methods in the global API for network, or at least amending the docs document how to achieve this.

**Comment by Thomaash** [comment]
> Was able to implement the desired functionality using the methods on the `DataSet` instances used to create the network graph.
> 
> ```ts
> const nodesDataSet = new DataSet(nodes);
> const edgesDataSet = new DataSet(edges);
> const data = {
>   nodes: nodesDataSet,
>   edges: edgesDataSet,
> };
> const network = new Network(container, data, options);
> 
> // later in the app
> 
> nodesDataSet.add({id: 'test-id-123', label: 'Test'})
> ```
> 
> After calling the `add` method, the node appeared on the graph as expected.
> 
> [Docs for DataSet](https://visjs.github.io/vis-data/data/dataset.html#Methods).
> 
> Will keep issue open b/c I still feel it's worth either exposing these methods in the global API for network, or at least amending the docs document how to achieve this.

This is the correct way to do it. If you feel it should be clarified in the docs feel free to open a PR.

Exposing them on Network would be tricky because there are multiple methods and especially type safety would be nontrivial.
