### ISSUE TITLE
how i add a dynamically edge

### ISSUE THREAD

**Issue by aimeiyijia** [visjs/vis-network#705]
add() is not work

**Comment by Thomaash** [comment]
This is so vague that I have no idea what's your problem.

See https://visjs.github.io/vis-network/examples/network/data/dynamicData.html.

**Comment by aimeiyijia** [comment]
like this :
       edges.add({ id: 29, from: 2, to: 3, direct: "right", label: "right" })
when i use it with vuejs,page will blank

**Comment by Thomaash** [comment]
I have no idea what `edges` is. However Vue reactivity messes with out Data Sets. Try exempting them from reactivity (just wild guess due to sever lack of info from your side).

**Comment by aimeiyijia** [comment]
look this
let edgeArr = [
			{ id: 21, from: 1, to: 3, direct: "right", label: "right" },
			{ id: 22, from: 1, to: 2, direct: "left", label: "left" },
			{ id: 23, from: 2, to: 4, direct: "all", label: "all" },
			{ id: 24, from: 2, to: 5, direct: "all", label: "all" },
];
edges = new vis.DataSet(edgeArr);

**Comment by aimeiyijia** [comment]
how to 'exempting them from reactivity'?,i try but still not work

**Comment by aimeiyijia** [comment]
thanks   
when I removed network from the declared data properties(vue),it work

**Comment by achievement008** [comment]
Try it https://github.com/alexcode/vue2vis for vue app
