### ISSUE TITLE
Export canvas to image

### ISSUE THREAD

**Issue by cristianocca** [visjs/vis-network#722]
Hello,

I'm trying to export the canvas to a PNG image, but for some reason I seem to always get blank/empty files.

I've tried these two alternatives:
`network.canvas.getContext().canvas.toDataURL("image/png")`
`document.getElementsByTagName("canvas")[0].toDataURL("image/png")`

What am I missing?

Note: Using right click + save image works as expected.

**Comment by cristianocca** [comment]
Not sure why toDataURL doesn't work, but it worked with another one.

```
function getImage(cb){
    if(!network){
      return null;
    }

    network.canvas.getContext().canvas.toBlob(function(b){
      var reader = new FileReader();
      reader.onloadend = function() {
        cb(reader.result);
      }
      reader.readAsDataURL(b);
    })
  }
```

**Comment by Thomaash** [comment]
It's over a year and I don't remember it all that well but my solution is on https://github.com/Thomaash/me/blob/master/src/components/vis/VisCanvas.vue (warning: it's Vue project). To put it simply create a giant canvas (be aware that there are limitations and it's generally not worth it trying to work around them) that will fit everything and call `toBlob()`. The reason why you can't export what's not visible is that it's simply not there, the canvas is only what you see and nothing beyond that exists.

**Comment by cristianocca** [comment]
That was helpful. Rather than a giant canvas, just get the min/max X/Y and build a canvas just big enough to fit everything, use those values for the canvas site, and call .fit() before exporting. Seems to work as expected!
