### ISSUE TITLE
I need to create non-stop nodes moving, or complete network

### ISSUE THREAD

**Issue by Cleanerrr** [visjs/vis-network#770]
Hi,
I want to create a network with nodes which are in non-stop moving. I tried with repulsion, but no success. Anybody any suggestion?
` var options = {
      width: '100%',
	  interaction:{
	    tooltipDelay: 300,
	    zoomView: false
	  },
	  layout: {
	  	randomSeed: undefined,
	    improvedLayout:true,
	    clusterThreshold: 150,
	    hierarchical: {
	      enabled:false,
	      levelSeparation: 150,
	      nodeSpacing: 100,
	      treeSpacing: 200,
	      blockShifting: true,
	      edgeMinimization: true,
	      parentCentralization: true,
	      direction: 'LR',        // UD, DU, LR, RL
	      sortMethod: 'hubsize',  // hubsize, directed
	      shakeTowards: 'leaves'  // roots, leaves
	    }
	  },
	  physics: {
	  	enabled: true,
	  	stabilization: {
	      enabled: false,
	      iterations: 10000,
	      updateInterval: 1000,
	      onlyDynamicEdges: false,
	      fit: false
	    },
	    repulsion: {
	      centralGravity: 0.3,
	      springLength: 150,
	      springConstant: 0.02,
	      nodeDistance: 200,
	      damping: 0.09
	    },
	    solver: 'repulsion',
	    timestep: 0.3,
	    maxVelocity:50,
	    minVelocity:0.1,
	    wind: { x: 0, y: 0 },
	    adaptiveTimestep: false
	  },
	  edges:{
	  	chosen: false,
	  	length: 250,
	  	color: {
	      color:'#848484',
	      highlight:'#ff7e00'
	    }
	  },
	  nodes:{
	  	borderWidth: 1,
	  	widthConstraint: false,
    	chosen: false,
    	physics: true,
    	mass: 3,
    	shape: 'box',
    	color: {
	      border: 'transparent',
	      background: '#000',
	      highlight: {
	        border: '#ff7e00',
	        background: '#000'
	      },
	      hover: {
	        border: '#ff7e00',
	        background: '#000'
	      }
	    },
	    font: {
	      color: '#ff7e00',
	      multi: 'html',
	      size: 25,
	      face: 'Ubuntu-Light',
	      align: 'center'
	    }
	  }
	};

    // initialize your network!
    var network = new vis.Network(container, data, options);`
Thank you in advance

**Comment by Thomaash** [comment]
You have to do this manually (change the node's positions in the data set using setInterval or something, depends on your specific needs). All the physics stuff, though imperfect, is designed to stabilise over time and stop moving.

Thanks to the forementioned imperfections it's possible to create constant movement for example with the following spinner (you have to carefully arrange the nodes by hand for it to work and keep in mind it's very fragile, it also can stop working in the future as this is a flaw in the algorithm, it's not a part of the API):
![vis-network-spinner](https://user-images.githubusercontent.com/12966757/83652597-18b1e300-a5bb-11ea-9004-4dbd376ebea2.png)

**Comment by Cleanerrr** [comment]
Hi,
thank you @Thomaash for your answer. 
I tried many many solutions, and my nodes moving one time, but for some time all network stoped.  I tried with repulsion, forceAtlas2Based, and with other physic options, but every time my network stops at the end. I need to set options for non-stop moving, random or circular, or... Do you have, maybe, some live example or some new hints?

**Comment by Thomaash** [comment]
Is I said the physics is meant to stop. If you want constant movement you have to do it yourself for example like https://jsfiddle.net/v1c0ztxo/.
