### ISSUE TITLE
calling Stabilize on the network doesn't store the positions on node and edge dataset

### ISSUE THREAD

**Issue by Instinct408** [visjs/vis-network#776]
I am using layouts from other framework and storing the positions it in node and edge datasets. However, I use stabilize to get a force direct layout from visjs. When calling stabilize, it doesn't seem to save the x and y position within those datasets. Its still storing the old x and y position from a different layout I am using. So everytime I update the dataset (to show node labels), the old positions are used and my force layout changes to whatever previous layout I had.

How do I sync the node positions from the network to the dataset itself?

**Comment by Thomaash** [comment]
Stabilization is not supposed to alter the datasets. Use `network.storePositions()` if you want that.
