### ISSUE TITLE
DataView filter works only on 2nd update of external parameter.

### ISSUE THREAD

**Issue by raemounz** [visjs/vis-network#789]
Browser: Chrome
OS: Windows
vis-network version: 7.6.9
Language: Typescript
Framework: React

[Code]
```
const ParentComponent: React.FC = () => {
    const networkRef: any = useRef();

    // Somewhere in the code, I call this
    networkRef.current.filter(["id0, id1, id2"]);

    return (
    ...
        <VisNetwork 
            ref={networkRef}
        />
    ...
    )
}
export default ParentComponent;

interface Props {
    ref: any;
}
const VisNetwork: React.FC<Props> = forwardRef((props: Props, ref) => {
    useImperativeHandle(ref, () => ({
        filter(items: any) {
            setFilterNodes(items);
            nView.refresh();
        }
    }));

    const [filterNodes, setFilterNodes] = useState<any[]>([]);
    const filterNodesRef = useRef(filterNodes);
    useEffect(() => {
        filterNodesRef.current = filterNodes;
    }, [filterNodes]);

    ...
    // Some code to create the network (concentrate on the nodesView filter method)
    const [nView, setNView] = useState<DataView>();
    const nodesView = new DataView(nodes, {
        filter: (n: any) => {
            if (filterNodesRef.current.includes(n.id)) {
                return true;
            }
            return false;
        }
    });
    setNView(nodesView);
    const network = new vis.Network(container, {nodes: nodesView, edges: edgesView}, options);
});
export default VisNetwork;
```

[Issue]
The `DataView` filter should work when `filterNodesRef.current` changes.  But it doesn't.  It only works when I call  `networkRef.current.filter(["id0, id1, id2"]);` the second time.

**Comment by Thomaash** [comment]
I have no idea about React and don't fully understand the code you provided but if it is any similar to Vue the problem is that the data view has no way of knowing something has changed. The only thing it gets is some function and that's it. It has no idea what's going on in the function, that the values in its scope changed after it's execution or that it is being instantiated from withing React component.

If React has something like watches simply call `dataView.refresh()` when any of relevant values changes.

**Comment by raemounz** [comment]
I updated the code.  I am actually calling the `refresh()` method when `filter` is called.  However, still it only works the second time.

**Comment by raemounz** [comment]
I finally solved it.  I called the `refresh()` method inside the `useEffect()` instead.
```
useEffect(() => {
    filterNodesRef.current = filterNodes;
    nView.refresh();
}, [filterNodes]);
```
I will close this issue.  Thanks for your immediate reply.
