### ISSUE TITLE
change suggestion in manipulation.editEdge

### ISSUE THREAD

**Issue by dalaven** [visjs/vis-network#800]
It required customizing the edges but the manipulation.editedge only gave me the id, label, to and from, I couldn't get how to get the color, dashes or any other property, I could solve it by looking for the specific object with the id, overwriting the initial properties of the editstage function, I put it as a suggestion because this allows a better manipulation of the graphics.
Here my solution, it is preferable to use a function that this method
`manipulation:{
editEdge:function(data,callback){
                    data = network.edgesHandler.body.edges[data.id].options;
                    console.log(data);
                },
}`

**Comment by Thomaash** [comment]
Hi @dalaven,

I'm not exactly sure what you want to achieve. Why don't you just fetch it from the data set?
```javascript
const edges = new DataSet(/* Your usual initialization of edges. */);

const options = {
  manipulation: {
    editEdge({ id }, callback) {
      const data = edges.get(id);
      // Do whatever you need to do.
    },
  },
};

new Network(document.getElementById("your-network-element"), { edges }, options);
```

Generally, if it's not documented it's a really bad idea to touch it. `network.edgesHandler` is not part of the public API, it can change in any way or disappear without prior notice even in a bugfix release.

**Comment by dalaven** [comment]
thanks for your answer, 
I tried to use this function edge.get but it only brings me the information of, id, label, and I need all the properties, I was testing and found a way to get the information but when editing it did not change what was entered by the user, also thanks for the answer it helped me a little, I am still fixing, but I think it is already an error with a variable of mine
