### ISSUE TITLE
Is vis-network the right tool for building a mind map ?

### ISSUE THREAD

**Issue by LifeIsStrange** [visjs/vis-network#814]
I want to build a modern, fluid mindmap webapp.
After a lot of research I have no clear answer to which technoogy should be choosen for building a mindmap.

For which low level API to use amongst SVG, Canvas and WebGL the answer seems clear, Canvas is the best fit for 2D dynamic layouts. (SVG feels too static and WebGL is mostly for 3D or at least introduce unwanted complexity/learning curve)

But Canvas is far too low level for building a mind map:
We need a higher level framework that would give us (mostly for free but allowing us to customize):
zoom support
camera movements
and most importantly: the physics of links between the nodes.

Would Vis-network be the best fit ? What would be others great alternatives ? (as vis-network seems mostly unmaintained)

we have considered general puprose libs like D3.js:
it seems to be too complex and not enough specialized on nodes/links networks unlike vis-network

We have considered specialized libs for links physic like https://ptsjs.org/guide/get-started-0100
conclusion: it seems too low level/specialized

There is also general purpose canvas frameworks like canvas like https://konvajs.org/
but they seems too generalist.

I would apreciate any feedback on this issue :)

**Comment by Thomaash** [comment]
Hi @LifeIsStrange,

first of all I disagree that Vis Network is mostly unmaintained, it's definitely maintained, though we do desperately need more contributors.

You can use Vis Network to build a mind map, I see absolutely no problem with that. Personally I wouldn't use the other libs you suggested, they seem to low level for this task but that's just me, you're a different person who may have different priorities. Whether Vis Network would be the best fit though would be better answered on StackOverflow or some similar site.

**Comment by LifeIsStrange** [comment]
@Thomaash Thanks for the answer.
I asked the question on [StackOverflow](https://stackoverflow.com/questions/62474504/which-technologies-to-use-for-building-a-modern-mind-map-web-app) but asking about the right technology for a given problem is outside of the stack guideline... so my question got rejected.

I have a problem specific to vis-network:
by default when I drag a node with the mouse to another parent node it will move other nodes/links in an elastic way. How can we make a node movable without affecting others ?

is it prossible to drag a node, to "detach" it from its initial parent and to affect it a new parent ?

I have seen https://stackoverflow.com/questions/44148082/how-to-create-a-custom-tree-chart-style-layout-with-sharp-angles-vis-js as a solution (not to the dragging problem but just for preventing the elsatic movement) but it needs to have hidden nodes which is a hack I do not understand. What is the reasoning behind it and is there a cleaner way to achieve this ?

finally, is there a way to achieve something similar to https://konvajs.org/docs/sandbox/Modify_Curves_with_Anchor_Points.html in vis-js
