### ISSUE TITLE
How do I add custom button like the navigation buttons?

### ISSUE THREAD

**Issue by 24rochak** [visjs/vis-network#833]
I want to have my own buttons like them which stay at their location even when the whole network moves around. I tried drawing on the canvas but the drawings move when the network moves. I also tried creating a new button with the `class= vis-button vis-myButton` and adding custom css for `myButton` but that also didn't work.

Navigation Button example: https://visjs.github.io/vis-network/examples/network/other/navigation.html

How do I do it? Any help is appreciated. Thanks

**Comment by 24rochak** [comment]
I want to have my own buttons like them which stay at their location even when the whole network moves around. I tried drawing on the canvas but the drawings move when the network moves. I also tried creating a new button with the class= vis-button vis-myButton and adding custom css for myButton but that also didn't work.

Navigation Button example: https://visjs.github.io/vis-network/examples/network/other/navigation.html

How do I do it? Any help is appreciated. Thanks

**Comment by Thomaash** [comment]
Just add normal HTML/JS buttons into your DOM and on click call `network.moveTo(…)` ([docs](https://visjs.github.io/vis-network/docs/network/#methods)).

Alternatively you could restyle the default buttons to stop them from moving with the network:
```css
div.vis-network div.vis-navigation div.vis-button {
  position: fixed;
}
```

**Comment by 24rochak** [comment]
Thanks for your quick response. You might have mistaken by what I meant. I basically want a button that stays fixed like the navigation button and I can trigger my own functions onclick.

**Comment by Thomaash** [comment]
Oh, if that's the case, simply add your buttons to div.vis-navigation element that is next to the canvas and position them absolutely (you have to create them after Vis Network start and creates it's elements). That's how the stock buttons work.

**Comment by 24rochak** [comment]
I tried adding a new element to the div that you said. After adding it, I can see the new element in the child nodes of div.vis-navigation. However, it is not visible. I tried playing around with CSS as well but it didn't work. 
Right now, I'm able to add a new button by directly adding it to the body. However, I want it to be part of div.vis-navigation. 
It would be great if you could provide a snippet or a fiddle for the same? Thanks

**Comment by Thomaash** [comment]
```javascript
document
  .querySelector(".vis-navigation")
  .insertAdjacentHTML(
    "afterbegin",
    "<a style='position: absolute; bottom: 8em; left: 3em;' href='https://visjs.org/'>“button”</a>"
  );
```

**Comment by 24rochak** [comment]
Exactly what I needed. Thanks for your help. I'll close the issue.
