### ISSUE TITLE
react-vis-network node level positioning

### ISSUE THREAD

**Issue by LingarajChengti** [visjs/vis-network#846]
Using *React-vis-network version 1.0.0*  and below are the options used

Attached screenshot FYR, not able to fix the network node level positioning, 

issue in level positioning:  ![result](https://user-images.githubusercontent.com/35490731/86757913-1aab0e00-c061-11ea-98b2-785198d7530d.png)

Expected flow:     ![expected](https://user-images.githubusercontent.com/35490731/86757904-1979e100-c061-11ea-9437-1743d6f26489.png)

please help.

`visOptions = {
            layout: {
                hierarchical: {
                    enabled: true,
                    nodeSpacing: 330,
                    blockShifting: true,
                    parentCentralization: false,
                    edgeMinimization: true,
                    direction: 'UD',
                    sortMethod: 'directed',
                },
            },
            physics: true,
            nodes: {
                fixed: {
                    y: true,
                    x: true
                },
                margin:25,
                size: 50, 
                font: {
                    size: 25,
                    align: "center",
                    bold: {
                        color: "#bbbdc0",
                        size: 25,
                        vadjust: 0,
                        mod: "bold"
                    }
                }
            },
            physics: {
                forceAtlas2Based: {
                    gravitationalConstant: -50000,
                    centralGravity: 999,
                    springLength: 1,
                    springConstant: 9999,
                    avoidOverlap: 1
                },
                solver: 'forceAtlas2Based',
            }

**Comment by Thomaash** [comment]
This has been fixed in 6.0.2. You'll have to poke the maintainers of react-vis-network to update.

**Comment by LingarajChengti** [comment]
can you please loop me to maintainer of react-vis-network?
