### ISSUE TITLE
Edge arrows appear above node labels

### ISSUE THREAD

**Issue by bglasgo** [visjs/vis-network#883]
On my network, arrows on both and and middles of edges appear drawn a layer above any node label text, while the edges themselves are underneath the node label.

**Comment by Thomaash** [comment]
Hmm, this was introduced in #761. The reason is that the arrows can pierce into nodes and therefore have to be above the nodes. The problem is that a node and its label is a single unit even when the label is outside of the node, so there's no simple way to fix this.

**Comment by bglasgo** [comment]
Hmm, im not sure what you mean, all my arrows end up outside the nodes border so that wouldnt be an issue.  I haven't looked around in the code but, perhaps offer the user a setting of whether these get drawn above or below everything?

**Comment by Thomaash** [comment]
Hi @bglasgo,

for all shapes except for custom this should be resolved with the next release.

**Comment by bglasgo** [comment]
beautiful, great job!
