### ISSUE TITLE
Unable to remove circular 'handle'

### ISSUE THREAD

**Issue by missinglink** [visjs/vis-network#9]
Heya,

I'm trying to remove a circular 'handle' from the graph as seen in the screenshot on the right-hand side of the middle node.

<img width="202" alt="Screenshot 2019-07-24 at 11 24 24" src="https://user-images.githubusercontent.com/738069/61782197-ef0a2600-ae05-11e9-8086-41f0f39474ef.png">

Apologies, as it's a question phrased as a bug report, but I've gone through all the options in the docs and I can't find one which removes this circle!

I'm running the latest code from github with the following config (all interaction should be disabled):

note: the circle is present even when `options = {}`

```js
var options = {
    clickToUse: false,
    configure: {
      enabled: false
    },
    edges: {
      smooth: {
        type: 'cubicBezier',
        forceDirection: 'vertical',
        roundness: 0.4
      }
    },
    layout: {
      hierarchical: {
        enabled: true,
        direction: 'UD'
        // sortMethod: 'directed'
      }
    },
    physics: {
      enabled: false
    },
    interaction: {
      dragNodes: false,
      dragView: false,
      hoverConnectedEdges: false,
      selectConnectedEdges: false,
      multiselect: false,
      selectable: false,
      zoomView: false
    },
    enabled: {
      enabled: false
    },
    manipulation: {
      enabled: false
    },
    groups: {
      useDefaultGroups: false
    }
  }
```

**Comment by vletoux** [comment]
It has nothing to do with options but with your data.
You have an edge with the same node as start and as end.

**Comment by missinglink** [comment]
Right you are! Thanks very much, I knew I was doing something stupid!

**Comment by mojoaxel** [comment]
@missinglink Thanks for opening this issue. We are happy that it could be resolved! Working on these issues takes a lot of time. Please consider [supporting](https://opencollective.com/visjs/contribute) further maintenance and development!
