### ISSUE TITLE
Intermittent issue with afterDrawing event

### ISSUE THREAD

**Issue by DeZZar** [visjs/vis-network#90]
Hi Team,

I am using the "afterDrawing" event to draw images over nodes using the 'drawImage' method on the passed in canvas context.  We are finding that at times the images intermittently dissapear and its difficult to track down why as it is not consistenly repeatable.

They can dissapear just by clicking on the canvas or a node or an edge or by resizing the window. Sometimes by navigating to another tab and back again. Whenever they dissapear clicking again anywhere on the canvas causes them to reappear and it functions as normal until they next time they drop off.

It would appear that there is a chance somewhere within vis.network the callback isnt being triggered or some sort of re-draw occurs before the images can be applied which doesnt subsequently call the afterDrawing callback.

This is the code block that draws the images for reference.

```
this.visNetwork.on("afterDrawing", (ctx: CanvasRenderingContext2D) => {
            let nodeHeight: number;
            let imageObj: HTMLImageElement;

            const boundBoxes = {};
            const ids = this.ftData.nodes.map((node:any) => {
                boundBoxes[node.id] = this.visNetwork.getBoundingBox(node.id);
                return node.id;
            });
            const positions = this.visNetwork.getPositions(ids);

            this.ftData.nodes.forEach((node: ft_node) => {
                if (!node.hidden) {
                    imageObj = new Image();
                    imageObj.src = node.icon;
                    nodeHeight = FTUtility.getNodeHeight(boundBoxes[node.id]) / 2;
                    ctx.drawImage(imageObj, positions[node.id].x - 20, positions[node.id].y - (12 + nodeHeight), 40, 40);
                }
            });
        });
```

Any advise on the potential cause would be wonderful.

Kind regards,
Derrick

**Comment by DeZZar** [comment]
Just a little additional information that MAY assist with this.  I have also added the following line to print text straight after drawing the image and when the issue with the dissapearing images happens, the text is still rendered - it does not dissapear like the images do.

```
    ctx.font = '16px serif';
    ctx.fillText("...", positions[node.id].x + 40, positions[node.id].y - (nodeHeight - 10));
```

The images are simply PNG files referenced as their path.

Perhaps this is an asynchronous issue where the callback for 'afterDrawing' isnt awaited by vis.network?

**Comment by Thomaash** [comment]
Hi @DeZZar, are you sure the images are loaded? Canvas doesn't wait for I/O and simply skips anything it doesn't have. Since you create new images right before rendering there may not be enough of time to load them if they're not already cached.

In my experiments it doesn't work at all if caching is disabled. If caching is enabled it works reliably once the images are loaded and as long as they're cached.

Try whether you can trigger this problem by clearing cache or enabling “disable cache” in Network tab in Chrome's DevTools.

**Comment by DeZZar** [comment]
Thanks @Thomaash - appreciate the pointers.  I feel we MAY have resolved this.  The issue is to do with the timing of loading the images before they are rendered.  They are not present/referenced in the DOM at all so it doesnt really have anything to do with browser cache.

Instead what I've attempted is to create a method to load each icon into a map that is populated with loaded image objects.  The class that instantiates the vis.Network waits for this caching process to complete before it initialises vis.  From that point forward the pre-loaded image object is referenced in the 'afterDrawing' method.

With this working, so far, I've not been able to observe the dissapearance issue.

Thank you again for taking a look.  For anyone that may experience a similar issue in the future, this is the method created for caching the image objects:
```
    public static async cacheMemberIcons(): Promise<any> {
        const iconUrl: string = `${process.env.PUBLIC_URL}/graphics/icons/`;
        const icons: any = {
            "image1": {file: "image1", image: null},
            "image2": {file: "image2", image: null},
            "image3": {file: "image3", image: null}
        };
        const promises = Object.values(icons).map((icon: any) => {
            return new Promise((resolve) => {
                let imageObj: HTMLImageElement = new Image();
                imageObj.onload = () => {
                    icon.image = imageObj;
                    resolve();
                };
                imageObj.src = `${iconUrl}${icon.file}.png`;
            });
        });

        await Promise.all(promises);
        return icons;
    }
```
This method is called in the parent class (that contains vis) like so:
`this.imageCache = await Utility.cacheMemberIcons();`

And referenced in the drawing method as:
`ctx.drawImage(this.imageCache[node.icon].image, positions[node.id].x - 20, positions[node.id].y - (12 + nodeHeight), 40, 40);`
