### ISSUE TITLE
Scroll the page instead of the network graph

### ISSUE THREAD

**Issue by gmverdon** [visjs/vis-network#916]
I would like to scroll the page instead of the network graph so users on mobile can get 'past' the network graph which takes up the full screen. 

How can this be achieved.

Thanks in advance!

**Comment by Thomaash** [comment]
All interaction is optional and can be disabled, it's all documented surprisingly in the [documentation](https://visjs.github.io/vis-network/docs/network/interaction.html).

TLDR:
```javascript
const options = {
  interaction: {
    dragView: false,
  },
};
```
