### ISSUE TITLE
Export high quality graph

### ISSUE THREAD

**Issue by omidMolaverdi** [visjs/vis-network#924]
Well done for the great work.

I believe that this question is similar to https://github.com/visjs/vis-network/issues/722 however the previous one is quite technical for me to understand. 

I am looking for an easy way to export the network in high resolution so that the user can zoom in and read the details. Is there any quick ways of doing it please?

**Comment by Thomaash** [comment]
Hi @omidMolaverdi,

simply make the canvas bigger (beware that there are different limits in different browsers and no way to query them), zoom in and take the shot. That's what I do in https://github.com/Thomaash/me/blob/master/src/components/vis/VisCanvas.vue (warning: it's Vue project).

**Comment by omidMolaverdi** [comment]
@Thomaash  thanks. Is there any way in simple JS or Jquery. To be honest, I do not know vue

**Comment by Thomaash** [comment]
Sure, you can do this with vanilla JS or jQuery no problem. However if you can't do it on your own, you should ask on a site like StackOverflow. The issues here are only for the cases when there's something wrong with Vis Network itself.
