### ISSUE TITLE
Not working example changingClusteredEdgesNodes - edge color not changing

### ISSUE THREAD

**Issue by abazylewicz** [visjs/vis-network#94]
I tried example from https://visjs.github.io/vis-network/examples/network/other/changingClusteredEdgesNodes.html but it didn't work as expected for updating edges. Clicking an edge, no matter clustered or not, did not changed it color to red (on Chrome, FF, Safari).

It looks like Clustering.updateEdge() method does not update the color of the edge, but works for changing stuff like value and label of the edge. Not sure if this is intended behavior or not

**Comment by mojoaxel** [comment]
The description clearly states:

> Clicking on an edge will make it red regardless of whether it is a clusteredEdge or not (updateEdge)

Looks like a bug or a bad description to me.

**Comment by Thomaash** [comment]
Full color object instead of color string works fine:
```javascript
network.clustering.updateEdge(params.edges[0], {
  color: { hover: "#aa0000", highlight: "#aa0000", color: "#aa0000" }
});
```
