### ISSUE TITLE
Is it possible to support canvas drawing?

### ISSUE THREAD

**Issue by laike9m** [visjs/vis-network#947]
I would like to create a graph, in which several nodes are surrounded by a box.
![image](https://user-images.githubusercontent.com/2592205/89977398-e27a8a80-dc1f-11ea-8a5e-bd860b44bbdb.png)

In vis-network, we can use [getPositions](https://visjs.github.io/vis-network/docs/network/index.html?keywords=getPositions) to accquire node position. If there's a way to directly operate on canvas, I can draw the box myself.

Please forgive me if this is already supported, at least I didn't find how from the documentation.

**Comment by Thomaash** [comment]
Yes, you can use the `beforeDrawing` event for this, more details are in the docs at https://visjs.github.io/vis-network/docs/network/#Events.

**Comment by laike9m** [comment]
Thanks a lot, that's exactly what I need.
