### ISSUE TITLE
regeneratorRuntime is not defined [regeneratorRuntime is not defined] error in Salesforce

### ISSUE THREAD

**Issue by mrainboldt** [visjs/vis-network#954]
Receiving regeneratorRuntime is not defined [regeneratorRuntime is not defined] when trying to load the script explicitly into both lightning web component and aura component.
I cannot reference the url of the resource because of security around Salesforce.

when using https://unpkg.com/browse/vis-network@8.1.0/standalone/umd/vis-network.min.js

**Comment by Thomaash** [comment]
Hi @mrainboldt,

I have never used lightning web component nor aura component. Could you provide an MWE on StackBlitz, please? Otherwise I'm afraid I won't be able to help.

**Comment by mrainboldt** [comment]
Hi if you paste the js from above in this console you will get the error 
https://developer.salesforce.com/docs/component-library/tools/locker-service-console

**Comment by Thomaash** [comment]
The problem is that you're running regenerator runtime in strict mode, it doesn't work in strict mode, it actually uses the function constructor to escape strict mode if it finds itself in strict mode (CSP violation).

If you want to use Vis Network in strict mode you'll have to sacrifice compatibility for non-ES6 browsers (i.e. IE) by building `vis-network/esnext` with custom config that doesn't use regenerator runtime at all.

**Comment by mrainboldt** [comment]
Any thoughts now getting "Emitter is not a function"

**Comment by Thomaash** [comment]
Check that you have all peer dependencies installed.

**Comment by nbrown30** [comment]
@mrainboldt have you had any success with this build? I am also interested in using Vis.js with Lightning Web Components.

**Comment by mrainboldt** [comment]
@nbrown30 I have, I was going to create a generic one and put it on my repo.  I should be able to get to that this weekend, when I have it done it will be a new repo here https://github.com/mrainboldt?tab=repositories

**Comment by mrainboldt** [comment]
@nbrown30 Here is my repo with the lightning web component, would love your feedback or ideas on how to enhance.
https://github.com/mrainboldt/visNetworkMapLWC

**Comment by jpduckwo** [comment]
> The problem is that you're running regenerator runtime in strict mode, it doesn't work in strict mode, it actually uses the function constructor to escape strict mode if it finds itself in strict mode (CSP violation).
> 
> If you want to use Vis Network in strict mode you'll have to sacrifice compatibility for non-ES6 browsers (i.e. IE) by building `vis-network/esnext` with custom config that doesn't use regenerator runtime at all.

@Thomaash I've tried following this advice but not able to import the esnext module (using typescript / angular) https://github.com/visjs/vis-network/issues/1429 . Have you got any hints?
