### ISSUE TITLE
Directed hierarchical graph renders incorrectly when clusters enabled, depending on node ID

### ISSUE THREAD

**Issue by pmcnab** [visjs/vis-network#956]
I have a system that generates hierarchical graphs.  I have started development to support clusters, but have run into some strange rendering problems.

The graph is a directed hierarchical graph, but the default output from the jsfiddle shows the "Complete" node at the same level as two nodes that have edges going to the Complete node.  https://jsfiddle.net/pmcnab/L4z52j7q/7/

If you double-click on any cluster to expand it, then the graph re-calculates and correctly puts the "Complete" node below the other nodes.  

I have found that if the node id of the "complete" node is lower than the other node ids, the above behavior holds.  However, if the node id of the "complete" node is *higher* than other ids, then it renders correctly, whether it is clustered or not.

This is using vis-network 8.1.0 as can be seen in the fiddle.  I'm using Chrome 84.0.4147.125 on Windows 10, and a colleague verified the behavior using the latest Firefox (79) on Linux

I think it's a bug to have the node id have any impact on the resulting position of the node, when factoring in a directed graph with explicit edges defined.

**Comment by pmcnab** [comment]
After further review and testing, it's not just the node id.  Forcing the "Complete" node to have a higher integer ID than everything else improved in some cases, but not in others.  The jsfiddle does give a specific instance where if you toggle the "complete_node_id" in the javascript to the other value the graph will display differently, so hopefully that can lead to debugging the root problem.

**Comment by pmcnab** [comment]
Any comments on this?  This is blocking my deployment of clusters and making me consider if I'd be better off with an alternate graphing library

**Comment by Thomaash** [comment]
Hi @pmcnab,

could you provide an actual MWE, please? What you provided contains a lot of stuff that just doesn't seem to matter (a tonne of configuration, cycles etc.; also what is `cluster_hash`, `complete_node_id` etc.).

**Comment by pmcnab** [comment]
The cluster_hash is just a way to dynamically get all the list of cluster_ids from the node definition without having to hard-code them in multiple places.  

The "complete_node_id" is the id assigned to the "final" node of the hierarchical graph that everything else feeds into.  It's a variable in that example because I found that changing the node id changed the resulting layout in a way that should not be a valid configuration (meaning that when clusters are enabled, automatic hierarchical levels are not being placed correctly).

I stripped out more of the configuration and the dynamic derivation to make it easier to see, https://jsfiddle.net/pmcnab/L4z52j7q/14/

If you leave it as it is there, the "Complete" node, which in a directed UD hierarchical graph should be at the bottom level, is actually on the third level from the bottom.  If I change the "complete_id" to the commented out value at the top of the JS, then the complete node appears correctly at the bottom of the graph.

You can also see that when you double-click on a cluster to expand it, the complete node is put at the right place.

**Comment by pmcnab** [comment]
I made another update because I realized I was only clustering two of the three sets, https://jsfiddle.net/pmcnab/L4z52j7q/16/

This has a similar but different problem, which is that now the "Complete" node is on the bottom level, but several nodes that it depends on are on the same level.  

In all cases when I de-cluster things behave more as expected.

**Comment by pmcnab** [comment]
I can confirm with my jsfiddle that 8.2.1 seems to fix the problem.  I'll try using that with my production system and see if it works for general data.  Thanks!

**Comment by pmcnab** [comment]
This appears to be working now, thank you!
