### ISSUE TITLE
The sourcemap url in vis-network.css is incorrect

### ISSUE THREAD

**Issue by gregid** [visjs/vis-network#968]
Current sourcemap url in `vis-network.css` is:
```
/*# sourceMappingURL=styles/vis-network.css.map */
```
while both files are in the same folder, so it should be:
```
/*# sourceMappingURL=vis-network.css.map */
```
This is causing problems with bundlers, e.g.:
https://github.com/parcel-bundler/parcel/issues/5031

BTW The min file has correct url.

**Comment by Thomaash** [comment]
This is a problem in (Vis Dev Utils)[https://github.com/visjs/vis-dev-utils/issues/294].
