### ISSUE TITLE
is moment.js dependency really needed?

### ISSUE THREAD

**Issue by bel0v** [visjs/vis-network#97]
Hi!
I've spotted there is a moment.js dependency which adds up quite a lot to bundle size. But I cannot really see it is used in the network module. Could you confirm it is needed?

I've found 2 cases:
1) `moment().utc().format()` // come on
2) usage in timeline examples, which belong in https://github.com/visjs/vis-timeline

Cheers!

**Comment by Thomaash** [comment]
Number one is only dev dependency.

**Comment by Thomaash** [comment]
It seems we don't need it at all except for backwards compatibility (some people are likely importing Moment through our bundle).

**Comment by bel0v** [comment]
@Thomaash I could make a PR deleting it and it could be shipped in a major release in accordance to semver, what do you think?

**Comment by Thomaash** [comment]
I think we should discuss it as part of #85 since there are more problems with dependency handling which require an overhaul of bundling.
