### ISSUE TITLE
Using font awesome 5 as icons displayed as rectangles, continued issues

### ISSUE THREAD

**Issue by PrzemyslawKlys** [visjs/vis-network#984]
This is a continuation of https://github.com/visjs/vis-network/issues/139. Sorry for resurrecting the old issue. 

So I'm looking at given examples: https://jsfiddle.net/api/post/library/pure/ to follow your advice of race condition, and it seems that even examples have this issue with rectangles:

![image](https://user-images.githubusercontent.com/15063294/91213150-787ade80-e711-11ea-87fb-f0e67525f532.png)

You mention there's a way to make sure font is loaded before vis display things, but I can't see it anywhere in the examples. Could you maybe point me to one?

**Comment by Thomaash** [comment]
The example fails because it tries to load HTTP resources from HTTPS page, Font Awesome 5 is the only font loaded via HTTPS and also the only one rendered. Anyway the interesting part is the following code:
```javascript
if (document.fonts) {
  // Decent browsers: Make sure the fonts are loaded.
  document.fonts
    .load('normal normal 900 24px/1 "Font Awesome 5 Free"')
    .catch(console.error.bind(console, "Failed to load Font Awesome 5."))
    .then(function () {
      // create a network
      const network = new vis.Network(container, data, options);
    })
    .catch(
      console.error.bind(
        console,
        "Failed to render the network with Font Awesome 5."
      )
    );
} else {
  // IE: Let's just hope the fonts are loaded (they're probably not,
  // hence the timeout).
  window.addEventListener("load", function () {
    setTimeout(function () {
      // create a network
      const network = new vis.Network(container, data, options);
    }, 500);
  });
}
```

**Comment by PrzemyslawKlys** [comment]
Maybe something like this would work as well? https://cssminifier.com/article/how-to-defer-css-font-loading

**Comment by Thomaash** [comment]
> Maybe something like this would work as well? https://cssminifier.com/article/how-to-defer-css-font-loading

Help with what exactly?

**Comment by PrzemyslawKlys** [comment]
Preloading fonts before everything else. While the article talks about defering CSS it states that you can control when exactly fonts are loaded.

**Comment by Thomaash** [comment]
Not really. You don't want to defer the CSS to prevent empty rectangles, quite the opposite actually. You want to load it ASAP (before `new vis.Network(…)` gets executed, which happens as soon as the HTML and JS is parsed). Unless, of course, you have a long lived page that may or may not call `new vis.Network(…)`, then the article is spot on.

**Comment by PrzemyslawKlys** [comment]
Would I need to take care of all 3 font awesome fonts or just waiting for the first one is enough?

**Comment by Thomaash** [comment]
> Would I need to take care of all 3 font awesome fonts or just waiting for the first one is enough?

You have to take care of all the fonts that you use.
