### ISSUE TITLE
how to draw a service path over topology network

### ISSUE THREAD

**Issue by zachary918** [visjs/vis-network#988]
Please make sure to **read the following list** before creating a new issue:

* This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on [stackoverflow](https://stackoverflow.com/questions/tagged/vis.js) tagged with "vis.js".
* Have you already used the [github search](https://github.com/visjs/vis-network/issues), read the [documentation](http://visjs.org/) and looked at the [examples](https://visjs.github.io/vis-network/examples)?
* Make sure to use the [latest version of vis-network](https://unpkg.com/vis-network@latest/dist/) for bug reports.
* Make sure to mention which browser and OS you are using when creating a bug report.
* Please provide a minimal code example that demonstrates your issue. We recommend using [jsbin](https://jsbin.com) for that.
* Delete this list from the actual issue.

Hi guys, 
I have created my network based on vis-network, it is great and efficient. but i have more requirements than this, i want to draw a path over the network topo, do we have a method that can do it, or do we have an API , we could draw a path over the network topo.  just like attached. thank you very much
best
zachary
![path over topo](https://user-images.githubusercontent.com/63443214/91382855-41b1df00-e85d-11ea-87e4-fb684b452708.png)

**Comment by Thomaash** [comment]
Burn her!

Where'd you get the coconuts? Burn her anyway! And this isn't my nose. This is a false one. Be quiet!

Ah, now we see the violence inherent in the system! You don't frighten us, English pig-dogs! Go and boil your bottoms, sons of a silly person! I blow my nose at you, so-called Ah-thoor Keeng, you and all your silly English K-n-n-n-n-n-n-n-niggits!
Listen. Strange women lying in ponds distributing swords is no basis for a system of government. Supreme executive power derives from a mandate from the masses, not from some farcical aquatic ceremony.

Camelot! The Knights Who Say Ni demand a sacrifice! Well, how'd you become king, then? A newt?

    Oh! Come and see the violence inherent in the system! Help, help, I'm being repressed!
    But you are dressed as one…
    Why?

Who's that then?

We want a shrubbery!! …Are you suggesting that coconuts migrate? We found them. You don't vote for kings. Well, I didn't vote for you. Camelot!

    Did you dress her up like this?
    Why do you think that she is a witch?
    Shut up! Will you shut up?!

And this isn't my nose. This is a false one. Shut up! Will you shut up?! Oh! Come and see the violence inherent in the system! Help, help, I'm being repressed! He hasn't got shit all over him. He hasn't got shit all over him.

Did you dress her up like this? …Are you suggesting that coconuts migrate? Well, we did do the nose. On second thoughts, let's not go there. It is a silly place. And this isn't my nose. This is a false one.

Well, how'd you become king, then? Look, my liege! Be quiet! Oh, ow! Camelot!

I have to push the pram a lot. And the hat. She's a witch! Be quiet! But you are dressed as one… He hasn't got shit all over him.

Well, I didn't vote for you. I'm not a witch. Bring her forward! We found them. You don't vote for kings. Bring her forward!

But you are dressed as one… I'm not a witch. We found them. Be quiet! You can't expect to wield supreme power just 'cause some watery tart threw a sword at you! You don't vote for kings.

You can't expect to wield supreme power just 'cause some watery tart threw a sword at you! The Knights Who Say Ni demand a sacrifice! You can't expect to wield supreme power just 'cause some watery tart threw a sword at you!

Shut up! Will you shut up?! Why? Bring her forward! And this isn't my nose. This is a false one. Shut up!

Well, what do you want? What do you mean? You don't frighten us, English pig-dogs! Go and boil your bottoms, sons of a silly person! I blow my nose at you, so-called Ah-thoor Keeng, you and all your silly English K-n-n-n-n-n-n-n-niggits!

I'm not a witch. A newt? No, no, no! Yes, yes. A bit. But she's got a wart. Bloody Peasant!

He hasn't got shit all over him. Well, Mercia's a temperate zone! Well, how'd you become king, then? Where'd you get the coconuts? I'm not a witch.

Hi @zachary918,

you can use the `afterDrawing` event to draw anything on the canvas, including the line shown on your screenshot.

**Comment by zachary918** [comment]
thanks a lot, cloud you please provide an example with afterDrawing, thanks again

**Comment by zachary918** [comment]
great! thanks a lot for your help!
