### ISSUE TITLE
Nodes with Fixed property will still move in physics simulation

### ISSUE THREAD

**Issue by charleshtrenholm** [visjs/vis-network#991]
Hello,

I have a very specific use case where I have a set of nodes of 2 different types that are coming from our backend. The first type (type A) has a defined structure and is sent with specific X Y coordinates. The second type (type B) are generally "children" of the type A nodes and do not have fixed coordinates. 

The behavior I want is for the type A nodes to maintain the exact coordinates given by the backend, and lay the type B nodes out in such a way where I can utilize physics to have them repel from the type A nodes and from each other. I have tried many different configurations but generally have been using barnesHut as the physics option.

I currently have it set up so that it is initially layed out with physics and the type A nodes with XY coordinates are laid out with their coordinates and the `fixed` property set to true. I then turn the physics off after `stabilizationIterationsDone` because we only want to use the physics for initial layout. What I'm seeing is that even when nodes have coordinates and are fixed, they are still getting affected by other nodes. Changing mass seems to have no effect.

According to the documentation for fixed property:
> When true, the node will not move but IS part of the physics simulation
and for x and y properties: 
>  When using stabilization, the stabilized position may be different from the initial one. To lock the node to that position use the physics or fixed options. 

My understanding from this was that `fixed` would allow the nodes to have mass and affect other nodes, but remain locked in place, but this is not my observation. 

[here](https://jsfiddle.net/d630kq1b/41/) is a working JSFiddle replicating the issue. 

Thanks, any help is appreciated!

**Comment by Thomaash** [comment]
Hi @charleshtrenholm,

I'm not exactly sure what's the problem. Fixed nodes are just that fixed, they don't move at all, they're bolted to the wall if you will. That's exactly what should happen and what happens in the JSFiddle you provided (I don't see any movement at all, they're also on the same spots each time I run it).

Bonus tip: You can have physics disabled all the time and call `network.stabilize()` when you want to arrange the nodes (oneshot physics), there's no need to fiddle with events, change options etc.

**Comment by charleshtrenholm** [comment]
@Thomaash Thanks for your help! If you comment out lines 42-86 in the JS you'll see what the shape I'm expecting the orange nodes to be is. When the other nodes are added in they get pushed around. I removed the stabilization event the behavior is the same even when not calling `network.stabilize`. Essentially I want the nodes that have coordinates to keep their exact position provided and then have the other nodes use physics to push out from each other. I hope provides a better understanding

**Comment by Thomaash** [comment]
If I comment out lines 42 through 86 I get a syntax error.

**Comment by charleshtrenholm** [comment]
(here)[https://jsfiddle.net/37mgn10j/50/] is a version with the same code but no nodes governed by physics. Its supposed to be in a plus sign shape. If you uncomment the lines I mentioned you'll see that the orange nodes will be pushed around in the initial layout, I'm trying to see if I can have this same plus sign shape maintained even with the additional nodes.
